/*
 * Keycloak Admin REST API
 * This is a REST API reference for the Keycloak Admin REST API.
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.keycloak.www.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
/**
 * AccessTokenAuthorizationPermissions
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-03-11T12:00:50.005853600+07:00[Asia/Bangkok]")

public class AccessTokenAuthorizationPermissions {
  @JsonProperty("rsid")
  private String rsid = null;

  @JsonProperty("rsname")
  private String rsname = null;

  @JsonProperty("scopes")
  private List<String> scopes = null;

  @JsonProperty("claims")
  private Map<String, List<String>> claims = null;

  public AccessTokenAuthorizationPermissions rsid(String rsid) {
    this.rsid = rsid;
    return this;
  }

   /**
   * Get rsid
   * @return rsid
  **/
  public String getRsid() {
    return rsid;
  }

  public void setRsid(String rsid) {
    this.rsid = rsid;
  }

  public AccessTokenAuthorizationPermissions rsname(String rsname) {
    this.rsname = rsname;
    return this;
  }

   /**
   * Get rsname
   * @return rsname
  **/
  public String getRsname() {
    return rsname;
  }

  public void setRsname(String rsname) {
    this.rsname = rsname;
  }

  public AccessTokenAuthorizationPermissions scopes(List<String> scopes) {
    this.scopes = scopes;
    return this;
  }

  public AccessTokenAuthorizationPermissions addScopesItem(String scopesItem) {
    if (this.scopes == null) {
      this.scopes = new ArrayList<>();
    }
    this.scopes.add(scopesItem);
    return this;
  }

   /**
   * Get scopes
   * @return scopes
  **/
  public List<String> getScopes() {
    return scopes;
  }

  public void setScopes(List<String> scopes) {
    this.scopes = scopes;
  }

  public AccessTokenAuthorizationPermissions claims(Map<String, List<String>> claims) {
    this.claims = claims;
    return this;
  }

  public AccessTokenAuthorizationPermissions putClaimsItem(String key, List<String> claimsItem) {
    if (this.claims == null) {
      this.claims = new HashMap<>();
    }
    this.claims.put(key, claimsItem);
    return this;
  }

   /**
   * Get claims
   * @return claims
  **/
  public Map<String, List<String>> getClaims() {
    return claims;
  }

  public void setClaims(Map<String, List<String>> claims) {
    this.claims = claims;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AccessTokenAuthorizationPermissions accessTokenAuthorizationPermissions = (AccessTokenAuthorizationPermissions) o;
    return Objects.equals(this.rsid, accessTokenAuthorizationPermissions.rsid) &&
        Objects.equals(this.rsname, accessTokenAuthorizationPermissions.rsname) &&
        Objects.equals(this.scopes, accessTokenAuthorizationPermissions.scopes) &&
        Objects.equals(this.claims, accessTokenAuthorizationPermissions.claims);
  }

  @Override
  public int hashCode() {
    return Objects.hash(rsid, rsname, scopes, claims);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AccessTokenAuthorizationPermissions {\n");
    
    sb.append("    rsid: ").append(toIndentedString(rsid)).append("\n");
    sb.append("    rsname: ").append(toIndentedString(rsname)).append("\n");
    sb.append("    scopes: ").append(toIndentedString(scopes)).append("\n");
    sb.append("    claims: ").append(toIndentedString(claims)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
