/*
 * Keycloak Admin REST API
 * This is a REST API reference for the Keycloak Admin REST API.
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.keycloak.www.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * AccessTokenCnf
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-03-11T12:00:50.005853600+07:00[Asia/Bangkok]")

public class AccessTokenCnf {
  @JsonProperty("x5t#S256")
  private String x5tS256 = null;

  @JsonProperty("jkt")
  private String jkt = null;

  public AccessTokenCnf x5tS256(String x5tS256) {
    this.x5tS256 = x5tS256;
    return this;
  }

   /**
   * Get x5tS256
   * @return x5tS256
  **/
  public String getX5tS256() {
    return x5tS256;
  }

  public void setX5tS256(String x5tS256) {
    this.x5tS256 = x5tS256;
  }

  public AccessTokenCnf jkt(String jkt) {
    this.jkt = jkt;
    return this;
  }

   /**
   * Get jkt
   * @return jkt
  **/
  public String getJkt() {
    return jkt;
  }

  public void setJkt(String jkt) {
    this.jkt = jkt;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AccessTokenCnf accessTokenCnf = (AccessTokenCnf) o;
    return Objects.equals(this.x5tS256, accessTokenCnf.x5tS256) &&
        Objects.equals(this.jkt, accessTokenCnf.jkt);
  }

  @Override
  public int hashCode() {
    return Objects.hash(x5tS256, jkt);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AccessTokenCnf {\n");
    
    sb.append("    x5tS256: ").append(toIndentedString(x5tS256)).append("\n");
    sb.append("    jkt: ").append(toIndentedString(jkt)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
