/*
 * Keycloak Admin REST API
 * This is a REST API reference for the Keycloak Admin REST API.
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.keycloak.www.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

import java.util.ArrayList;
import java.util.List;
/**
 * AccessTokenRealmAccess
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-03-11T12:00:50.005853600+07:00[Asia/Bangkok]")

public class AccessTokenRealmAccess {
  @JsonProperty("roles")
  private List<String> roles = null;

  @JsonProperty("verify_caller")
  private Boolean verifyCaller = null;

  public AccessTokenRealmAccess roles(List<String> roles) {
    this.roles = roles;
    return this;
  }

  public AccessTokenRealmAccess addRolesItem(String rolesItem) {
    if (this.roles == null) {
      this.roles = new ArrayList<>();
    }
    this.roles.add(rolesItem);
    return this;
  }

   /**
   * Get roles
   * @return roles
  **/
  public List<String> getRoles() {
    return roles;
  }

  public void setRoles(List<String> roles) {
    this.roles = roles;
  }

  public AccessTokenRealmAccess verifyCaller(Boolean verifyCaller) {
    this.verifyCaller = verifyCaller;
    return this;
  }

   /**
   * Get verifyCaller
   * @return verifyCaller
  **/
  public Boolean isVerifyCaller() {
    return verifyCaller;
  }

  public void setVerifyCaller(Boolean verifyCaller) {
    this.verifyCaller = verifyCaller;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AccessTokenRealmAccess accessTokenRealmAccess = (AccessTokenRealmAccess) o;
    return Objects.equals(this.roles, accessTokenRealmAccess.roles) &&
        Objects.equals(this.verifyCaller, accessTokenRealmAccess.verifyCaller);
  }

  @Override
  public int hashCode() {
    return Objects.hash(roles, verifyCaller);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AccessTokenRealmAccess {\n");
    
    sb.append("    roles: ").append(toIndentedString(roles)).append("\n");
    sb.append("    verifyCaller: ").append(toIndentedString(verifyCaller)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
