/*
 * Keycloak Admin REST API
 * This is a REST API reference for the Keycloak Admin REST API.
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.keycloak.www.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * AdminrealmsClaims
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-03-11T12:00:50.005853600+07:00[Asia/Bangkok]")

public class AdminrealmsClaims {
  @JsonProperty("name")
  private Boolean name = null;

  @JsonProperty("username")
  private Boolean username = null;

  @JsonProperty("profile")
  private Boolean profile = null;

  @JsonProperty("picture")
  private Boolean picture = null;

  @JsonProperty("website")
  private Boolean website = null;

  @JsonProperty("email")
  private Boolean email = null;

  @JsonProperty("gender")
  private Boolean gender = null;

  @JsonProperty("locale")
  private Boolean locale = null;

  @JsonProperty("address")
  private Boolean address = null;

  @JsonProperty("phone")
  private Boolean phone = null;

  public AdminrealmsClaims name(Boolean name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  public Boolean isName() {
    return name;
  }

  public void setName(Boolean name) {
    this.name = name;
  }

  public AdminrealmsClaims username(Boolean username) {
    this.username = username;
    return this;
  }

   /**
   * Get username
   * @return username
  **/
  public Boolean isUsername() {
    return username;
  }

  public void setUsername(Boolean username) {
    this.username = username;
  }

  public AdminrealmsClaims profile(Boolean profile) {
    this.profile = profile;
    return this;
  }

   /**
   * Get profile
   * @return profile
  **/
  public Boolean isProfile() {
    return profile;
  }

  public void setProfile(Boolean profile) {
    this.profile = profile;
  }

  public AdminrealmsClaims picture(Boolean picture) {
    this.picture = picture;
    return this;
  }

   /**
   * Get picture
   * @return picture
  **/
  public Boolean isPicture() {
    return picture;
  }

  public void setPicture(Boolean picture) {
    this.picture = picture;
  }

  public AdminrealmsClaims website(Boolean website) {
    this.website = website;
    return this;
  }

   /**
   * Get website
   * @return website
  **/
  public Boolean isWebsite() {
    return website;
  }

  public void setWebsite(Boolean website) {
    this.website = website;
  }

  public AdminrealmsClaims email(Boolean email) {
    this.email = email;
    return this;
  }

   /**
   * Get email
   * @return email
  **/
  public Boolean isEmail() {
    return email;
  }

  public void setEmail(Boolean email) {
    this.email = email;
  }

  public AdminrealmsClaims gender(Boolean gender) {
    this.gender = gender;
    return this;
  }

   /**
   * Get gender
   * @return gender
  **/
  public Boolean isGender() {
    return gender;
  }

  public void setGender(Boolean gender) {
    this.gender = gender;
  }

  public AdminrealmsClaims locale(Boolean locale) {
    this.locale = locale;
    return this;
  }

   /**
   * Get locale
   * @return locale
  **/
  public Boolean isLocale() {
    return locale;
  }

  public void setLocale(Boolean locale) {
    this.locale = locale;
  }

  public AdminrealmsClaims address(Boolean address) {
    this.address = address;
    return this;
  }

   /**
   * Get address
   * @return address
  **/
  public Boolean isAddress() {
    return address;
  }

  public void setAddress(Boolean address) {
    this.address = address;
  }

  public AdminrealmsClaims phone(Boolean phone) {
    this.phone = phone;
    return this;
  }

   /**
   * Get phone
   * @return phone
  **/
  public Boolean isPhone() {
    return phone;
  }

  public void setPhone(Boolean phone) {
    this.phone = phone;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AdminrealmsClaims adminrealmsClaims = (AdminrealmsClaims) o;
    return Objects.equals(this.name, adminrealmsClaims.name) &&
        Objects.equals(this.username, adminrealmsClaims.username) &&
        Objects.equals(this.profile, adminrealmsClaims.profile) &&
        Objects.equals(this.picture, adminrealmsClaims.picture) &&
        Objects.equals(this.website, adminrealmsClaims.website) &&
        Objects.equals(this.email, adminrealmsClaims.email) &&
        Objects.equals(this.gender, adminrealmsClaims.gender) &&
        Objects.equals(this.locale, adminrealmsClaims.locale) &&
        Objects.equals(this.address, adminrealmsClaims.address) &&
        Objects.equals(this.phone, adminrealmsClaims.phone);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, username, profile, picture, website, email, gender, locale, address, phone);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AdminrealmsClaims {\n");
    
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    username: ").append(toIndentedString(username)).append("\n");
    sb.append("    profile: ").append(toIndentedString(profile)).append("\n");
    sb.append("    picture: ").append(toIndentedString(picture)).append("\n");
    sb.append("    website: ").append(toIndentedString(website)).append("\n");
    sb.append("    email: ").append(toIndentedString(email)).append("\n");
    sb.append("    gender: ").append(toIndentedString(gender)).append("\n");
    sb.append("    locale: ").append(toIndentedString(locale)).append("\n");
    sb.append("    address: ").append(toIndentedString(address)).append("\n");
    sb.append("    phone: ").append(toIndentedString(phone)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
