/*
 * Keycloak Admin REST API
 * This is a REST API reference for the Keycloak Admin REST API.
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.keycloak.www.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

import java.util.HashMap;
import java.util.List;
import java.util.Map;
/**
 * AdminrealmsUserFederationProviders
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-03-11T12:00:50.005853600+07:00[Asia/Bangkok]")

public class AdminrealmsUserFederationProviders {
  @JsonProperty("id")
  private String id = null;

  @JsonProperty("displayName")
  private String displayName = null;

  @JsonProperty("providerName")
  private String providerName = null;

  @JsonProperty("config")
  private Map<String, String> config = null;

  @JsonProperty("priority")
  private Integer priority = null;

  @JsonProperty("fullSyncPeriod")
  private Integer fullSyncPeriod = null;

  @JsonProperty("changedSyncPeriod")
  private Integer changedSyncPeriod = null;

  @JsonProperty("lastSync")
  private Integer lastSync = null;

  public AdminrealmsUserFederationProviders id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public AdminrealmsUserFederationProviders displayName(String displayName) {
    this.displayName = displayName;
    return this;
  }

   /**
   * Get displayName
   * @return displayName
  **/
  public String getDisplayName() {
    return displayName;
  }

  public void setDisplayName(String displayName) {
    this.displayName = displayName;
  }

  public AdminrealmsUserFederationProviders providerName(String providerName) {
    this.providerName = providerName;
    return this;
  }

   /**
   * Get providerName
   * @return providerName
  **/
  public String getProviderName() {
    return providerName;
  }

  public void setProviderName(String providerName) {
    this.providerName = providerName;
  }

  public AdminrealmsUserFederationProviders config(Map<String, String> config) {
    this.config = config;
    return this;
  }

  public AdminrealmsUserFederationProviders putConfigItem(String key, String configItem) {
    if (this.config == null) {
      this.config = new HashMap<>();
    }
    this.config.put(key, configItem);
    return this;
  }

   /**
   * Get config
   * @return config
  **/
  public Map<String, String> getConfig() {
    return config;
  }

  public void setConfig(Map<String, String> config) {
    this.config = config;
  }

  public AdminrealmsUserFederationProviders priority(Integer priority) {
    this.priority = priority;
    return this;
  }

   /**
   * Get priority
   * @return priority
  **/
  public Integer getPriority() {
    return priority;
  }

  public void setPriority(Integer priority) {
    this.priority = priority;
  }

  public AdminrealmsUserFederationProviders fullSyncPeriod(Integer fullSyncPeriod) {
    this.fullSyncPeriod = fullSyncPeriod;
    return this;
  }

   /**
   * Get fullSyncPeriod
   * @return fullSyncPeriod
  **/
  public Integer getFullSyncPeriod() {
    return fullSyncPeriod;
  }

  public void setFullSyncPeriod(Integer fullSyncPeriod) {
    this.fullSyncPeriod = fullSyncPeriod;
  }

  public AdminrealmsUserFederationProviders changedSyncPeriod(Integer changedSyncPeriod) {
    this.changedSyncPeriod = changedSyncPeriod;
    return this;
  }

   /**
   * Get changedSyncPeriod
   * @return changedSyncPeriod
  **/
  public Integer getChangedSyncPeriod() {
    return changedSyncPeriod;
  }

  public void setChangedSyncPeriod(Integer changedSyncPeriod) {
    this.changedSyncPeriod = changedSyncPeriod;
  }

  public AdminrealmsUserFederationProviders lastSync(Integer lastSync) {
    this.lastSync = lastSync;
    return this;
  }

   /**
   * Get lastSync
   * @return lastSync
  **/
  public Integer getLastSync() {
    return lastSync;
  }

  public void setLastSync(Integer lastSync) {
    this.lastSync = lastSync;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AdminrealmsUserFederationProviders adminrealmsUserFederationProviders = (AdminrealmsUserFederationProviders) o;
    return Objects.equals(this.id, adminrealmsUserFederationProviders.id) &&
        Objects.equals(this.displayName, adminrealmsUserFederationProviders.displayName) &&
        Objects.equals(this.providerName, adminrealmsUserFederationProviders.providerName) &&
        Objects.equals(this.config, adminrealmsUserFederationProviders.config) &&
        Objects.equals(this.priority, adminrealmsUserFederationProviders.priority) &&
        Objects.equals(this.fullSyncPeriod, adminrealmsUserFederationProviders.fullSyncPeriod) &&
        Objects.equals(this.changedSyncPeriod, adminrealmsUserFederationProviders.changedSyncPeriod) &&
        Objects.equals(this.lastSync, adminrealmsUserFederationProviders.lastSync);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, displayName, providerName, config, priority, fullSyncPeriod, changedSyncPeriod, lastSync);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AdminrealmsUserFederationProviders {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    displayName: ").append(toIndentedString(displayName)).append("\n");
    sb.append("    providerName: ").append(toIndentedString(providerName)).append("\n");
    sb.append("    config: ").append(toIndentedString(config)).append("\n");
    sb.append("    priority: ").append(toIndentedString(priority)).append("\n");
    sb.append("    fullSyncPeriod: ").append(toIndentedString(fullSyncPeriod)).append("\n");
    sb.append("    changedSyncPeriod: ").append(toIndentedString(changedSyncPeriod)).append("\n");
    sb.append("    lastSync: ").append(toIndentedString(lastSync)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
