/*
 * Keycloak Admin REST API
 * This is a REST API reference for the Keycloak Admin REST API.
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.keycloak.www.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * AdminrealmsCredentials
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-03-11T12:00:50.005853600+07:00[Asia/Bangkok]")

public class AdminrealmsCredentials {
  @JsonProperty("id")
  private String id = null;

  @JsonProperty("type")
  private String type = null;

  @JsonProperty("userLabel")
  private String userLabel = null;

  @JsonProperty("createdDate")
  private Long createdDate = null;

  @JsonProperty("secretData")
  private String secretData = null;

  @JsonProperty("credentialData")
  private String credentialData = null;

  @JsonProperty("priority")
  private Integer priority = null;

  @JsonProperty("value")
  private String value = null;

  @JsonProperty("temporary")
  private Boolean temporary = null;

  @JsonProperty("device")
  private String device = null;

  @JsonProperty("hashedSaltedValue")
  private String hashedSaltedValue = null;

  @JsonProperty("salt")
  private String salt = null;

  @JsonProperty("hashIterations")
  private Integer hashIterations = null;

  @JsonProperty("counter")
  private Integer counter = null;

  @JsonProperty("algorithm")
  private String algorithm = null;

  @JsonProperty("digits")
  private Integer digits = null;

  @JsonProperty("period")
  private Integer period = null;

  @JsonProperty("config")
  private Object config = null;

  public AdminrealmsCredentials id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public AdminrealmsCredentials type(String type) {
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  public String getType() {
    return type;
  }

  public void setType(String type) {
    this.type = type;
  }

  public AdminrealmsCredentials userLabel(String userLabel) {
    this.userLabel = userLabel;
    return this;
  }

   /**
   * Get userLabel
   * @return userLabel
  **/
  public String getUserLabel() {
    return userLabel;
  }

  public void setUserLabel(String userLabel) {
    this.userLabel = userLabel;
  }

  public AdminrealmsCredentials createdDate(Long createdDate) {
    this.createdDate = createdDate;
    return this;
  }

   /**
   * Get createdDate
   * @return createdDate
  **/
  public Long getCreatedDate() {
    return createdDate;
  }

  public void setCreatedDate(Long createdDate) {
    this.createdDate = createdDate;
  }

  public AdminrealmsCredentials secretData(String secretData) {
    this.secretData = secretData;
    return this;
  }

   /**
   * Get secretData
   * @return secretData
  **/
  public String getSecretData() {
    return secretData;
  }

  public void setSecretData(String secretData) {
    this.secretData = secretData;
  }

  public AdminrealmsCredentials credentialData(String credentialData) {
    this.credentialData = credentialData;
    return this;
  }

   /**
   * Get credentialData
   * @return credentialData
  **/
  public String getCredentialData() {
    return credentialData;
  }

  public void setCredentialData(String credentialData) {
    this.credentialData = credentialData;
  }

  public AdminrealmsCredentials priority(Integer priority) {
    this.priority = priority;
    return this;
  }

   /**
   * Get priority
   * @return priority
  **/
  public Integer getPriority() {
    return priority;
  }

  public void setPriority(Integer priority) {
    this.priority = priority;
  }

  public AdminrealmsCredentials value(String value) {
    this.value = value;
    return this;
  }

   /**
   * Get value
   * @return value
  **/
  public String getValue() {
    return value;
  }

  public void setValue(String value) {
    this.value = value;
  }

  public AdminrealmsCredentials temporary(Boolean temporary) {
    this.temporary = temporary;
    return this;
  }

   /**
   * Get temporary
   * @return temporary
  **/
  public Boolean isTemporary() {
    return temporary;
  }

  public void setTemporary(Boolean temporary) {
    this.temporary = temporary;
  }

  public AdminrealmsCredentials device(String device) {
    this.device = device;
    return this;
  }

   /**
   * Get device
   * @return device
  **/
  public String getDevice() {
    return device;
  }

  public void setDevice(String device) {
    this.device = device;
  }

  public AdminrealmsCredentials hashedSaltedValue(String hashedSaltedValue) {
    this.hashedSaltedValue = hashedSaltedValue;
    return this;
  }

   /**
   * Get hashedSaltedValue
   * @return hashedSaltedValue
  **/
  public String getHashedSaltedValue() {
    return hashedSaltedValue;
  }

  public void setHashedSaltedValue(String hashedSaltedValue) {
    this.hashedSaltedValue = hashedSaltedValue;
  }

  public AdminrealmsCredentials salt(String salt) {
    this.salt = salt;
    return this;
  }

   /**
   * Get salt
   * @return salt
  **/
  public String getSalt() {
    return salt;
  }

  public void setSalt(String salt) {
    this.salt = salt;
  }

  public AdminrealmsCredentials hashIterations(Integer hashIterations) {
    this.hashIterations = hashIterations;
    return this;
  }

   /**
   * Get hashIterations
   * @return hashIterations
  **/
  public Integer getHashIterations() {
    return hashIterations;
  }

  public void setHashIterations(Integer hashIterations) {
    this.hashIterations = hashIterations;
  }

  public AdminrealmsCredentials counter(Integer counter) {
    this.counter = counter;
    return this;
  }

   /**
   * Get counter
   * @return counter
  **/
  public Integer getCounter() {
    return counter;
  }

  public void setCounter(Integer counter) {
    this.counter = counter;
  }

  public AdminrealmsCredentials algorithm(String algorithm) {
    this.algorithm = algorithm;
    return this;
  }

   /**
   * Get algorithm
   * @return algorithm
  **/
  public String getAlgorithm() {
    return algorithm;
  }

  public void setAlgorithm(String algorithm) {
    this.algorithm = algorithm;
  }

  public AdminrealmsCredentials digits(Integer digits) {
    this.digits = digits;
    return this;
  }

   /**
   * Get digits
   * @return digits
  **/
  public Integer getDigits() {
    return digits;
  }

  public void setDigits(Integer digits) {
    this.digits = digits;
  }

  public AdminrealmsCredentials period(Integer period) {
    this.period = period;
    return this;
  }

   /**
   * Get period
   * @return period
  **/
  public Integer getPeriod() {
    return period;
  }

  public void setPeriod(Integer period) {
    this.period = period;
  }

  public AdminrealmsCredentials config(Object config) {
    this.config = config;
    return this;
  }

   /**
   * Get config
   * @return config
  **/
  public Object getConfig() {
    return config;
  }

  public void setConfig(Object config) {
    this.config = config;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AdminrealmsCredentials adminrealmsCredentials = (AdminrealmsCredentials) o;
    return Objects.equals(this.id, adminrealmsCredentials.id) &&
        Objects.equals(this.type, adminrealmsCredentials.type) &&
        Objects.equals(this.userLabel, adminrealmsCredentials.userLabel) &&
        Objects.equals(this.createdDate, adminrealmsCredentials.createdDate) &&
        Objects.equals(this.secretData, adminrealmsCredentials.secretData) &&
        Objects.equals(this.credentialData, adminrealmsCredentials.credentialData) &&
        Objects.equals(this.priority, adminrealmsCredentials.priority) &&
        Objects.equals(this.value, adminrealmsCredentials.value) &&
        Objects.equals(this.temporary, adminrealmsCredentials.temporary) &&
        Objects.equals(this.device, adminrealmsCredentials.device) &&
        Objects.equals(this.hashedSaltedValue, adminrealmsCredentials.hashedSaltedValue) &&
        Objects.equals(this.salt, adminrealmsCredentials.salt) &&
        Objects.equals(this.hashIterations, adminrealmsCredentials.hashIterations) &&
        Objects.equals(this.counter, adminrealmsCredentials.counter) &&
        Objects.equals(this.algorithm, adminrealmsCredentials.algorithm) &&
        Objects.equals(this.digits, adminrealmsCredentials.digits) &&
        Objects.equals(this.period, adminrealmsCredentials.period) &&
        Objects.equals(this.config, adminrealmsCredentials.config);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, type, userLabel, createdDate, secretData, credentialData, priority, value, temporary, device, hashedSaltedValue, salt, hashIterations, counter, algorithm, digits, period, config);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AdminrealmsCredentials {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    userLabel: ").append(toIndentedString(userLabel)).append("\n");
    sb.append("    createdDate: ").append(toIndentedString(createdDate)).append("\n");
    sb.append("    secretData: ").append(toIndentedString(secretData)).append("\n");
    sb.append("    credentialData: ").append(toIndentedString(credentialData)).append("\n");
    sb.append("    priority: ").append(toIndentedString(priority)).append("\n");
    sb.append("    value: ").append(toIndentedString(value)).append("\n");
    sb.append("    temporary: ").append(toIndentedString(temporary)).append("\n");
    sb.append("    device: ").append(toIndentedString(device)).append("\n");
    sb.append("    hashedSaltedValue: ").append(toIndentedString(hashedSaltedValue)).append("\n");
    sb.append("    salt: ").append(toIndentedString(salt)).append("\n");
    sb.append("    hashIterations: ").append(toIndentedString(hashIterations)).append("\n");
    sb.append("    counter: ").append(toIndentedString(counter)).append("\n");
    sb.append("    algorithm: ").append(toIndentedString(algorithm)).append("\n");
    sb.append("    digits: ").append(toIndentedString(digits)).append("\n");
    sb.append("    period: ").append(toIndentedString(period)).append("\n");
    sb.append("    config: ").append(toIndentedString(config)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
