/*
 * Keycloak Admin REST API
 * This is a REST API reference for the Keycloak Admin REST API.
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.keycloak.www.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

import java.util.ArrayList;
import java.util.List;
import org.keycloak.www.client.AdminrealmsClientProfilesExecutors;
/**
 * AdminrealmsClientProfilesProfiles
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-03-11T12:00:50.005853600+07:00[Asia/Bangkok]")

public class AdminrealmsClientProfilesProfiles {
  @JsonProperty("name")
  private String name = null;

  @JsonProperty("description")
  private String description = null;

  @JsonProperty("executors")
  private List<AdminrealmsClientProfilesExecutors> executors = null;

  public AdminrealmsClientProfilesProfiles name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public AdminrealmsClientProfilesProfiles description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public AdminrealmsClientProfilesProfiles executors(List<AdminrealmsClientProfilesExecutors> executors) {
    this.executors = executors;
    return this;
  }

  public AdminrealmsClientProfilesProfiles addExecutorsItem(AdminrealmsClientProfilesExecutors executorsItem) {
    if (this.executors == null) {
      this.executors = new ArrayList<>();
    }
    this.executors.add(executorsItem);
    return this;
  }

   /**
   * Get executors
   * @return executors
  **/
  public List<AdminrealmsClientProfilesExecutors> getExecutors() {
    return executors;
  }

  public void setExecutors(List<AdminrealmsClientProfilesExecutors> executors) {
    this.executors = executors;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AdminrealmsClientProfilesProfiles adminrealmsClientProfilesProfiles = (AdminrealmsClientProfilesProfiles) o;
    return Objects.equals(this.name, adminrealmsClientProfilesProfiles.name) &&
        Objects.equals(this.description, adminrealmsClientProfilesProfiles.description) &&
        Objects.equals(this.executors, adminrealmsClientProfilesProfiles.executors);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, description, executors);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AdminrealmsClientProfilesProfiles {\n");
    
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    executors: ").append(toIndentedString(executors)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
