/*
 * Keycloak Admin REST API
 * This is a REST API reference for the Keycloak Admin REST API.
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.keycloak.www.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

import java.util.HashMap;
import java.util.List;
import java.util.Map;
/**
 * AdminrealmsUserFederationMappers
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-03-11T12:00:50.005853600+07:00[Asia/Bangkok]")

public class AdminrealmsUserFederationMappers {
  @JsonProperty("id")
  private String id = null;

  @JsonProperty("name")
  private String name = null;

  @JsonProperty("federationProviderDisplayName")
  private String federationProviderDisplayName = null;

  @JsonProperty("federationMapperType")
  private String federationMapperType = null;

  @JsonProperty("config")
  private Map<String, String> config = null;

  public AdminrealmsUserFederationMappers id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public AdminrealmsUserFederationMappers name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public AdminrealmsUserFederationMappers federationProviderDisplayName(String federationProviderDisplayName) {
    this.federationProviderDisplayName = federationProviderDisplayName;
    return this;
  }

   /**
   * Get federationProviderDisplayName
   * @return federationProviderDisplayName
  **/
  public String getFederationProviderDisplayName() {
    return federationProviderDisplayName;
  }

  public void setFederationProviderDisplayName(String federationProviderDisplayName) {
    this.federationProviderDisplayName = federationProviderDisplayName;
  }

  public AdminrealmsUserFederationMappers federationMapperType(String federationMapperType) {
    this.federationMapperType = federationMapperType;
    return this;
  }

   /**
   * Get federationMapperType
   * @return federationMapperType
  **/
  public String getFederationMapperType() {
    return federationMapperType;
  }

  public void setFederationMapperType(String federationMapperType) {
    this.federationMapperType = federationMapperType;
  }

  public AdminrealmsUserFederationMappers config(Map<String, String> config) {
    this.config = config;
    return this;
  }

  public AdminrealmsUserFederationMappers putConfigItem(String key, String configItem) {
    if (this.config == null) {
      this.config = new HashMap<>();
    }
    this.config.put(key, configItem);
    return this;
  }

   /**
   * Get config
   * @return config
  **/
  public Map<String, String> getConfig() {
    return config;
  }

  public void setConfig(Map<String, String> config) {
    this.config = config;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AdminrealmsUserFederationMappers adminrealmsUserFederationMappers = (AdminrealmsUserFederationMappers) o;
    return Objects.equals(this.id, adminrealmsUserFederationMappers.id) &&
        Objects.equals(this.name, adminrealmsUserFederationMappers.name) &&
        Objects.equals(this.federationProviderDisplayName, adminrealmsUserFederationMappers.federationProviderDisplayName) &&
        Objects.equals(this.federationMapperType, adminrealmsUserFederationMappers.federationMapperType) &&
        Objects.equals(this.config, adminrealmsUserFederationMappers.config);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, federationProviderDisplayName, federationMapperType, config);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AdminrealmsUserFederationMappers {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    federationProviderDisplayName: ").append(toIndentedString(federationProviderDisplayName)).append("\n");
    sb.append("    federationMapperType: ").append(toIndentedString(federationMapperType)).append("\n");
    sb.append("    config: ").append(toIndentedString(config)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
