/*
 * Keycloak Admin REST API
 * This is a REST API reference for the Keycloak Admin REST API.
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.keycloak.www.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

import java.util.ArrayList;
import java.util.List;
import org.keycloak.www.client.AdminrealmsAuthenticationExecutions;
/**
 * AdminrealmsAuthenticationFlows
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-03-11T12:00:50.005853600+07:00[Asia/Bangkok]")

public class AdminrealmsAuthenticationFlows {
  @JsonProperty("id")
  private String id = null;

  @JsonProperty("alias")
  private String alias = null;

  @JsonProperty("description")
  private String description = null;

  @JsonProperty("providerId")
  private String providerId = null;

  @JsonProperty("topLevel")
  private Boolean topLevel = null;

  @JsonProperty("builtIn")
  private Boolean builtIn = null;

  @JsonProperty("authenticationExecutions")
  private List<AdminrealmsAuthenticationExecutions> authenticationExecutions = null;

  public AdminrealmsAuthenticationFlows id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public AdminrealmsAuthenticationFlows alias(String alias) {
    this.alias = alias;
    return this;
  }

   /**
   * Get alias
   * @return alias
  **/
  public String getAlias() {
    return alias;
  }

  public void setAlias(String alias) {
    this.alias = alias;
  }

  public AdminrealmsAuthenticationFlows description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public AdminrealmsAuthenticationFlows providerId(String providerId) {
    this.providerId = providerId;
    return this;
  }

   /**
   * Get providerId
   * @return providerId
  **/
  public String getProviderId() {
    return providerId;
  }

  public void setProviderId(String providerId) {
    this.providerId = providerId;
  }

  public AdminrealmsAuthenticationFlows topLevel(Boolean topLevel) {
    this.topLevel = topLevel;
    return this;
  }

   /**
   * Get topLevel
   * @return topLevel
  **/
  public Boolean isTopLevel() {
    return topLevel;
  }

  public void setTopLevel(Boolean topLevel) {
    this.topLevel = topLevel;
  }

  public AdminrealmsAuthenticationFlows builtIn(Boolean builtIn) {
    this.builtIn = builtIn;
    return this;
  }

   /**
   * Get builtIn
   * @return builtIn
  **/
  public Boolean isBuiltIn() {
    return builtIn;
  }

  public void setBuiltIn(Boolean builtIn) {
    this.builtIn = builtIn;
  }

  public AdminrealmsAuthenticationFlows authenticationExecutions(List<AdminrealmsAuthenticationExecutions> authenticationExecutions) {
    this.authenticationExecutions = authenticationExecutions;
    return this;
  }

  public AdminrealmsAuthenticationFlows addAuthenticationExecutionsItem(AdminrealmsAuthenticationExecutions authenticationExecutionsItem) {
    if (this.authenticationExecutions == null) {
      this.authenticationExecutions = new ArrayList<>();
    }
    this.authenticationExecutions.add(authenticationExecutionsItem);
    return this;
  }

   /**
   * Get authenticationExecutions
   * @return authenticationExecutions
  **/
  public List<AdminrealmsAuthenticationExecutions> getAuthenticationExecutions() {
    return authenticationExecutions;
  }

  public void setAuthenticationExecutions(List<AdminrealmsAuthenticationExecutions> authenticationExecutions) {
    this.authenticationExecutions = authenticationExecutions;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AdminrealmsAuthenticationFlows adminrealmsAuthenticationFlows = (AdminrealmsAuthenticationFlows) o;
    return Objects.equals(this.id, adminrealmsAuthenticationFlows.id) &&
        Objects.equals(this.alias, adminrealmsAuthenticationFlows.alias) &&
        Objects.equals(this.description, adminrealmsAuthenticationFlows.description) &&
        Objects.equals(this.providerId, adminrealmsAuthenticationFlows.providerId) &&
        Objects.equals(this.topLevel, adminrealmsAuthenticationFlows.topLevel) &&
        Objects.equals(this.builtIn, adminrealmsAuthenticationFlows.builtIn) &&
        Objects.equals(this.authenticationExecutions, adminrealmsAuthenticationFlows.authenticationExecutions);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, alias, description, providerId, topLevel, builtIn, authenticationExecutions);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AdminrealmsAuthenticationFlows {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    alias: ").append(toIndentedString(alias)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    providerId: ").append(toIndentedString(providerId)).append("\n");
    sb.append("    topLevel: ").append(toIndentedString(topLevel)).append("\n");
    sb.append("    builtIn: ").append(toIndentedString(builtIn)).append("\n");
    sb.append("    authenticationExecutions: ").append(toIndentedString(authenticationExecutions)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
