/*
 * Keycloak Admin REST API
 * This is a REST API reference for the Keycloak Admin REST API.
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.keycloak.www.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.keycloak.www.client.AdminrealmsAdminPermissionsClientProtocolMappers;
/**
 * AdminrealmsClientTemplates
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-03-11T12:00:50.005853600+07:00[Asia/Bangkok]")

public class AdminrealmsClientTemplates {
  @JsonProperty("id")
  private String id = null;

  @JsonProperty("name")
  private String name = null;

  @JsonProperty("description")
  private String description = null;

  @JsonProperty("protocol")
  private String protocol = null;

  @JsonProperty("fullScopeAllowed")
  private Boolean fullScopeAllowed = null;

  @JsonProperty("bearerOnly")
  private Boolean bearerOnly = null;

  @JsonProperty("consentRequired")
  private Boolean consentRequired = null;

  @JsonProperty("standardFlowEnabled")
  private Boolean standardFlowEnabled = null;

  @JsonProperty("implicitFlowEnabled")
  private Boolean implicitFlowEnabled = null;

  @JsonProperty("directAccessGrantsEnabled")
  private Boolean directAccessGrantsEnabled = null;

  @JsonProperty("serviceAccountsEnabled")
  private Boolean serviceAccountsEnabled = null;

  @JsonProperty("publicClient")
  private Boolean publicClient = null;

  @JsonProperty("frontchannelLogout")
  private Boolean frontchannelLogout = null;

  @JsonProperty("attributes")
  private Map<String, String> attributes = null;

  @JsonProperty("protocolMappers")
  private List<AdminrealmsAdminPermissionsClientProtocolMappers> protocolMappers = null;

  public AdminrealmsClientTemplates id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public AdminrealmsClientTemplates name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public AdminrealmsClientTemplates description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public AdminrealmsClientTemplates protocol(String protocol) {
    this.protocol = protocol;
    return this;
  }

   /**
   * Get protocol
   * @return protocol
  **/
  public String getProtocol() {
    return protocol;
  }

  public void setProtocol(String protocol) {
    this.protocol = protocol;
  }

  public AdminrealmsClientTemplates fullScopeAllowed(Boolean fullScopeAllowed) {
    this.fullScopeAllowed = fullScopeAllowed;
    return this;
  }

   /**
   * Get fullScopeAllowed
   * @return fullScopeAllowed
  **/
  public Boolean isFullScopeAllowed() {
    return fullScopeAllowed;
  }

  public void setFullScopeAllowed(Boolean fullScopeAllowed) {
    this.fullScopeAllowed = fullScopeAllowed;
  }

  public AdminrealmsClientTemplates bearerOnly(Boolean bearerOnly) {
    this.bearerOnly = bearerOnly;
    return this;
  }

   /**
   * Get bearerOnly
   * @return bearerOnly
  **/
  public Boolean isBearerOnly() {
    return bearerOnly;
  }

  public void setBearerOnly(Boolean bearerOnly) {
    this.bearerOnly = bearerOnly;
  }

  public AdminrealmsClientTemplates consentRequired(Boolean consentRequired) {
    this.consentRequired = consentRequired;
    return this;
  }

   /**
   * Get consentRequired
   * @return consentRequired
  **/
  public Boolean isConsentRequired() {
    return consentRequired;
  }

  public void setConsentRequired(Boolean consentRequired) {
    this.consentRequired = consentRequired;
  }

  public AdminrealmsClientTemplates standardFlowEnabled(Boolean standardFlowEnabled) {
    this.standardFlowEnabled = standardFlowEnabled;
    return this;
  }

   /**
   * Get standardFlowEnabled
   * @return standardFlowEnabled
  **/
  public Boolean isStandardFlowEnabled() {
    return standardFlowEnabled;
  }

  public void setStandardFlowEnabled(Boolean standardFlowEnabled) {
    this.standardFlowEnabled = standardFlowEnabled;
  }

  public AdminrealmsClientTemplates implicitFlowEnabled(Boolean implicitFlowEnabled) {
    this.implicitFlowEnabled = implicitFlowEnabled;
    return this;
  }

   /**
   * Get implicitFlowEnabled
   * @return implicitFlowEnabled
  **/
  public Boolean isImplicitFlowEnabled() {
    return implicitFlowEnabled;
  }

  public void setImplicitFlowEnabled(Boolean implicitFlowEnabled) {
    this.implicitFlowEnabled = implicitFlowEnabled;
  }

  public AdminrealmsClientTemplates directAccessGrantsEnabled(Boolean directAccessGrantsEnabled) {
    this.directAccessGrantsEnabled = directAccessGrantsEnabled;
    return this;
  }

   /**
   * Get directAccessGrantsEnabled
   * @return directAccessGrantsEnabled
  **/
  public Boolean isDirectAccessGrantsEnabled() {
    return directAccessGrantsEnabled;
  }

  public void setDirectAccessGrantsEnabled(Boolean directAccessGrantsEnabled) {
    this.directAccessGrantsEnabled = directAccessGrantsEnabled;
  }

  public AdminrealmsClientTemplates serviceAccountsEnabled(Boolean serviceAccountsEnabled) {
    this.serviceAccountsEnabled = serviceAccountsEnabled;
    return this;
  }

   /**
   * Get serviceAccountsEnabled
   * @return serviceAccountsEnabled
  **/
  public Boolean isServiceAccountsEnabled() {
    return serviceAccountsEnabled;
  }

  public void setServiceAccountsEnabled(Boolean serviceAccountsEnabled) {
    this.serviceAccountsEnabled = serviceAccountsEnabled;
  }

  public AdminrealmsClientTemplates publicClient(Boolean publicClient) {
    this.publicClient = publicClient;
    return this;
  }

   /**
   * Get publicClient
   * @return publicClient
  **/
  public Boolean isPublicClient() {
    return publicClient;
  }

  public void setPublicClient(Boolean publicClient) {
    this.publicClient = publicClient;
  }

  public AdminrealmsClientTemplates frontchannelLogout(Boolean frontchannelLogout) {
    this.frontchannelLogout = frontchannelLogout;
    return this;
  }

   /**
   * Get frontchannelLogout
   * @return frontchannelLogout
  **/
  public Boolean isFrontchannelLogout() {
    return frontchannelLogout;
  }

  public void setFrontchannelLogout(Boolean frontchannelLogout) {
    this.frontchannelLogout = frontchannelLogout;
  }

  public AdminrealmsClientTemplates attributes(Map<String, String> attributes) {
    this.attributes = attributes;
    return this;
  }

  public AdminrealmsClientTemplates putAttributesItem(String key, String attributesItem) {
    if (this.attributes == null) {
      this.attributes = new HashMap<>();
    }
    this.attributes.put(key, attributesItem);
    return this;
  }

   /**
   * Get attributes
   * @return attributes
  **/
  public Map<String, String> getAttributes() {
    return attributes;
  }

  public void setAttributes(Map<String, String> attributes) {
    this.attributes = attributes;
  }

  public AdminrealmsClientTemplates protocolMappers(List<AdminrealmsAdminPermissionsClientProtocolMappers> protocolMappers) {
    this.protocolMappers = protocolMappers;
    return this;
  }

  public AdminrealmsClientTemplates addProtocolMappersItem(AdminrealmsAdminPermissionsClientProtocolMappers protocolMappersItem) {
    if (this.protocolMappers == null) {
      this.protocolMappers = new ArrayList<>();
    }
    this.protocolMappers.add(protocolMappersItem);
    return this;
  }

   /**
   * Get protocolMappers
   * @return protocolMappers
  **/
  public List<AdminrealmsAdminPermissionsClientProtocolMappers> getProtocolMappers() {
    return protocolMappers;
  }

  public void setProtocolMappers(List<AdminrealmsAdminPermissionsClientProtocolMappers> protocolMappers) {
    this.protocolMappers = protocolMappers;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AdminrealmsClientTemplates adminrealmsClientTemplates = (AdminrealmsClientTemplates) o;
    return Objects.equals(this.id, adminrealmsClientTemplates.id) &&
        Objects.equals(this.name, adminrealmsClientTemplates.name) &&
        Objects.equals(this.description, adminrealmsClientTemplates.description) &&
        Objects.equals(this.protocol, adminrealmsClientTemplates.protocol) &&
        Objects.equals(this.fullScopeAllowed, adminrealmsClientTemplates.fullScopeAllowed) &&
        Objects.equals(this.bearerOnly, adminrealmsClientTemplates.bearerOnly) &&
        Objects.equals(this.consentRequired, adminrealmsClientTemplates.consentRequired) &&
        Objects.equals(this.standardFlowEnabled, adminrealmsClientTemplates.standardFlowEnabled) &&
        Objects.equals(this.implicitFlowEnabled, adminrealmsClientTemplates.implicitFlowEnabled) &&
        Objects.equals(this.directAccessGrantsEnabled, adminrealmsClientTemplates.directAccessGrantsEnabled) &&
        Objects.equals(this.serviceAccountsEnabled, adminrealmsClientTemplates.serviceAccountsEnabled) &&
        Objects.equals(this.publicClient, adminrealmsClientTemplates.publicClient) &&
        Objects.equals(this.frontchannelLogout, adminrealmsClientTemplates.frontchannelLogout) &&
        Objects.equals(this.attributes, adminrealmsClientTemplates.attributes) &&
        Objects.equals(this.protocolMappers, adminrealmsClientTemplates.protocolMappers);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, description, protocol, fullScopeAllowed, bearerOnly, consentRequired, standardFlowEnabled, implicitFlowEnabled, directAccessGrantsEnabled, serviceAccountsEnabled, publicClient, frontchannelLogout, attributes, protocolMappers);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AdminrealmsClientTemplates {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    protocol: ").append(toIndentedString(protocol)).append("\n");
    sb.append("    fullScopeAllowed: ").append(toIndentedString(fullScopeAllowed)).append("\n");
    sb.append("    bearerOnly: ").append(toIndentedString(bearerOnly)).append("\n");
    sb.append("    consentRequired: ").append(toIndentedString(consentRequired)).append("\n");
    sb.append("    standardFlowEnabled: ").append(toIndentedString(standardFlowEnabled)).append("\n");
    sb.append("    implicitFlowEnabled: ").append(toIndentedString(implicitFlowEnabled)).append("\n");
    sb.append("    directAccessGrantsEnabled: ").append(toIndentedString(directAccessGrantsEnabled)).append("\n");
    sb.append("    serviceAccountsEnabled: ").append(toIndentedString(serviceAccountsEnabled)).append("\n");
    sb.append("    publicClient: ").append(toIndentedString(publicClient)).append("\n");
    sb.append("    frontchannelLogout: ").append(toIndentedString(frontchannelLogout)).append("\n");
    sb.append("    attributes: ").append(toIndentedString(attributes)).append("\n");
    sb.append("    protocolMappers: ").append(toIndentedString(protocolMappers)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
