/*
 * Keycloak Admin REST API
 * This is a REST API reference for the Keycloak Admin REST API.
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.keycloak.www.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

import java.util.ArrayList;
import java.util.List;
/**
 * AdminrealmsAdminPermissionsClientAuthorizationSettingsAuthorizationSchemaResourceTypes
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-03-11T12:00:50.005853600+07:00[Asia/Bangkok]")

public class AdminrealmsAdminPermissionsClientAuthorizationSettingsAuthorizationSchemaResourceTypes {
  @JsonProperty("type")
  private String type = null;

  @JsonProperty("scopes")
  private List<String> scopes = null;

  public AdminrealmsAdminPermissionsClientAuthorizationSettingsAuthorizationSchemaResourceTypes type(String type) {
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  public String getType() {
    return type;
  }

  public void setType(String type) {
    this.type = type;
  }

  public AdminrealmsAdminPermissionsClientAuthorizationSettingsAuthorizationSchemaResourceTypes scopes(List<String> scopes) {
    this.scopes = scopes;
    return this;
  }

  public AdminrealmsAdminPermissionsClientAuthorizationSettingsAuthorizationSchemaResourceTypes addScopesItem(String scopesItem) {
    if (this.scopes == null) {
      this.scopes = new ArrayList<>();
    }
    this.scopes.add(scopesItem);
    return this;
  }

   /**
   * Get scopes
   * @return scopes
  **/
  public List<String> getScopes() {
    return scopes;
  }

  public void setScopes(List<String> scopes) {
    this.scopes = scopes;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AdminrealmsAdminPermissionsClientAuthorizationSettingsAuthorizationSchemaResourceTypes adminrealmsAdminPermissionsClientAuthorizationSettingsAuthorizationSchemaResourceTypes = (AdminrealmsAdminPermissionsClientAuthorizationSettingsAuthorizationSchemaResourceTypes) o;
    return Objects.equals(this.type, adminrealmsAdminPermissionsClientAuthorizationSettingsAuthorizationSchemaResourceTypes.type) &&
        Objects.equals(this.scopes, adminrealmsAdminPermissionsClientAuthorizationSettingsAuthorizationSchemaResourceTypes.scopes);
  }

  @Override
  public int hashCode() {
    return Objects.hash(type, scopes);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AdminrealmsAdminPermissionsClientAuthorizationSettingsAuthorizationSchemaResourceTypes {\n");
    
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    scopes: ").append(toIndentedString(scopes)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
