/*
 * Keycloak Admin REST API
 * This is a REST API reference for the Keycloak Admin REST API.
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.keycloak.www.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

import java.util.ArrayList;
import java.util.List;
import org.keycloak.www.client.AdminrealmsUserProfileMetadataAttributes;
import org.keycloak.www.client.AdminrealmsUserProfileMetadataGroups;
/**
 * AdminrealmsUserProfileMetadata
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-03-11T12:00:50.005853600+07:00[Asia/Bangkok]")

public class AdminrealmsUserProfileMetadata {
  @JsonProperty("attributes")
  private List<AdminrealmsUserProfileMetadataAttributes> attributes = null;

  @JsonProperty("groups")
  private List<AdminrealmsUserProfileMetadataGroups> groups = null;

  public AdminrealmsUserProfileMetadata attributes(List<AdminrealmsUserProfileMetadataAttributes> attributes) {
    this.attributes = attributes;
    return this;
  }

  public AdminrealmsUserProfileMetadata addAttributesItem(AdminrealmsUserProfileMetadataAttributes attributesItem) {
    if (this.attributes == null) {
      this.attributes = new ArrayList<>();
    }
    this.attributes.add(attributesItem);
    return this;
  }

   /**
   * Get attributes
   * @return attributes
  **/
  public List<AdminrealmsUserProfileMetadataAttributes> getAttributes() {
    return attributes;
  }

  public void setAttributes(List<AdminrealmsUserProfileMetadataAttributes> attributes) {
    this.attributes = attributes;
  }

  public AdminrealmsUserProfileMetadata groups(List<AdminrealmsUserProfileMetadataGroups> groups) {
    this.groups = groups;
    return this;
  }

  public AdminrealmsUserProfileMetadata addGroupsItem(AdminrealmsUserProfileMetadataGroups groupsItem) {
    if (this.groups == null) {
      this.groups = new ArrayList<>();
    }
    this.groups.add(groupsItem);
    return this;
  }

   /**
   * Get groups
   * @return groups
  **/
  public List<AdminrealmsUserProfileMetadataGroups> getGroups() {
    return groups;
  }

  public void setGroups(List<AdminrealmsUserProfileMetadataGroups> groups) {
    this.groups = groups;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AdminrealmsUserProfileMetadata adminrealmsUserProfileMetadata = (AdminrealmsUserProfileMetadata) o;
    return Objects.equals(this.attributes, adminrealmsUserProfileMetadata.attributes) &&
        Objects.equals(this.groups, adminrealmsUserProfileMetadata.groups);
  }

  @Override
  public int hashCode() {
    return Objects.hash(attributes, groups);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AdminrealmsUserProfileMetadata {\n");
    
    sb.append("    attributes: ").append(toIndentedString(attributes)).append("\n");
    sb.append("    groups: ").append(toIndentedString(groups)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
