/*
 * Keycloak Admin REST API
 * This is a REST API reference for the Keycloak Admin REST API.
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.keycloak.www.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

import java.util.ArrayList;
import java.util.List;
import org.keycloak.www.client.AdminrealmsClientPoliciesConditions;
/**
 * AdminrealmsClientPoliciesPolicies
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-03-11T12:00:50.005853600+07:00[Asia/Bangkok]")

public class AdminrealmsClientPoliciesPolicies {
  @JsonProperty("name")
  private String name = null;

  @JsonProperty("description")
  private String description = null;

  @JsonProperty("enabled")
  private Boolean enabled = null;

  @JsonProperty("conditions")
  private List<AdminrealmsClientPoliciesConditions> conditions = null;

  @JsonProperty("profiles")
  private List<String> profiles = null;

  public AdminrealmsClientPoliciesPolicies name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public AdminrealmsClientPoliciesPolicies description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public AdminrealmsClientPoliciesPolicies enabled(Boolean enabled) {
    this.enabled = enabled;
    return this;
  }

   /**
   * Get enabled
   * @return enabled
  **/
  public Boolean isEnabled() {
    return enabled;
  }

  public void setEnabled(Boolean enabled) {
    this.enabled = enabled;
  }

  public AdminrealmsClientPoliciesPolicies conditions(List<AdminrealmsClientPoliciesConditions> conditions) {
    this.conditions = conditions;
    return this;
  }

  public AdminrealmsClientPoliciesPolicies addConditionsItem(AdminrealmsClientPoliciesConditions conditionsItem) {
    if (this.conditions == null) {
      this.conditions = new ArrayList<>();
    }
    this.conditions.add(conditionsItem);
    return this;
  }

   /**
   * Get conditions
   * @return conditions
  **/
  public List<AdminrealmsClientPoliciesConditions> getConditions() {
    return conditions;
  }

  public void setConditions(List<AdminrealmsClientPoliciesConditions> conditions) {
    this.conditions = conditions;
  }

  public AdminrealmsClientPoliciesPolicies profiles(List<String> profiles) {
    this.profiles = profiles;
    return this;
  }

  public AdminrealmsClientPoliciesPolicies addProfilesItem(String profilesItem) {
    if (this.profiles == null) {
      this.profiles = new ArrayList<>();
    }
    this.profiles.add(profilesItem);
    return this;
  }

   /**
   * Get profiles
   * @return profiles
  **/
  public List<String> getProfiles() {
    return profiles;
  }

  public void setProfiles(List<String> profiles) {
    this.profiles = profiles;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AdminrealmsClientPoliciesPolicies adminrealmsClientPoliciesPolicies = (AdminrealmsClientPoliciesPolicies) o;
    return Objects.equals(this.name, adminrealmsClientPoliciesPolicies.name) &&
        Objects.equals(this.description, adminrealmsClientPoliciesPolicies.description) &&
        Objects.equals(this.enabled, adminrealmsClientPoliciesPolicies.enabled) &&
        Objects.equals(this.conditions, adminrealmsClientPoliciesPolicies.conditions) &&
        Objects.equals(this.profiles, adminrealmsClientPoliciesPolicies.profiles);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, description, enabled, conditions, profiles);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AdminrealmsClientPoliciesPolicies {\n");
    
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    enabled: ").append(toIndentedString(enabled)).append("\n");
    sb.append("    conditions: ").append(toIndentedString(conditions)).append("\n");
    sb.append("    profiles: ").append(toIndentedString(profiles)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
