/*
 * Keycloak Admin REST API
 * This is a REST API reference for the Keycloak Admin REST API.
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.keycloak.www.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.keycloak.www.client.AdminrealmsrealmadmineventsAuthDetails;
/**
 * AdminEventRepresentation
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-03-11T12:00:50.005853600+07:00[Asia/Bangkok]")

public class AdminEventRepresentation {
  @JsonProperty("time")
  private Long time = null;

  @JsonProperty("realmId")
  private String realmId = null;

  @JsonProperty("authDetails")
  private AdminrealmsrealmadmineventsAuthDetails authDetails = null;

  @JsonProperty("operationType")
  private String operationType = null;

  @JsonProperty("resourceType")
  private String resourceType = null;

  @JsonProperty("resourcePath")
  private String resourcePath = null;

  @JsonProperty("representation")
  private String representation = null;

  @JsonProperty("error")
  private String error = null;

  @JsonProperty("details")
  private Map<String, String> details = null;

  public AdminEventRepresentation time(Long time) {
    this.time = time;
    return this;
  }

   /**
   * Get time
   * @return time
  **/
  public Long getTime() {
    return time;
  }

  public void setTime(Long time) {
    this.time = time;
  }

  public AdminEventRepresentation realmId(String realmId) {
    this.realmId = realmId;
    return this;
  }

   /**
   * Get realmId
   * @return realmId
  **/
  public String getRealmId() {
    return realmId;
  }

  public void setRealmId(String realmId) {
    this.realmId = realmId;
  }

  public AdminEventRepresentation authDetails(AdminrealmsrealmadmineventsAuthDetails authDetails) {
    this.authDetails = authDetails;
    return this;
  }

   /**
   * Get authDetails
   * @return authDetails
  **/
  public AdminrealmsrealmadmineventsAuthDetails getAuthDetails() {
    return authDetails;
  }

  public void setAuthDetails(AdminrealmsrealmadmineventsAuthDetails authDetails) {
    this.authDetails = authDetails;
  }

  public AdminEventRepresentation operationType(String operationType) {
    this.operationType = operationType;
    return this;
  }

   /**
   * Get operationType
   * @return operationType
  **/
  public String getOperationType() {
    return operationType;
  }

  public void setOperationType(String operationType) {
    this.operationType = operationType;
  }

  public AdminEventRepresentation resourceType(String resourceType) {
    this.resourceType = resourceType;
    return this;
  }

   /**
   * Get resourceType
   * @return resourceType
  **/
  public String getResourceType() {
    return resourceType;
  }

  public void setResourceType(String resourceType) {
    this.resourceType = resourceType;
  }

  public AdminEventRepresentation resourcePath(String resourcePath) {
    this.resourcePath = resourcePath;
    return this;
  }

   /**
   * Get resourcePath
   * @return resourcePath
  **/
  public String getResourcePath() {
    return resourcePath;
  }

  public void setResourcePath(String resourcePath) {
    this.resourcePath = resourcePath;
  }

  public AdminEventRepresentation representation(String representation) {
    this.representation = representation;
    return this;
  }

   /**
   * Get representation
   * @return representation
  **/
  public String getRepresentation() {
    return representation;
  }

  public void setRepresentation(String representation) {
    this.representation = representation;
  }

  public AdminEventRepresentation error(String error) {
    this.error = error;
    return this;
  }

   /**
   * Get error
   * @return error
  **/
  public String getError() {
    return error;
  }

  public void setError(String error) {
    this.error = error;
  }

  public AdminEventRepresentation details(Map<String, String> details) {
    this.details = details;
    return this;
  }

  public AdminEventRepresentation putDetailsItem(String key, String detailsItem) {
    if (this.details == null) {
      this.details = new HashMap<>();
    }
    this.details.put(key, detailsItem);
    return this;
  }

   /**
   * Get details
   * @return details
  **/
  public Map<String, String> getDetails() {
    return details;
  }

  public void setDetails(Map<String, String> details) {
    this.details = details;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AdminEventRepresentation adminEventRepresentation = (AdminEventRepresentation) o;
    return Objects.equals(this.time, adminEventRepresentation.time) &&
        Objects.equals(this.realmId, adminEventRepresentation.realmId) &&
        Objects.equals(this.authDetails, adminEventRepresentation.authDetails) &&
        Objects.equals(this.operationType, adminEventRepresentation.operationType) &&
        Objects.equals(this.resourceType, adminEventRepresentation.resourceType) &&
        Objects.equals(this.resourcePath, adminEventRepresentation.resourcePath) &&
        Objects.equals(this.representation, adminEventRepresentation.representation) &&
        Objects.equals(this.error, adminEventRepresentation.error) &&
        Objects.equals(this.details, adminEventRepresentation.details);
  }

  @Override
  public int hashCode() {
    return Objects.hash(time, realmId, authDetails, operationType, resourceType, resourcePath, representation, error, details);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AdminEventRepresentation {\n");
    
    sb.append("    time: ").append(toIndentedString(time)).append("\n");
    sb.append("    realmId: ").append(toIndentedString(realmId)).append("\n");
    sb.append("    authDetails: ").append(toIndentedString(authDetails)).append("\n");
    sb.append("    operationType: ").append(toIndentedString(operationType)).append("\n");
    sb.append("    resourceType: ").append(toIndentedString(resourceType)).append("\n");
    sb.append("    resourcePath: ").append(toIndentedString(resourcePath)).append("\n");
    sb.append("    representation: ").append(toIndentedString(representation)).append("\n");
    sb.append("    error: ").append(toIndentedString(error)).append("\n");
    sb.append("    details: ").append(toIndentedString(details)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
