/*
 * Keycloak Admin REST API
 * This is a REST API reference for the Keycloak Admin REST API.
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.keycloak.www.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.keycloak.www.client.AdminrealmsrealmclienttypesConfig;
/**
 * AdminrealmsrealmclienttypesClienttypes
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-03-11T12:00:50.005853600+07:00[Asia/Bangkok]")

public class AdminrealmsrealmclienttypesClienttypes {
  @JsonProperty("name")
  private String name = null;

  @JsonProperty("provider")
  private String provider = null;

  @JsonProperty("parent")
  private String parent = null;

  @JsonProperty("config")
  private Map<String, AdminrealmsrealmclienttypesConfig> config = null;

  public AdminrealmsrealmclienttypesClienttypes name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public AdminrealmsrealmclienttypesClienttypes provider(String provider) {
    this.provider = provider;
    return this;
  }

   /**
   * Get provider
   * @return provider
  **/
  public String getProvider() {
    return provider;
  }

  public void setProvider(String provider) {
    this.provider = provider;
  }

  public AdminrealmsrealmclienttypesClienttypes parent(String parent) {
    this.parent = parent;
    return this;
  }

   /**
   * Get parent
   * @return parent
  **/
  public String getParent() {
    return parent;
  }

  public void setParent(String parent) {
    this.parent = parent;
  }

  public AdminrealmsrealmclienttypesClienttypes config(Map<String, AdminrealmsrealmclienttypesConfig> config) {
    this.config = config;
    return this;
  }

  public AdminrealmsrealmclienttypesClienttypes putConfigItem(String key, AdminrealmsrealmclienttypesConfig configItem) {
    if (this.config == null) {
      this.config = new HashMap<>();
    }
    this.config.put(key, configItem);
    return this;
  }

   /**
   * Get config
   * @return config
  **/
  public Map<String, AdminrealmsrealmclienttypesConfig> getConfig() {
    return config;
  }

  public void setConfig(Map<String, AdminrealmsrealmclienttypesConfig> config) {
    this.config = config;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AdminrealmsrealmclienttypesClienttypes adminrealmsrealmclienttypesClienttypes = (AdminrealmsrealmclienttypesClienttypes) o;
    return Objects.equals(this.name, adminrealmsrealmclienttypesClienttypes.name) &&
        Objects.equals(this.provider, adminrealmsrealmclienttypesClienttypes.provider) &&
        Objects.equals(this.parent, adminrealmsrealmclienttypesClienttypes.parent) &&
        Objects.equals(this.config, adminrealmsrealmclienttypesClienttypes.config);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, provider, parent, config);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AdminrealmsrealmclienttypesClienttypes {\n");
    
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    provider: ").append(toIndentedString(provider)).append("\n");
    sb.append("    parent: ").append(toIndentedString(parent)).append("\n");
    sb.append("    config: ").append(toIndentedString(config)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
