/*
 * Keycloak Admin REST API
 * This is a REST API reference for the Keycloak Admin REST API.
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.keycloak.www.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * AuthenticationExecutionExportRepresentation
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-03-11T12:00:50.005853600+07:00[Asia/Bangkok]")

public class AuthenticationExecutionExportRepresentation {
  @JsonProperty("authenticatorConfig")
  private String authenticatorConfig = null;

  @JsonProperty("authenticator")
  private String authenticator = null;

  @JsonProperty("authenticatorFlow")
  private Boolean authenticatorFlow = null;

  @JsonProperty("requirement")
  private String requirement = null;

  @JsonProperty("priority")
  private Integer priority = null;

  @JsonProperty("autheticatorFlow")
  private Boolean autheticatorFlow = null;

  @JsonProperty("flowAlias")
  private String flowAlias = null;

  @JsonProperty("userSetupAllowed")
  private Boolean userSetupAllowed = null;

  public AuthenticationExecutionExportRepresentation authenticatorConfig(String authenticatorConfig) {
    this.authenticatorConfig = authenticatorConfig;
    return this;
  }

   /**
   * Get authenticatorConfig
   * @return authenticatorConfig
  **/
  public String getAuthenticatorConfig() {
    return authenticatorConfig;
  }

  public void setAuthenticatorConfig(String authenticatorConfig) {
    this.authenticatorConfig = authenticatorConfig;
  }

  public AuthenticationExecutionExportRepresentation authenticator(String authenticator) {
    this.authenticator = authenticator;
    return this;
  }

   /**
   * Get authenticator
   * @return authenticator
  **/
  public String getAuthenticator() {
    return authenticator;
  }

  public void setAuthenticator(String authenticator) {
    this.authenticator = authenticator;
  }

  public AuthenticationExecutionExportRepresentation authenticatorFlow(Boolean authenticatorFlow) {
    this.authenticatorFlow = authenticatorFlow;
    return this;
  }

   /**
   * Get authenticatorFlow
   * @return authenticatorFlow
  **/
  public Boolean isAuthenticatorFlow() {
    return authenticatorFlow;
  }

  public void setAuthenticatorFlow(Boolean authenticatorFlow) {
    this.authenticatorFlow = authenticatorFlow;
  }

  public AuthenticationExecutionExportRepresentation requirement(String requirement) {
    this.requirement = requirement;
    return this;
  }

   /**
   * Get requirement
   * @return requirement
  **/
  public String getRequirement() {
    return requirement;
  }

  public void setRequirement(String requirement) {
    this.requirement = requirement;
  }

  public AuthenticationExecutionExportRepresentation priority(Integer priority) {
    this.priority = priority;
    return this;
  }

   /**
   * Get priority
   * @return priority
  **/
  public Integer getPriority() {
    return priority;
  }

  public void setPriority(Integer priority) {
    this.priority = priority;
  }

  public AuthenticationExecutionExportRepresentation autheticatorFlow(Boolean autheticatorFlow) {
    this.autheticatorFlow = autheticatorFlow;
    return this;
  }

   /**
   * Get autheticatorFlow
   * @return autheticatorFlow
  **/
  public Boolean isAutheticatorFlow() {
    return autheticatorFlow;
  }

  public void setAutheticatorFlow(Boolean autheticatorFlow) {
    this.autheticatorFlow = autheticatorFlow;
  }

  public AuthenticationExecutionExportRepresentation flowAlias(String flowAlias) {
    this.flowAlias = flowAlias;
    return this;
  }

   /**
   * Get flowAlias
   * @return flowAlias
  **/
  public String getFlowAlias() {
    return flowAlias;
  }

  public void setFlowAlias(String flowAlias) {
    this.flowAlias = flowAlias;
  }

  public AuthenticationExecutionExportRepresentation userSetupAllowed(Boolean userSetupAllowed) {
    this.userSetupAllowed = userSetupAllowed;
    return this;
  }

   /**
   * Get userSetupAllowed
   * @return userSetupAllowed
  **/
  public Boolean isUserSetupAllowed() {
    return userSetupAllowed;
  }

  public void setUserSetupAllowed(Boolean userSetupAllowed) {
    this.userSetupAllowed = userSetupAllowed;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AuthenticationExecutionExportRepresentation authenticationExecutionExportRepresentation = (AuthenticationExecutionExportRepresentation) o;
    return Objects.equals(this.authenticatorConfig, authenticationExecutionExportRepresentation.authenticatorConfig) &&
        Objects.equals(this.authenticator, authenticationExecutionExportRepresentation.authenticator) &&
        Objects.equals(this.authenticatorFlow, authenticationExecutionExportRepresentation.authenticatorFlow) &&
        Objects.equals(this.requirement, authenticationExecutionExportRepresentation.requirement) &&
        Objects.equals(this.priority, authenticationExecutionExportRepresentation.priority) &&
        Objects.equals(this.autheticatorFlow, authenticationExecutionExportRepresentation.autheticatorFlow) &&
        Objects.equals(this.flowAlias, authenticationExecutionExportRepresentation.flowAlias) &&
        Objects.equals(this.userSetupAllowed, authenticationExecutionExportRepresentation.userSetupAllowed);
  }

  @Override
  public int hashCode() {
    return Objects.hash(authenticatorConfig, authenticator, authenticatorFlow, requirement, priority, autheticatorFlow, flowAlias, userSetupAllowed);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AuthenticationExecutionExportRepresentation {\n");
    
    sb.append("    authenticatorConfig: ").append(toIndentedString(authenticatorConfig)).append("\n");
    sb.append("    authenticator: ").append(toIndentedString(authenticator)).append("\n");
    sb.append("    authenticatorFlow: ").append(toIndentedString(authenticatorFlow)).append("\n");
    sb.append("    requirement: ").append(toIndentedString(requirement)).append("\n");
    sb.append("    priority: ").append(toIndentedString(priority)).append("\n");
    sb.append("    autheticatorFlow: ").append(toIndentedString(autheticatorFlow)).append("\n");
    sb.append("    flowAlias: ").append(toIndentedString(flowAlias)).append("\n");
    sb.append("    userSetupAllowed: ").append(toIndentedString(userSetupAllowed)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
