/*
 * Keycloak Admin REST API
 * This is a REST API reference for the Keycloak Admin REST API.
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.keycloak.www.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

import java.util.List;
/**
 * ClientPolicyExecutorRepresentation
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-03-11T12:00:50.005853600+07:00[Asia/Bangkok]")

public class ClientPolicyExecutorRepresentation {
  @JsonProperty("executor")
  private String executor = null;

  @JsonProperty("configuration")
  private List _configuration = null;

  public ClientPolicyExecutorRepresentation executor(String executor) {
    this.executor = executor;
    return this;
  }

   /**
   * Get executor
   * @return executor
  **/
  public String getExecutor() {
    return executor;
  }

  public void setExecutor(String executor) {
    this.executor = executor;
  }

  public ClientPolicyExecutorRepresentation _configuration(List _configuration) {
    this._configuration = _configuration;
    return this;
  }

   /**
   * Get _configuration
   * @return _configuration
  **/
  public List getConfiguration() {
    return _configuration;
  }

  public void setConfiguration(List _configuration) {
    this._configuration = _configuration;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ClientPolicyExecutorRepresentation clientPolicyExecutorRepresentation = (ClientPolicyExecutorRepresentation) o;
    return Objects.equals(this.executor, clientPolicyExecutorRepresentation.executor) &&
        Objects.equals(this._configuration, clientPolicyExecutorRepresentation._configuration);
  }

  @Override
  public int hashCode() {
    return Objects.hash(executor, _configuration);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ClientPolicyExecutorRepresentation {\n");
    
    sb.append("    executor: ").append(toIndentedString(executor)).append("\n");
    sb.append("    _configuration: ").append(toIndentedString(_configuration)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
