/*
 * Keycloak Admin REST API
 * This is a REST API reference for the Keycloak Admin REST API.
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.keycloak.www.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.keycloak.www.client.AdminrealmsAdminPermissionsClientProtocolMappers;
/**
 * ClientscopesClientscopeidBody
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-03-11T12:00:50.005853600+07:00[Asia/Bangkok]")

public class ClientscopesClientscopeidBody {
  @JsonProperty("id")
  private String id = null;

  @JsonProperty("name")
  private String name = null;

  @JsonProperty("description")
  private String description = null;

  @JsonProperty("protocol")
  private String protocol = null;

  @JsonProperty("attributes")
  private Map<String, String> attributes = null;

  @JsonProperty("protocolMappers")
  private List<AdminrealmsAdminPermissionsClientProtocolMappers> protocolMappers = null;

  public ClientscopesClientscopeidBody id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public ClientscopesClientscopeidBody name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public ClientscopesClientscopeidBody description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public ClientscopesClientscopeidBody protocol(String protocol) {
    this.protocol = protocol;
    return this;
  }

   /**
   * Get protocol
   * @return protocol
  **/
  public String getProtocol() {
    return protocol;
  }

  public void setProtocol(String protocol) {
    this.protocol = protocol;
  }

  public ClientscopesClientscopeidBody attributes(Map<String, String> attributes) {
    this.attributes = attributes;
    return this;
  }

  public ClientscopesClientscopeidBody putAttributesItem(String key, String attributesItem) {
    if (this.attributes == null) {
      this.attributes = new HashMap<>();
    }
    this.attributes.put(key, attributesItem);
    return this;
  }

   /**
   * Get attributes
   * @return attributes
  **/
  public Map<String, String> getAttributes() {
    return attributes;
  }

  public void setAttributes(Map<String, String> attributes) {
    this.attributes = attributes;
  }

  public ClientscopesClientscopeidBody protocolMappers(List<AdminrealmsAdminPermissionsClientProtocolMappers> protocolMappers) {
    this.protocolMappers = protocolMappers;
    return this;
  }

  public ClientscopesClientscopeidBody addProtocolMappersItem(AdminrealmsAdminPermissionsClientProtocolMappers protocolMappersItem) {
    if (this.protocolMappers == null) {
      this.protocolMappers = new ArrayList<>();
    }
    this.protocolMappers.add(protocolMappersItem);
    return this;
  }

   /**
   * Get protocolMappers
   * @return protocolMappers
  **/
  public List<AdminrealmsAdminPermissionsClientProtocolMappers> getProtocolMappers() {
    return protocolMappers;
  }

  public void setProtocolMappers(List<AdminrealmsAdminPermissionsClientProtocolMappers> protocolMappers) {
    this.protocolMappers = protocolMappers;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ClientscopesClientscopeidBody clientscopesClientscopeidBody = (ClientscopesClientscopeidBody) o;
    return Objects.equals(this.id, clientscopesClientscopeidBody.id) &&
        Objects.equals(this.name, clientscopesClientscopeidBody.name) &&
        Objects.equals(this.description, clientscopesClientscopeidBody.description) &&
        Objects.equals(this.protocol, clientscopesClientscopeidBody.protocol) &&
        Objects.equals(this.attributes, clientscopesClientscopeidBody.attributes) &&
        Objects.equals(this.protocolMappers, clientscopesClientscopeidBody.protocolMappers);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, description, protocol, attributes, protocolMappers);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ClientscopesClientscopeidBody {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    protocol: ").append(toIndentedString(protocol)).append("\n");
    sb.append("    attributes: ").append(toIndentedString(attributes)).append("\n");
    sb.append("    protocolMappers: ").append(toIndentedString(protocolMappers)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
