/*
 * Keycloak Admin REST API
 * This is a REST API reference for the Keycloak Admin REST API.
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.keycloak.www.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Gets or Sets DecisionEffect
 */
public enum DecisionEffect {
  PERMIT("PERMIT"),
  DENY("DENY");

  private String value;

  DecisionEffect(String value) {
    this.value = value;
  }

  @JsonValue
  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  @JsonCreator
  public static DecisionEffect fromValue(String input) {
    for (DecisionEffect b : DecisionEffect.values()) {
      if (b.value.equals(input)) {
        return b;
      }
    }
    return null;
  }
}
