/*
 * Keycloak Admin REST API
 * This is a REST API reference for the Keycloak Admin REST API.
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.keycloak.www.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

import java.util.ArrayList;
import java.util.List;
import org.keycloak.www.client.EvaluationResultRepresentationPolicies;
import org.keycloak.www.client.ResourceResourceidBody;
import org.keycloak.www.client.ScopeScopeidBody;
/**
 * EvaluationResultRepresentation
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-03-11T12:00:50.005853600+07:00[Asia/Bangkok]")

public class EvaluationResultRepresentation {
  @JsonProperty("resource")
  private ResourceResourceidBody resource = null;

  @JsonProperty("scopes")
  private List<ScopeScopeidBody> scopes = null;

  @JsonProperty("policies")
  private List<EvaluationResultRepresentationPolicies> policies = null;

  /**
   * Gets or Sets status
   */
  public enum StatusEnum {
    PERMIT("PERMIT"),
    DENY("DENY");

    private String value;

    StatusEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static StatusEnum fromValue(String input) {
      for (StatusEnum b : StatusEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("status")
  private StatusEnum status = null;

  @JsonProperty("allowedScopes")
  private List<ScopeScopeidBody> allowedScopes = null;

  public EvaluationResultRepresentation resource(ResourceResourceidBody resource) {
    this.resource = resource;
    return this;
  }

   /**
   * Get resource
   * @return resource
  **/
  public ResourceResourceidBody getResource() {
    return resource;
  }

  public void setResource(ResourceResourceidBody resource) {
    this.resource = resource;
  }

  public EvaluationResultRepresentation scopes(List<ScopeScopeidBody> scopes) {
    this.scopes = scopes;
    return this;
  }

  public EvaluationResultRepresentation addScopesItem(ScopeScopeidBody scopesItem) {
    if (this.scopes == null) {
      this.scopes = new ArrayList<>();
    }
    this.scopes.add(scopesItem);
    return this;
  }

   /**
   * Get scopes
   * @return scopes
  **/
  public List<ScopeScopeidBody> getScopes() {
    return scopes;
  }

  public void setScopes(List<ScopeScopeidBody> scopes) {
    this.scopes = scopes;
  }

  public EvaluationResultRepresentation policies(List<EvaluationResultRepresentationPolicies> policies) {
    this.policies = policies;
    return this;
  }

  public EvaluationResultRepresentation addPoliciesItem(EvaluationResultRepresentationPolicies policiesItem) {
    if (this.policies == null) {
      this.policies = new ArrayList<>();
    }
    this.policies.add(policiesItem);
    return this;
  }

   /**
   * Get policies
   * @return policies
  **/
  public List<EvaluationResultRepresentationPolicies> getPolicies() {
    return policies;
  }

  public void setPolicies(List<EvaluationResultRepresentationPolicies> policies) {
    this.policies = policies;
  }

  public EvaluationResultRepresentation status(StatusEnum status) {
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  public StatusEnum getStatus() {
    return status;
  }

  public void setStatus(StatusEnum status) {
    this.status = status;
  }

  public EvaluationResultRepresentation allowedScopes(List<ScopeScopeidBody> allowedScopes) {
    this.allowedScopes = allowedScopes;
    return this;
  }

  public EvaluationResultRepresentation addAllowedScopesItem(ScopeScopeidBody allowedScopesItem) {
    if (this.allowedScopes == null) {
      this.allowedScopes = new ArrayList<>();
    }
    this.allowedScopes.add(allowedScopesItem);
    return this;
  }

   /**
   * Get allowedScopes
   * @return allowedScopes
  **/
  public List<ScopeScopeidBody> getAllowedScopes() {
    return allowedScopes;
  }

  public void setAllowedScopes(List<ScopeScopeidBody> allowedScopes) {
    this.allowedScopes = allowedScopes;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EvaluationResultRepresentation evaluationResultRepresentation = (EvaluationResultRepresentation) o;
    return Objects.equals(this.resource, evaluationResultRepresentation.resource) &&
        Objects.equals(this.scopes, evaluationResultRepresentation.scopes) &&
        Objects.equals(this.policies, evaluationResultRepresentation.policies) &&
        Objects.equals(this.status, evaluationResultRepresentation.status) &&
        Objects.equals(this.allowedScopes, evaluationResultRepresentation.allowedScopes);
  }

  @Override
  public int hashCode() {
    return Objects.hash(resource, scopes, policies, status, allowedScopes);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EvaluationResultRepresentation {\n");
    
    sb.append("    resource: ").append(toIndentedString(resource)).append("\n");
    sb.append("    scopes: ").append(toIndentedString(scopes)).append("\n");
    sb.append("    policies: ").append(toIndentedString(policies)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    allowedScopes: ").append(toIndentedString(allowedScopes)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
