/*
 * Keycloak Admin REST API
 * This is a REST API reference for the Keycloak Admin REST API.
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.keycloak.www.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

import java.util.ArrayList;
import java.util.List;
/**
 * EventsConfigBody
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-03-11T12:00:50.005853600+07:00[Asia/Bangkok]")

public class EventsConfigBody {
  @JsonProperty("eventsEnabled")
  private Boolean eventsEnabled = null;

  @JsonProperty("eventsExpiration")
  private Long eventsExpiration = null;

  @JsonProperty("eventsListeners")
  private List<String> eventsListeners = null;

  @JsonProperty("enabledEventTypes")
  private List<String> enabledEventTypes = null;

  @JsonProperty("adminEventsEnabled")
  private Boolean adminEventsEnabled = null;

  @JsonProperty("adminEventsDetailsEnabled")
  private Boolean adminEventsDetailsEnabled = null;

  public EventsConfigBody eventsEnabled(Boolean eventsEnabled) {
    this.eventsEnabled = eventsEnabled;
    return this;
  }

   /**
   * Get eventsEnabled
   * @return eventsEnabled
  **/
  public Boolean isEventsEnabled() {
    return eventsEnabled;
  }

  public void setEventsEnabled(Boolean eventsEnabled) {
    this.eventsEnabled = eventsEnabled;
  }

  public EventsConfigBody eventsExpiration(Long eventsExpiration) {
    this.eventsExpiration = eventsExpiration;
    return this;
  }

   /**
   * Get eventsExpiration
   * @return eventsExpiration
  **/
  public Long getEventsExpiration() {
    return eventsExpiration;
  }

  public void setEventsExpiration(Long eventsExpiration) {
    this.eventsExpiration = eventsExpiration;
  }

  public EventsConfigBody eventsListeners(List<String> eventsListeners) {
    this.eventsListeners = eventsListeners;
    return this;
  }

  public EventsConfigBody addEventsListenersItem(String eventsListenersItem) {
    if (this.eventsListeners == null) {
      this.eventsListeners = new ArrayList<>();
    }
    this.eventsListeners.add(eventsListenersItem);
    return this;
  }

   /**
   * Get eventsListeners
   * @return eventsListeners
  **/
  public List<String> getEventsListeners() {
    return eventsListeners;
  }

  public void setEventsListeners(List<String> eventsListeners) {
    this.eventsListeners = eventsListeners;
  }

  public EventsConfigBody enabledEventTypes(List<String> enabledEventTypes) {
    this.enabledEventTypes = enabledEventTypes;
    return this;
  }

  public EventsConfigBody addEnabledEventTypesItem(String enabledEventTypesItem) {
    if (this.enabledEventTypes == null) {
      this.enabledEventTypes = new ArrayList<>();
    }
    this.enabledEventTypes.add(enabledEventTypesItem);
    return this;
  }

   /**
   * Get enabledEventTypes
   * @return enabledEventTypes
  **/
  public List<String> getEnabledEventTypes() {
    return enabledEventTypes;
  }

  public void setEnabledEventTypes(List<String> enabledEventTypes) {
    this.enabledEventTypes = enabledEventTypes;
  }

  public EventsConfigBody adminEventsEnabled(Boolean adminEventsEnabled) {
    this.adminEventsEnabled = adminEventsEnabled;
    return this;
  }

   /**
   * Get adminEventsEnabled
   * @return adminEventsEnabled
  **/
  public Boolean isAdminEventsEnabled() {
    return adminEventsEnabled;
  }

  public void setAdminEventsEnabled(Boolean adminEventsEnabled) {
    this.adminEventsEnabled = adminEventsEnabled;
  }

  public EventsConfigBody adminEventsDetailsEnabled(Boolean adminEventsDetailsEnabled) {
    this.adminEventsDetailsEnabled = adminEventsDetailsEnabled;
    return this;
  }

   /**
   * Get adminEventsDetailsEnabled
   * @return adminEventsDetailsEnabled
  **/
  public Boolean isAdminEventsDetailsEnabled() {
    return adminEventsDetailsEnabled;
  }

  public void setAdminEventsDetailsEnabled(Boolean adminEventsDetailsEnabled) {
    this.adminEventsDetailsEnabled = adminEventsDetailsEnabled;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EventsConfigBody eventsConfigBody = (EventsConfigBody) o;
    return Objects.equals(this.eventsEnabled, eventsConfigBody.eventsEnabled) &&
        Objects.equals(this.eventsExpiration, eventsConfigBody.eventsExpiration) &&
        Objects.equals(this.eventsListeners, eventsConfigBody.eventsListeners) &&
        Objects.equals(this.enabledEventTypes, eventsConfigBody.enabledEventTypes) &&
        Objects.equals(this.adminEventsEnabled, eventsConfigBody.adminEventsEnabled) &&
        Objects.equals(this.adminEventsDetailsEnabled, eventsConfigBody.adminEventsDetailsEnabled);
  }

  @Override
  public int hashCode() {
    return Objects.hash(eventsEnabled, eventsExpiration, eventsListeners, enabledEventTypes, adminEventsEnabled, adminEventsDetailsEnabled);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EventsConfigBody {\n");
    
    sb.append("    eventsEnabled: ").append(toIndentedString(eventsEnabled)).append("\n");
    sb.append("    eventsExpiration: ").append(toIndentedString(eventsExpiration)).append("\n");
    sb.append("    eventsListeners: ").append(toIndentedString(eventsListeners)).append("\n");
    sb.append("    enabledEventTypes: ").append(toIndentedString(enabledEventTypes)).append("\n");
    sb.append("    adminEventsEnabled: ").append(toIndentedString(adminEventsEnabled)).append("\n");
    sb.append("    adminEventsDetailsEnabled: ").append(toIndentedString(adminEventsDetailsEnabled)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
