/*
 * Keycloak Admin REST API
 * This is a REST API reference for the Keycloak Admin REST API.
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.keycloak.www.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.keycloak.www.client.AccessTokenAddress;
/**
 * IDToken
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-03-11T12:00:50.005853600+07:00[Asia/Bangkok]")

public class IDToken {
  @JsonProperty("jti")
  private String jti = null;

  @JsonProperty("exp")
  private Long exp = null;

  @JsonProperty("nbf")
  private Long nbf = null;

  @JsonProperty("iat")
  private Long iat = null;

  @JsonProperty("iss")
  private String iss = null;

  @JsonProperty("sub")
  private String sub = null;

  @JsonProperty("typ")
  private String typ = null;

  @JsonProperty("azp")
  private String azp = null;

  @JsonProperty("otherClaims")
  private Map<String, Object> otherClaims = null;

  @JsonProperty("nonce")
  private String nonce = null;

  @JsonProperty("auth_time")
  private Long authTime = null;

  @JsonProperty("sid")
  private String sid = null;

  @JsonProperty("at_hash")
  private String atHash = null;

  @JsonProperty("c_hash")
  private String cHash = null;

  @JsonProperty("name")
  private String name = null;

  @JsonProperty("given_name")
  private String givenName = null;

  @JsonProperty("family_name")
  private String familyName = null;

  @JsonProperty("middle_name")
  private String middleName = null;

  @JsonProperty("nickname")
  private String nickname = null;

  @JsonProperty("preferred_username")
  private String preferredUsername = null;

  @JsonProperty("profile")
  private String profile = null;

  @JsonProperty("picture")
  private String picture = null;

  @JsonProperty("website")
  private String website = null;

  @JsonProperty("email")
  private String email = null;

  @JsonProperty("email_verified")
  private Boolean emailVerified = null;

  @JsonProperty("gender")
  private String gender = null;

  @JsonProperty("birthdate")
  private String birthdate = null;

  @JsonProperty("zoneinfo")
  private String zoneinfo = null;

  @JsonProperty("locale")
  private String locale = null;

  @JsonProperty("phone_number")
  private String phoneNumber = null;

  @JsonProperty("phone_number_verified")
  private Boolean phoneNumberVerified = null;

  @JsonProperty("address")
  private AccessTokenAddress address = null;

  @JsonProperty("updated_at")
  private Long updatedAt = null;

  @JsonProperty("claims_locales")
  private String claimsLocales = null;

  @JsonProperty("acr")
  private String acr = null;

  @JsonProperty("s_hash")
  private String sHash = null;

  public IDToken jti(String jti) {
    this.jti = jti;
    return this;
  }

   /**
   * Get jti
   * @return jti
  **/
  public String getJti() {
    return jti;
  }

  public void setJti(String jti) {
    this.jti = jti;
  }

  public IDToken exp(Long exp) {
    this.exp = exp;
    return this;
  }

   /**
   * Get exp
   * @return exp
  **/
  public Long getExp() {
    return exp;
  }

  public void setExp(Long exp) {
    this.exp = exp;
  }

  public IDToken nbf(Long nbf) {
    this.nbf = nbf;
    return this;
  }

   /**
   * Get nbf
   * @return nbf
  **/
  public Long getNbf() {
    return nbf;
  }

  public void setNbf(Long nbf) {
    this.nbf = nbf;
  }

  public IDToken iat(Long iat) {
    this.iat = iat;
    return this;
  }

   /**
   * Get iat
   * @return iat
  **/
  public Long getIat() {
    return iat;
  }

  public void setIat(Long iat) {
    this.iat = iat;
  }

  public IDToken iss(String iss) {
    this.iss = iss;
    return this;
  }

   /**
   * Get iss
   * @return iss
  **/
  public String getIss() {
    return iss;
  }

  public void setIss(String iss) {
    this.iss = iss;
  }

  public IDToken sub(String sub) {
    this.sub = sub;
    return this;
  }

   /**
   * Get sub
   * @return sub
  **/
  public String getSub() {
    return sub;
  }

  public void setSub(String sub) {
    this.sub = sub;
  }

  public IDToken typ(String typ) {
    this.typ = typ;
    return this;
  }

   /**
   * Get typ
   * @return typ
  **/
  public String getTyp() {
    return typ;
  }

  public void setTyp(String typ) {
    this.typ = typ;
  }

  public IDToken azp(String azp) {
    this.azp = azp;
    return this;
  }

   /**
   * Get azp
   * @return azp
  **/
  public String getAzp() {
    return azp;
  }

  public void setAzp(String azp) {
    this.azp = azp;
  }

  public IDToken otherClaims(Map<String, Object> otherClaims) {
    this.otherClaims = otherClaims;
    return this;
  }

  public IDToken putOtherClaimsItem(String key, Object otherClaimsItem) {
    if (this.otherClaims == null) {
      this.otherClaims = new HashMap<>();
    }
    this.otherClaims.put(key, otherClaimsItem);
    return this;
  }

   /**
   * Get otherClaims
   * @return otherClaims
  **/
  public Map<String, Object> getOtherClaims() {
    return otherClaims;
  }

  public void setOtherClaims(Map<String, Object> otherClaims) {
    this.otherClaims = otherClaims;
  }

  public IDToken nonce(String nonce) {
    this.nonce = nonce;
    return this;
  }

   /**
   * Get nonce
   * @return nonce
  **/
  public String getNonce() {
    return nonce;
  }

  public void setNonce(String nonce) {
    this.nonce = nonce;
  }

  public IDToken authTime(Long authTime) {
    this.authTime = authTime;
    return this;
  }

   /**
   * Get authTime
   * @return authTime
  **/
  public Long getAuthTime() {
    return authTime;
  }

  public void setAuthTime(Long authTime) {
    this.authTime = authTime;
  }

  public IDToken sid(String sid) {
    this.sid = sid;
    return this;
  }

   /**
   * Get sid
   * @return sid
  **/
  public String getSid() {
    return sid;
  }

  public void setSid(String sid) {
    this.sid = sid;
  }

  public IDToken atHash(String atHash) {
    this.atHash = atHash;
    return this;
  }

   /**
   * Get atHash
   * @return atHash
  **/
  public String getAtHash() {
    return atHash;
  }

  public void setAtHash(String atHash) {
    this.atHash = atHash;
  }

  public IDToken cHash(String cHash) {
    this.cHash = cHash;
    return this;
  }

   /**
   * Get cHash
   * @return cHash
  **/
  public String getCHash() {
    return cHash;
  }

  public void setCHash(String cHash) {
    this.cHash = cHash;
  }

  public IDToken name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public IDToken givenName(String givenName) {
    this.givenName = givenName;
    return this;
  }

   /**
   * Get givenName
   * @return givenName
  **/
  public String getGivenName() {
    return givenName;
  }

  public void setGivenName(String givenName) {
    this.givenName = givenName;
  }

  public IDToken familyName(String familyName) {
    this.familyName = familyName;
    return this;
  }

   /**
   * Get familyName
   * @return familyName
  **/
  public String getFamilyName() {
    return familyName;
  }

  public void setFamilyName(String familyName) {
    this.familyName = familyName;
  }

  public IDToken middleName(String middleName) {
    this.middleName = middleName;
    return this;
  }

   /**
   * Get middleName
   * @return middleName
  **/
  public String getMiddleName() {
    return middleName;
  }

  public void setMiddleName(String middleName) {
    this.middleName = middleName;
  }

  public IDToken nickname(String nickname) {
    this.nickname = nickname;
    return this;
  }

   /**
   * Get nickname
   * @return nickname
  **/
  public String getNickname() {
    return nickname;
  }

  public void setNickname(String nickname) {
    this.nickname = nickname;
  }

  public IDToken preferredUsername(String preferredUsername) {
    this.preferredUsername = preferredUsername;
    return this;
  }

   /**
   * Get preferredUsername
   * @return preferredUsername
  **/
  public String getPreferredUsername() {
    return preferredUsername;
  }

  public void setPreferredUsername(String preferredUsername) {
    this.preferredUsername = preferredUsername;
  }

  public IDToken profile(String profile) {
    this.profile = profile;
    return this;
  }

   /**
   * Get profile
   * @return profile
  **/
  public String getProfile() {
    return profile;
  }

  public void setProfile(String profile) {
    this.profile = profile;
  }

  public IDToken picture(String picture) {
    this.picture = picture;
    return this;
  }

   /**
   * Get picture
   * @return picture
  **/
  public String getPicture() {
    return picture;
  }

  public void setPicture(String picture) {
    this.picture = picture;
  }

  public IDToken website(String website) {
    this.website = website;
    return this;
  }

   /**
   * Get website
   * @return website
  **/
  public String getWebsite() {
    return website;
  }

  public void setWebsite(String website) {
    this.website = website;
  }

  public IDToken email(String email) {
    this.email = email;
    return this;
  }

   /**
   * Get email
   * @return email
  **/
  public String getEmail() {
    return email;
  }

  public void setEmail(String email) {
    this.email = email;
  }

  public IDToken emailVerified(Boolean emailVerified) {
    this.emailVerified = emailVerified;
    return this;
  }

   /**
   * Get emailVerified
   * @return emailVerified
  **/
  public Boolean isEmailVerified() {
    return emailVerified;
  }

  public void setEmailVerified(Boolean emailVerified) {
    this.emailVerified = emailVerified;
  }

  public IDToken gender(String gender) {
    this.gender = gender;
    return this;
  }

   /**
   * Get gender
   * @return gender
  **/
  public String getGender() {
    return gender;
  }

  public void setGender(String gender) {
    this.gender = gender;
  }

  public IDToken birthdate(String birthdate) {
    this.birthdate = birthdate;
    return this;
  }

   /**
   * Get birthdate
   * @return birthdate
  **/
  public String getBirthdate() {
    return birthdate;
  }

  public void setBirthdate(String birthdate) {
    this.birthdate = birthdate;
  }

  public IDToken zoneinfo(String zoneinfo) {
    this.zoneinfo = zoneinfo;
    return this;
  }

   /**
   * Get zoneinfo
   * @return zoneinfo
  **/
  public String getZoneinfo() {
    return zoneinfo;
  }

  public void setZoneinfo(String zoneinfo) {
    this.zoneinfo = zoneinfo;
  }

  public IDToken locale(String locale) {
    this.locale = locale;
    return this;
  }

   /**
   * Get locale
   * @return locale
  **/
  public String getLocale() {
    return locale;
  }

  public void setLocale(String locale) {
    this.locale = locale;
  }

  public IDToken phoneNumber(String phoneNumber) {
    this.phoneNumber = phoneNumber;
    return this;
  }

   /**
   * Get phoneNumber
   * @return phoneNumber
  **/
  public String getPhoneNumber() {
    return phoneNumber;
  }

  public void setPhoneNumber(String phoneNumber) {
    this.phoneNumber = phoneNumber;
  }

  public IDToken phoneNumberVerified(Boolean phoneNumberVerified) {
    this.phoneNumberVerified = phoneNumberVerified;
    return this;
  }

   /**
   * Get phoneNumberVerified
   * @return phoneNumberVerified
  **/
  public Boolean isPhoneNumberVerified() {
    return phoneNumberVerified;
  }

  public void setPhoneNumberVerified(Boolean phoneNumberVerified) {
    this.phoneNumberVerified = phoneNumberVerified;
  }

  public IDToken address(AccessTokenAddress address) {
    this.address = address;
    return this;
  }

   /**
   * Get address
   * @return address
  **/
  public AccessTokenAddress getAddress() {
    return address;
  }

  public void setAddress(AccessTokenAddress address) {
    this.address = address;
  }

  public IDToken updatedAt(Long updatedAt) {
    this.updatedAt = updatedAt;
    return this;
  }

   /**
   * Get updatedAt
   * @return updatedAt
  **/
  public Long getUpdatedAt() {
    return updatedAt;
  }

  public void setUpdatedAt(Long updatedAt) {
    this.updatedAt = updatedAt;
  }

  public IDToken claimsLocales(String claimsLocales) {
    this.claimsLocales = claimsLocales;
    return this;
  }

   /**
   * Get claimsLocales
   * @return claimsLocales
  **/
  public String getClaimsLocales() {
    return claimsLocales;
  }

  public void setClaimsLocales(String claimsLocales) {
    this.claimsLocales = claimsLocales;
  }

  public IDToken acr(String acr) {
    this.acr = acr;
    return this;
  }

   /**
   * Get acr
   * @return acr
  **/
  public String getAcr() {
    return acr;
  }

  public void setAcr(String acr) {
    this.acr = acr;
  }

  public IDToken sHash(String sHash) {
    this.sHash = sHash;
    return this;
  }

   /**
   * Get sHash
   * @return sHash
  **/
  public String getSHash() {
    return sHash;
  }

  public void setSHash(String sHash) {
    this.sHash = sHash;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    IDToken idToken = (IDToken) o;
    return Objects.equals(this.jti, idToken.jti) &&
        Objects.equals(this.exp, idToken.exp) &&
        Objects.equals(this.nbf, idToken.nbf) &&
        Objects.equals(this.iat, idToken.iat) &&
        Objects.equals(this.iss, idToken.iss) &&
        Objects.equals(this.sub, idToken.sub) &&
        Objects.equals(this.typ, idToken.typ) &&
        Objects.equals(this.azp, idToken.azp) &&
        Objects.equals(this.otherClaims, idToken.otherClaims) &&
        Objects.equals(this.nonce, idToken.nonce) &&
        Objects.equals(this.authTime, idToken.authTime) &&
        Objects.equals(this.sid, idToken.sid) &&
        Objects.equals(this.atHash, idToken.atHash) &&
        Objects.equals(this.cHash, idToken.cHash) &&
        Objects.equals(this.name, idToken.name) &&
        Objects.equals(this.givenName, idToken.givenName) &&
        Objects.equals(this.familyName, idToken.familyName) &&
        Objects.equals(this.middleName, idToken.middleName) &&
        Objects.equals(this.nickname, idToken.nickname) &&
        Objects.equals(this.preferredUsername, idToken.preferredUsername) &&
        Objects.equals(this.profile, idToken.profile) &&
        Objects.equals(this.picture, idToken.picture) &&
        Objects.equals(this.website, idToken.website) &&
        Objects.equals(this.email, idToken.email) &&
        Objects.equals(this.emailVerified, idToken.emailVerified) &&
        Objects.equals(this.gender, idToken.gender) &&
        Objects.equals(this.birthdate, idToken.birthdate) &&
        Objects.equals(this.zoneinfo, idToken.zoneinfo) &&
        Objects.equals(this.locale, idToken.locale) &&
        Objects.equals(this.phoneNumber, idToken.phoneNumber) &&
        Objects.equals(this.phoneNumberVerified, idToken.phoneNumberVerified) &&
        Objects.equals(this.address, idToken.address) &&
        Objects.equals(this.updatedAt, idToken.updatedAt) &&
        Objects.equals(this.claimsLocales, idToken.claimsLocales) &&
        Objects.equals(this.acr, idToken.acr) &&
        Objects.equals(this.sHash, idToken.sHash);
  }

  @Override
  public int hashCode() {
    return Objects.hash(jti, exp, nbf, iat, iss, sub, typ, azp, otherClaims, nonce, authTime, sid, atHash, cHash, name, givenName, familyName, middleName, nickname, preferredUsername, profile, picture, website, email, emailVerified, gender, birthdate, zoneinfo, locale, phoneNumber, phoneNumberVerified, address, updatedAt, claimsLocales, acr, sHash);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class IDToken {\n");
    
    sb.append("    jti: ").append(toIndentedString(jti)).append("\n");
    sb.append("    exp: ").append(toIndentedString(exp)).append("\n");
    sb.append("    nbf: ").append(toIndentedString(nbf)).append("\n");
    sb.append("    iat: ").append(toIndentedString(iat)).append("\n");
    sb.append("    iss: ").append(toIndentedString(iss)).append("\n");
    sb.append("    sub: ").append(toIndentedString(sub)).append("\n");
    sb.append("    typ: ").append(toIndentedString(typ)).append("\n");
    sb.append("    azp: ").append(toIndentedString(azp)).append("\n");
    sb.append("    otherClaims: ").append(toIndentedString(otherClaims)).append("\n");
    sb.append("    nonce: ").append(toIndentedString(nonce)).append("\n");
    sb.append("    authTime: ").append(toIndentedString(authTime)).append("\n");
    sb.append("    sid: ").append(toIndentedString(sid)).append("\n");
    sb.append("    atHash: ").append(toIndentedString(atHash)).append("\n");
    sb.append("    cHash: ").append(toIndentedString(cHash)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    givenName: ").append(toIndentedString(givenName)).append("\n");
    sb.append("    familyName: ").append(toIndentedString(familyName)).append("\n");
    sb.append("    middleName: ").append(toIndentedString(middleName)).append("\n");
    sb.append("    nickname: ").append(toIndentedString(nickname)).append("\n");
    sb.append("    preferredUsername: ").append(toIndentedString(preferredUsername)).append("\n");
    sb.append("    profile: ").append(toIndentedString(profile)).append("\n");
    sb.append("    picture: ").append(toIndentedString(picture)).append("\n");
    sb.append("    website: ").append(toIndentedString(website)).append("\n");
    sb.append("    email: ").append(toIndentedString(email)).append("\n");
    sb.append("    emailVerified: ").append(toIndentedString(emailVerified)).append("\n");
    sb.append("    gender: ").append(toIndentedString(gender)).append("\n");
    sb.append("    birthdate: ").append(toIndentedString(birthdate)).append("\n");
    sb.append("    zoneinfo: ").append(toIndentedString(zoneinfo)).append("\n");
    sb.append("    locale: ").append(toIndentedString(locale)).append("\n");
    sb.append("    phoneNumber: ").append(toIndentedString(phoneNumber)).append("\n");
    sb.append("    phoneNumberVerified: ").append(toIndentedString(phoneNumberVerified)).append("\n");
    sb.append("    address: ").append(toIndentedString(address)).append("\n");
    sb.append("    updatedAt: ").append(toIndentedString(updatedAt)).append("\n");
    sb.append("    claimsLocales: ").append(toIndentedString(claimsLocales)).append("\n");
    sb.append("    acr: ").append(toIndentedString(acr)).append("\n");
    sb.append("    sHash: ").append(toIndentedString(sHash)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
