/*
 * Keycloak Admin REST API
 * This is a REST API reference for the Keycloak Admin REST API.
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.keycloak.www.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

import java.util.HashMap;
import java.util.List;
import java.util.Map;
/**
 * InlineResponse20019
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-03-11T12:00:50.005853600+07:00[Asia/Bangkok]")

public class InlineResponse20019 {
  @JsonProperty("id")
  private String id = null;

  @JsonProperty("username")
  private String username = null;

  @JsonProperty("userId")
  private String userId = null;

  @JsonProperty("ipAddress")
  private String ipAddress = null;

  @JsonProperty("start")
  private Long start = null;

  @JsonProperty("lastAccess")
  private Long lastAccess = null;

  @JsonProperty("rememberMe")
  private Boolean rememberMe = null;

  @JsonProperty("clients")
  private Map<String, String> clients = null;

  @JsonProperty("transientUser")
  private Boolean transientUser = null;

  public InlineResponse20019 id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public InlineResponse20019 username(String username) {
    this.username = username;
    return this;
  }

   /**
   * Get username
   * @return username
  **/
  public String getUsername() {
    return username;
  }

  public void setUsername(String username) {
    this.username = username;
  }

  public InlineResponse20019 userId(String userId) {
    this.userId = userId;
    return this;
  }

   /**
   * Get userId
   * @return userId
  **/
  public String getUserId() {
    return userId;
  }

  public void setUserId(String userId) {
    this.userId = userId;
  }

  public InlineResponse20019 ipAddress(String ipAddress) {
    this.ipAddress = ipAddress;
    return this;
  }

   /**
   * Get ipAddress
   * @return ipAddress
  **/
  public String getIpAddress() {
    return ipAddress;
  }

  public void setIpAddress(String ipAddress) {
    this.ipAddress = ipAddress;
  }

  public InlineResponse20019 start(Long start) {
    this.start = start;
    return this;
  }

   /**
   * Get start
   * @return start
  **/
  public Long getStart() {
    return start;
  }

  public void setStart(Long start) {
    this.start = start;
  }

  public InlineResponse20019 lastAccess(Long lastAccess) {
    this.lastAccess = lastAccess;
    return this;
  }

   /**
   * Get lastAccess
   * @return lastAccess
  **/
  public Long getLastAccess() {
    return lastAccess;
  }

  public void setLastAccess(Long lastAccess) {
    this.lastAccess = lastAccess;
  }

  public InlineResponse20019 rememberMe(Boolean rememberMe) {
    this.rememberMe = rememberMe;
    return this;
  }

   /**
   * Get rememberMe
   * @return rememberMe
  **/
  public Boolean isRememberMe() {
    return rememberMe;
  }

  public void setRememberMe(Boolean rememberMe) {
    this.rememberMe = rememberMe;
  }

  public InlineResponse20019 clients(Map<String, String> clients) {
    this.clients = clients;
    return this;
  }

  public InlineResponse20019 putClientsItem(String key, String clientsItem) {
    if (this.clients == null) {
      this.clients = new HashMap<>();
    }
    this.clients.put(key, clientsItem);
    return this;
  }

   /**
   * Get clients
   * @return clients
  **/
  public Map<String, String> getClients() {
    return clients;
  }

  public void setClients(Map<String, String> clients) {
    this.clients = clients;
  }

  public InlineResponse20019 transientUser(Boolean transientUser) {
    this.transientUser = transientUser;
    return this;
  }

   /**
   * Get transientUser
   * @return transientUser
  **/
  public Boolean isTransientUser() {
    return transientUser;
  }

  public void setTransientUser(Boolean transientUser) {
    this.transientUser = transientUser;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse20019 inlineResponse20019 = (InlineResponse20019) o;
    return Objects.equals(this.id, inlineResponse20019.id) &&
        Objects.equals(this.username, inlineResponse20019.username) &&
        Objects.equals(this.userId, inlineResponse20019.userId) &&
        Objects.equals(this.ipAddress, inlineResponse20019.ipAddress) &&
        Objects.equals(this.start, inlineResponse20019.start) &&
        Objects.equals(this.lastAccess, inlineResponse20019.lastAccess) &&
        Objects.equals(this.rememberMe, inlineResponse20019.rememberMe) &&
        Objects.equals(this.clients, inlineResponse20019.clients) &&
        Objects.equals(this.transientUser, inlineResponse20019.transientUser);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, username, userId, ipAddress, start, lastAccess, rememberMe, clients, transientUser);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse20019 {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    username: ").append(toIndentedString(username)).append("\n");
    sb.append("    userId: ").append(toIndentedString(userId)).append("\n");
    sb.append("    ipAddress: ").append(toIndentedString(ipAddress)).append("\n");
    sb.append("    start: ").append(toIndentedString(start)).append("\n");
    sb.append("    lastAccess: ").append(toIndentedString(lastAccess)).append("\n");
    sb.append("    rememberMe: ").append(toIndentedString(rememberMe)).append("\n");
    sb.append("    clients: ").append(toIndentedString(clients)).append("\n");
    sb.append("    transientUser: ").append(toIndentedString(transientUser)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
