/*
 * Keycloak Admin REST API
 * This is a REST API reference for the Keycloak Admin REST API.
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.keycloak.www.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.keycloak.www.client.KeysMetadataRepresentationKeys;
/**
 * InlineResponse20024
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-03-11T12:00:50.005853600+07:00[Asia/Bangkok]")

public class InlineResponse20024 {
  @JsonProperty("active")
  private Map<String, String> active = null;

  @JsonProperty("keys")
  private List<KeysMetadataRepresentationKeys> keys = null;

  public InlineResponse20024 active(Map<String, String> active) {
    this.active = active;
    return this;
  }

  public InlineResponse20024 putActiveItem(String key, String activeItem) {
    if (this.active == null) {
      this.active = new HashMap<>();
    }
    this.active.put(key, activeItem);
    return this;
  }

   /**
   * Get active
   * @return active
  **/
  public Map<String, String> getActive() {
    return active;
  }

  public void setActive(Map<String, String> active) {
    this.active = active;
  }

  public InlineResponse20024 keys(List<KeysMetadataRepresentationKeys> keys) {
    this.keys = keys;
    return this;
  }

  public InlineResponse20024 addKeysItem(KeysMetadataRepresentationKeys keysItem) {
    if (this.keys == null) {
      this.keys = new ArrayList<>();
    }
    this.keys.add(keysItem);
    return this;
  }

   /**
   * Get keys
   * @return keys
  **/
  public List<KeysMetadataRepresentationKeys> getKeys() {
    return keys;
  }

  public void setKeys(List<KeysMetadataRepresentationKeys> keys) {
    this.keys = keys;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse20024 inlineResponse20024 = (InlineResponse20024) o;
    return Objects.equals(this.active, inlineResponse20024.active) &&
        Objects.equals(this.keys, inlineResponse20024.keys);
  }

  @Override
  public int hashCode() {
    return Objects.hash(active, keys);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse20024 {\n");
    
    sb.append("    active: ").append(toIndentedString(active)).append("\n");
    sb.append("    keys: ").append(toIndentedString(keys)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
