/*
 * Keycloak Admin REST API
 * This is a REST API reference for the Keycloak Admin REST API.
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.keycloak.www.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

import java.util.ArrayList;
import java.util.List;
import org.keycloak.www.client.AdminrealmsAdminPermissionsClientAuthorizationSettingsResources;
import org.keycloak.www.client.AdminrealmsAdminPermissionsClientAuthorizationSettingsScopes;
/**
 * InlineResponse20011
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-03-11T12:00:50.005853600+07:00[Asia/Bangkok]")

public class InlineResponse20011 {
  @JsonProperty("id")
  private String id = null;

  @JsonProperty("name")
  private String name = null;

  @JsonProperty("description")
  private String description = null;

  @JsonProperty("type")
  private String type = null;

  @JsonProperty("policies")
  private List<String> policies = null;

  @JsonProperty("resources")
  private List<String> resources = null;

  @JsonProperty("scopes")
  private List<String> scopes = null;

  /**
   * Gets or Sets logic
   */
  public enum LogicEnum {
    POSITIVE("POSITIVE"),
    NEGATIVE("NEGATIVE");

    private String value;

    LogicEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static LogicEnum fromValue(String input) {
      for (LogicEnum b : LogicEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("logic")
  private LogicEnum logic = null;

  /**
   * Gets or Sets decisionStrategy
   */
  public enum DecisionStrategyEnum {
    AFFIRMATIVE("AFFIRMATIVE"),
    UNANIMOUS("UNANIMOUS"),
    CONSENSUS("CONSENSUS");

    private String value;

    DecisionStrategyEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static DecisionStrategyEnum fromValue(String input) {
      for (DecisionStrategyEnum b : DecisionStrategyEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("decisionStrategy")
  private DecisionStrategyEnum decisionStrategy = null;

  @JsonProperty("owner")
  private String owner = null;

  @JsonProperty("resourceType")
  private String resourceType = null;

  @JsonProperty("resourcesData")
  private List<AdminrealmsAdminPermissionsClientAuthorizationSettingsResources> resourcesData = null;

  @JsonProperty("scopesData")
  private List<AdminrealmsAdminPermissionsClientAuthorizationSettingsScopes> scopesData = null;

  public InlineResponse20011 id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public InlineResponse20011 name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public InlineResponse20011 description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public InlineResponse20011 type(String type) {
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  public String getType() {
    return type;
  }

  public void setType(String type) {
    this.type = type;
  }

  public InlineResponse20011 policies(List<String> policies) {
    this.policies = policies;
    return this;
  }

  public InlineResponse20011 addPoliciesItem(String policiesItem) {
    if (this.policies == null) {
      this.policies = new ArrayList<>();
    }
    this.policies.add(policiesItem);
    return this;
  }

   /**
   * Get policies
   * @return policies
  **/
  public List<String> getPolicies() {
    return policies;
  }

  public void setPolicies(List<String> policies) {
    this.policies = policies;
  }

  public InlineResponse20011 resources(List<String> resources) {
    this.resources = resources;
    return this;
  }

  public InlineResponse20011 addResourcesItem(String resourcesItem) {
    if (this.resources == null) {
      this.resources = new ArrayList<>();
    }
    this.resources.add(resourcesItem);
    return this;
  }

   /**
   * Get resources
   * @return resources
  **/
  public List<String> getResources() {
    return resources;
  }

  public void setResources(List<String> resources) {
    this.resources = resources;
  }

  public InlineResponse20011 scopes(List<String> scopes) {
    this.scopes = scopes;
    return this;
  }

  public InlineResponse20011 addScopesItem(String scopesItem) {
    if (this.scopes == null) {
      this.scopes = new ArrayList<>();
    }
    this.scopes.add(scopesItem);
    return this;
  }

   /**
   * Get scopes
   * @return scopes
  **/
  public List<String> getScopes() {
    return scopes;
  }

  public void setScopes(List<String> scopes) {
    this.scopes = scopes;
  }

  public InlineResponse20011 logic(LogicEnum logic) {
    this.logic = logic;
    return this;
  }

   /**
   * Get logic
   * @return logic
  **/
  public LogicEnum getLogic() {
    return logic;
  }

  public void setLogic(LogicEnum logic) {
    this.logic = logic;
  }

  public InlineResponse20011 decisionStrategy(DecisionStrategyEnum decisionStrategy) {
    this.decisionStrategy = decisionStrategy;
    return this;
  }

   /**
   * Get decisionStrategy
   * @return decisionStrategy
  **/
  public DecisionStrategyEnum getDecisionStrategy() {
    return decisionStrategy;
  }

  public void setDecisionStrategy(DecisionStrategyEnum decisionStrategy) {
    this.decisionStrategy = decisionStrategy;
  }

  public InlineResponse20011 owner(String owner) {
    this.owner = owner;
    return this;
  }

   /**
   * Get owner
   * @return owner
  **/
  public String getOwner() {
    return owner;
  }

  public void setOwner(String owner) {
    this.owner = owner;
  }

  public InlineResponse20011 resourceType(String resourceType) {
    this.resourceType = resourceType;
    return this;
  }

   /**
   * Get resourceType
   * @return resourceType
  **/
  public String getResourceType() {
    return resourceType;
  }

  public void setResourceType(String resourceType) {
    this.resourceType = resourceType;
  }

  public InlineResponse20011 resourcesData(List<AdminrealmsAdminPermissionsClientAuthorizationSettingsResources> resourcesData) {
    this.resourcesData = resourcesData;
    return this;
  }

  public InlineResponse20011 addResourcesDataItem(AdminrealmsAdminPermissionsClientAuthorizationSettingsResources resourcesDataItem) {
    if (this.resourcesData == null) {
      this.resourcesData = new ArrayList<>();
    }
    this.resourcesData.add(resourcesDataItem);
    return this;
  }

   /**
   * Get resourcesData
   * @return resourcesData
  **/
  public List<AdminrealmsAdminPermissionsClientAuthorizationSettingsResources> getResourcesData() {
    return resourcesData;
  }

  public void setResourcesData(List<AdminrealmsAdminPermissionsClientAuthorizationSettingsResources> resourcesData) {
    this.resourcesData = resourcesData;
  }

  public InlineResponse20011 scopesData(List<AdminrealmsAdminPermissionsClientAuthorizationSettingsScopes> scopesData) {
    this.scopesData = scopesData;
    return this;
  }

  public InlineResponse20011 addScopesDataItem(AdminrealmsAdminPermissionsClientAuthorizationSettingsScopes scopesDataItem) {
    if (this.scopesData == null) {
      this.scopesData = new ArrayList<>();
    }
    this.scopesData.add(scopesDataItem);
    return this;
  }

   /**
   * Get scopesData
   * @return scopesData
  **/
  public List<AdminrealmsAdminPermissionsClientAuthorizationSettingsScopes> getScopesData() {
    return scopesData;
  }

  public void setScopesData(List<AdminrealmsAdminPermissionsClientAuthorizationSettingsScopes> scopesData) {
    this.scopesData = scopesData;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse20011 inlineResponse20011 = (InlineResponse20011) o;
    return Objects.equals(this.id, inlineResponse20011.id) &&
        Objects.equals(this.name, inlineResponse20011.name) &&
        Objects.equals(this.description, inlineResponse20011.description) &&
        Objects.equals(this.type, inlineResponse20011.type) &&
        Objects.equals(this.policies, inlineResponse20011.policies) &&
        Objects.equals(this.resources, inlineResponse20011.resources) &&
        Objects.equals(this.scopes, inlineResponse20011.scopes) &&
        Objects.equals(this.logic, inlineResponse20011.logic) &&
        Objects.equals(this.decisionStrategy, inlineResponse20011.decisionStrategy) &&
        Objects.equals(this.owner, inlineResponse20011.owner) &&
        Objects.equals(this.resourceType, inlineResponse20011.resourceType) &&
        Objects.equals(this.resourcesData, inlineResponse20011.resourcesData) &&
        Objects.equals(this.scopesData, inlineResponse20011.scopesData);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, description, type, policies, resources, scopes, logic, decisionStrategy, owner, resourceType, resourcesData, scopesData);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse20011 {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    policies: ").append(toIndentedString(policies)).append("\n");
    sb.append("    resources: ").append(toIndentedString(resources)).append("\n");
    sb.append("    scopes: ").append(toIndentedString(scopes)).append("\n");
    sb.append("    logic: ").append(toIndentedString(logic)).append("\n");
    sb.append("    decisionStrategy: ").append(toIndentedString(decisionStrategy)).append("\n");
    sb.append("    owner: ").append(toIndentedString(owner)).append("\n");
    sb.append("    resourceType: ").append(toIndentedString(resourceType)).append("\n");
    sb.append("    resourcesData: ").append(toIndentedString(resourcesData)).append("\n");
    sb.append("    scopesData: ").append(toIndentedString(scopesData)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
