/*
 * Keycloak Admin REST API
 * This is a REST API reference for the Keycloak Admin REST API.
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.keycloak.www.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * InlineResponse20010
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-03-11T12:00:50.005853600+07:00[Asia/Bangkok]")

public class InlineResponse20010 {
  @JsonProperty("id")
  private String id = null;

  @JsonProperty("token")
  private String token = null;

  @JsonProperty("timestamp")
  private Integer timestamp = null;

  @JsonProperty("expiration")
  private Integer expiration = null;

  @JsonProperty("count")
  private Integer count = null;

  @JsonProperty("remainingCount")
  private Integer remainingCount = null;

  public InlineResponse20010 id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public InlineResponse20010 token(String token) {
    this.token = token;
    return this;
  }

   /**
   * Get token
   * @return token
  **/
  public String getToken() {
    return token;
  }

  public void setToken(String token) {
    this.token = token;
  }

  public InlineResponse20010 timestamp(Integer timestamp) {
    this.timestamp = timestamp;
    return this;
  }

   /**
   * Get timestamp
   * @return timestamp
  **/
  public Integer getTimestamp() {
    return timestamp;
  }

  public void setTimestamp(Integer timestamp) {
    this.timestamp = timestamp;
  }

  public InlineResponse20010 expiration(Integer expiration) {
    this.expiration = expiration;
    return this;
  }

   /**
   * Get expiration
   * @return expiration
  **/
  public Integer getExpiration() {
    return expiration;
  }

  public void setExpiration(Integer expiration) {
    this.expiration = expiration;
  }

  public InlineResponse20010 count(Integer count) {
    this.count = count;
    return this;
  }

   /**
   * Get count
   * @return count
  **/
  public Integer getCount() {
    return count;
  }

  public void setCount(Integer count) {
    this.count = count;
  }

  public InlineResponse20010 remainingCount(Integer remainingCount) {
    this.remainingCount = remainingCount;
    return this;
  }

   /**
   * Get remainingCount
   * @return remainingCount
  **/
  public Integer getRemainingCount() {
    return remainingCount;
  }

  public void setRemainingCount(Integer remainingCount) {
    this.remainingCount = remainingCount;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse20010 inlineResponse20010 = (InlineResponse20010) o;
    return Objects.equals(this.id, inlineResponse20010.id) &&
        Objects.equals(this.token, inlineResponse20010.token) &&
        Objects.equals(this.timestamp, inlineResponse20010.timestamp) &&
        Objects.equals(this.expiration, inlineResponse20010.expiration) &&
        Objects.equals(this.count, inlineResponse20010.count) &&
        Objects.equals(this.remainingCount, inlineResponse20010.remainingCount);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, token, timestamp, expiration, count, remainingCount);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse20010 {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    token: ").append(toIndentedString(token)).append("\n");
    sb.append("    timestamp: ").append(toIndentedString(timestamp)).append("\n");
    sb.append("    expiration: ").append(toIndentedString(expiration)).append("\n");
    sb.append("    count: ").append(toIndentedString(count)).append("\n");
    sb.append("    remainingCount: ").append(toIndentedString(remainingCount)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
