/*
 * Keycloak Admin REST API
 * This is a REST API reference for the Keycloak Admin REST API.
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.keycloak.www.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.keycloak.www.client.AccessTokenAddress;
import org.keycloak.www.client.AccessTokenAuthorization;
import org.keycloak.www.client.AccessTokenCnf;
import org.keycloak.www.client.AccessTokenRealmAccess;
/**
 * InlineResponse20015
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-03-11T12:00:50.005853600+07:00[Asia/Bangkok]")

public class InlineResponse20015 {
  @JsonProperty("jti")
  private String jti = null;

  @JsonProperty("exp")
  private Long exp = null;

  @JsonProperty("nbf")
  private Long nbf = null;

  @JsonProperty("iat")
  private Long iat = null;

  @JsonProperty("iss")
  private String iss = null;

  @JsonProperty("sub")
  private String sub = null;

  @JsonProperty("typ")
  private String typ = null;

  @JsonProperty("azp")
  private String azp = null;

  @JsonProperty("otherClaims")
  private Map<String, Object> otherClaims = null;

  @JsonProperty("nonce")
  private String nonce = null;

  @JsonProperty("auth_time")
  private Long authTime = null;

  @JsonProperty("sid")
  private String sid = null;

  @JsonProperty("at_hash")
  private String atHash = null;

  @JsonProperty("c_hash")
  private String cHash = null;

  @JsonProperty("name")
  private String name = null;

  @JsonProperty("given_name")
  private String givenName = null;

  @JsonProperty("family_name")
  private String familyName = null;

  @JsonProperty("middle_name")
  private String middleName = null;

  @JsonProperty("nickname")
  private String nickname = null;

  @JsonProperty("preferred_username")
  private String preferredUsername = null;

  @JsonProperty("profile")
  private String profile = null;

  @JsonProperty("picture")
  private String picture = null;

  @JsonProperty("website")
  private String website = null;

  @JsonProperty("email")
  private String email = null;

  @JsonProperty("email_verified")
  private Boolean emailVerified = null;

  @JsonProperty("gender")
  private String gender = null;

  @JsonProperty("birthdate")
  private String birthdate = null;

  @JsonProperty("zoneinfo")
  private String zoneinfo = null;

  @JsonProperty("locale")
  private String locale = null;

  @JsonProperty("phone_number")
  private String phoneNumber = null;

  @JsonProperty("phone_number_verified")
  private Boolean phoneNumberVerified = null;

  @JsonProperty("address")
  private AccessTokenAddress address = null;

  @JsonProperty("updated_at")
  private Long updatedAt = null;

  @JsonProperty("claims_locales")
  private String claimsLocales = null;

  @JsonProperty("acr")
  private String acr = null;

  @JsonProperty("s_hash")
  private String sHash = null;

  @JsonProperty("trusted-certs")
  private List<String> trustedCerts = null;

  @JsonProperty("allowed-origins")
  private List<String> allowedOrigins = null;

  @JsonProperty("realm_access")
  private AccessTokenRealmAccess realmAccess = null;

  @JsonProperty("resource_access")
  private Map<String, AccessTokenRealmAccess> resourceAccess = null;

  @JsonProperty("authorization")
  private AccessTokenAuthorization authorization = null;

  @JsonProperty("cnf")
  private AccessTokenCnf cnf = null;

  @JsonProperty("scope")
  private String scope = null;

  public InlineResponse20015 jti(String jti) {
    this.jti = jti;
    return this;
  }

   /**
   * Get jti
   * @return jti
  **/
  public String getJti() {
    return jti;
  }

  public void setJti(String jti) {
    this.jti = jti;
  }

  public InlineResponse20015 exp(Long exp) {
    this.exp = exp;
    return this;
  }

   /**
   * Get exp
   * @return exp
  **/
  public Long getExp() {
    return exp;
  }

  public void setExp(Long exp) {
    this.exp = exp;
  }

  public InlineResponse20015 nbf(Long nbf) {
    this.nbf = nbf;
    return this;
  }

   /**
   * Get nbf
   * @return nbf
  **/
  public Long getNbf() {
    return nbf;
  }

  public void setNbf(Long nbf) {
    this.nbf = nbf;
  }

  public InlineResponse20015 iat(Long iat) {
    this.iat = iat;
    return this;
  }

   /**
   * Get iat
   * @return iat
  **/
  public Long getIat() {
    return iat;
  }

  public void setIat(Long iat) {
    this.iat = iat;
  }

  public InlineResponse20015 iss(String iss) {
    this.iss = iss;
    return this;
  }

   /**
   * Get iss
   * @return iss
  **/
  public String getIss() {
    return iss;
  }

  public void setIss(String iss) {
    this.iss = iss;
  }

  public InlineResponse20015 sub(String sub) {
    this.sub = sub;
    return this;
  }

   /**
   * Get sub
   * @return sub
  **/
  public String getSub() {
    return sub;
  }

  public void setSub(String sub) {
    this.sub = sub;
  }

  public InlineResponse20015 typ(String typ) {
    this.typ = typ;
    return this;
  }

   /**
   * Get typ
   * @return typ
  **/
  public String getTyp() {
    return typ;
  }

  public void setTyp(String typ) {
    this.typ = typ;
  }

  public InlineResponse20015 azp(String azp) {
    this.azp = azp;
    return this;
  }

   /**
   * Get azp
   * @return azp
  **/
  public String getAzp() {
    return azp;
  }

  public void setAzp(String azp) {
    this.azp = azp;
  }

  public InlineResponse20015 otherClaims(Map<String, Object> otherClaims) {
    this.otherClaims = otherClaims;
    return this;
  }

  public InlineResponse20015 putOtherClaimsItem(String key, Object otherClaimsItem) {
    if (this.otherClaims == null) {
      this.otherClaims = new HashMap<>();
    }
    this.otherClaims.put(key, otherClaimsItem);
    return this;
  }

   /**
   * Get otherClaims
   * @return otherClaims
  **/
  public Map<String, Object> getOtherClaims() {
    return otherClaims;
  }

  public void setOtherClaims(Map<String, Object> otherClaims) {
    this.otherClaims = otherClaims;
  }

  public InlineResponse20015 nonce(String nonce) {
    this.nonce = nonce;
    return this;
  }

   /**
   * Get nonce
   * @return nonce
  **/
  public String getNonce() {
    return nonce;
  }

  public void setNonce(String nonce) {
    this.nonce = nonce;
  }

  public InlineResponse20015 authTime(Long authTime) {
    this.authTime = authTime;
    return this;
  }

   /**
   * Get authTime
   * @return authTime
  **/
  public Long getAuthTime() {
    return authTime;
  }

  public void setAuthTime(Long authTime) {
    this.authTime = authTime;
  }

  public InlineResponse20015 sid(String sid) {
    this.sid = sid;
    return this;
  }

   /**
   * Get sid
   * @return sid
  **/
  public String getSid() {
    return sid;
  }

  public void setSid(String sid) {
    this.sid = sid;
  }

  public InlineResponse20015 atHash(String atHash) {
    this.atHash = atHash;
    return this;
  }

   /**
   * Get atHash
   * @return atHash
  **/
  public String getAtHash() {
    return atHash;
  }

  public void setAtHash(String atHash) {
    this.atHash = atHash;
  }

  public InlineResponse20015 cHash(String cHash) {
    this.cHash = cHash;
    return this;
  }

   /**
   * Get cHash
   * @return cHash
  **/
  public String getCHash() {
    return cHash;
  }

  public void setCHash(String cHash) {
    this.cHash = cHash;
  }

  public InlineResponse20015 name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public InlineResponse20015 givenName(String givenName) {
    this.givenName = givenName;
    return this;
  }

   /**
   * Get givenName
   * @return givenName
  **/
  public String getGivenName() {
    return givenName;
  }

  public void setGivenName(String givenName) {
    this.givenName = givenName;
  }

  public InlineResponse20015 familyName(String familyName) {
    this.familyName = familyName;
    return this;
  }

   /**
   * Get familyName
   * @return familyName
  **/
  public String getFamilyName() {
    return familyName;
  }

  public void setFamilyName(String familyName) {
    this.familyName = familyName;
  }

  public InlineResponse20015 middleName(String middleName) {
    this.middleName = middleName;
    return this;
  }

   /**
   * Get middleName
   * @return middleName
  **/
  public String getMiddleName() {
    return middleName;
  }

  public void setMiddleName(String middleName) {
    this.middleName = middleName;
  }

  public InlineResponse20015 nickname(String nickname) {
    this.nickname = nickname;
    return this;
  }

   /**
   * Get nickname
   * @return nickname
  **/
  public String getNickname() {
    return nickname;
  }

  public void setNickname(String nickname) {
    this.nickname = nickname;
  }

  public InlineResponse20015 preferredUsername(String preferredUsername) {
    this.preferredUsername = preferredUsername;
    return this;
  }

   /**
   * Get preferredUsername
   * @return preferredUsername
  **/
  public String getPreferredUsername() {
    return preferredUsername;
  }

  public void setPreferredUsername(String preferredUsername) {
    this.preferredUsername = preferredUsername;
  }

  public InlineResponse20015 profile(String profile) {
    this.profile = profile;
    return this;
  }

   /**
   * Get profile
   * @return profile
  **/
  public String getProfile() {
    return profile;
  }

  public void setProfile(String profile) {
    this.profile = profile;
  }

  public InlineResponse20015 picture(String picture) {
    this.picture = picture;
    return this;
  }

   /**
   * Get picture
   * @return picture
  **/
  public String getPicture() {
    return picture;
  }

  public void setPicture(String picture) {
    this.picture = picture;
  }

  public InlineResponse20015 website(String website) {
    this.website = website;
    return this;
  }

   /**
   * Get website
   * @return website
  **/
  public String getWebsite() {
    return website;
  }

  public void setWebsite(String website) {
    this.website = website;
  }

  public InlineResponse20015 email(String email) {
    this.email = email;
    return this;
  }

   /**
   * Get email
   * @return email
  **/
  public String getEmail() {
    return email;
  }

  public void setEmail(String email) {
    this.email = email;
  }

  public InlineResponse20015 emailVerified(Boolean emailVerified) {
    this.emailVerified = emailVerified;
    return this;
  }

   /**
   * Get emailVerified
   * @return emailVerified
  **/
  public Boolean isEmailVerified() {
    return emailVerified;
  }

  public void setEmailVerified(Boolean emailVerified) {
    this.emailVerified = emailVerified;
  }

  public InlineResponse20015 gender(String gender) {
    this.gender = gender;
    return this;
  }

   /**
   * Get gender
   * @return gender
  **/
  public String getGender() {
    return gender;
  }

  public void setGender(String gender) {
    this.gender = gender;
  }

  public InlineResponse20015 birthdate(String birthdate) {
    this.birthdate = birthdate;
    return this;
  }

   /**
   * Get birthdate
   * @return birthdate
  **/
  public String getBirthdate() {
    return birthdate;
  }

  public void setBirthdate(String birthdate) {
    this.birthdate = birthdate;
  }

  public InlineResponse20015 zoneinfo(String zoneinfo) {
    this.zoneinfo = zoneinfo;
    return this;
  }

   /**
   * Get zoneinfo
   * @return zoneinfo
  **/
  public String getZoneinfo() {
    return zoneinfo;
  }

  public void setZoneinfo(String zoneinfo) {
    this.zoneinfo = zoneinfo;
  }

  public InlineResponse20015 locale(String locale) {
    this.locale = locale;
    return this;
  }

   /**
   * Get locale
   * @return locale
  **/
  public String getLocale() {
    return locale;
  }

  public void setLocale(String locale) {
    this.locale = locale;
  }

  public InlineResponse20015 phoneNumber(String phoneNumber) {
    this.phoneNumber = phoneNumber;
    return this;
  }

   /**
   * Get phoneNumber
   * @return phoneNumber
  **/
  public String getPhoneNumber() {
    return phoneNumber;
  }

  public void setPhoneNumber(String phoneNumber) {
    this.phoneNumber = phoneNumber;
  }

  public InlineResponse20015 phoneNumberVerified(Boolean phoneNumberVerified) {
    this.phoneNumberVerified = phoneNumberVerified;
    return this;
  }

   /**
   * Get phoneNumberVerified
   * @return phoneNumberVerified
  **/
  public Boolean isPhoneNumberVerified() {
    return phoneNumberVerified;
  }

  public void setPhoneNumberVerified(Boolean phoneNumberVerified) {
    this.phoneNumberVerified = phoneNumberVerified;
  }

  public InlineResponse20015 address(AccessTokenAddress address) {
    this.address = address;
    return this;
  }

   /**
   * Get address
   * @return address
  **/
  public AccessTokenAddress getAddress() {
    return address;
  }

  public void setAddress(AccessTokenAddress address) {
    this.address = address;
  }

  public InlineResponse20015 updatedAt(Long updatedAt) {
    this.updatedAt = updatedAt;
    return this;
  }

   /**
   * Get updatedAt
   * @return updatedAt
  **/
  public Long getUpdatedAt() {
    return updatedAt;
  }

  public void setUpdatedAt(Long updatedAt) {
    this.updatedAt = updatedAt;
  }

  public InlineResponse20015 claimsLocales(String claimsLocales) {
    this.claimsLocales = claimsLocales;
    return this;
  }

   /**
   * Get claimsLocales
   * @return claimsLocales
  **/
  public String getClaimsLocales() {
    return claimsLocales;
  }

  public void setClaimsLocales(String claimsLocales) {
    this.claimsLocales = claimsLocales;
  }

  public InlineResponse20015 acr(String acr) {
    this.acr = acr;
    return this;
  }

   /**
   * Get acr
   * @return acr
  **/
  public String getAcr() {
    return acr;
  }

  public void setAcr(String acr) {
    this.acr = acr;
  }

  public InlineResponse20015 sHash(String sHash) {
    this.sHash = sHash;
    return this;
  }

   /**
   * Get sHash
   * @return sHash
  **/
  public String getSHash() {
    return sHash;
  }

  public void setSHash(String sHash) {
    this.sHash = sHash;
  }

  public InlineResponse20015 trustedCerts(List<String> trustedCerts) {
    this.trustedCerts = trustedCerts;
    return this;
  }

  public InlineResponse20015 addTrustedCertsItem(String trustedCertsItem) {
    if (this.trustedCerts == null) {
      this.trustedCerts = new ArrayList<>();
    }
    this.trustedCerts.add(trustedCertsItem);
    return this;
  }

   /**
   * Get trustedCerts
   * @return trustedCerts
  **/
  public List<String> getTrustedCerts() {
    return trustedCerts;
  }

  public void setTrustedCerts(List<String> trustedCerts) {
    this.trustedCerts = trustedCerts;
  }

  public InlineResponse20015 allowedOrigins(List<String> allowedOrigins) {
    this.allowedOrigins = allowedOrigins;
    return this;
  }

  public InlineResponse20015 addAllowedOriginsItem(String allowedOriginsItem) {
    if (this.allowedOrigins == null) {
      this.allowedOrigins = new ArrayList<>();
    }
    this.allowedOrigins.add(allowedOriginsItem);
    return this;
  }

   /**
   * Get allowedOrigins
   * @return allowedOrigins
  **/
  public List<String> getAllowedOrigins() {
    return allowedOrigins;
  }

  public void setAllowedOrigins(List<String> allowedOrigins) {
    this.allowedOrigins = allowedOrigins;
  }

  public InlineResponse20015 realmAccess(AccessTokenRealmAccess realmAccess) {
    this.realmAccess = realmAccess;
    return this;
  }

   /**
   * Get realmAccess
   * @return realmAccess
  **/
  public AccessTokenRealmAccess getRealmAccess() {
    return realmAccess;
  }

  public void setRealmAccess(AccessTokenRealmAccess realmAccess) {
    this.realmAccess = realmAccess;
  }

  public InlineResponse20015 resourceAccess(Map<String, AccessTokenRealmAccess> resourceAccess) {
    this.resourceAccess = resourceAccess;
    return this;
  }

  public InlineResponse20015 putResourceAccessItem(String key, AccessTokenRealmAccess resourceAccessItem) {
    if (this.resourceAccess == null) {
      this.resourceAccess = new HashMap<>();
    }
    this.resourceAccess.put(key, resourceAccessItem);
    return this;
  }

   /**
   * Get resourceAccess
   * @return resourceAccess
  **/
  public Map<String, AccessTokenRealmAccess> getResourceAccess() {
    return resourceAccess;
  }

  public void setResourceAccess(Map<String, AccessTokenRealmAccess> resourceAccess) {
    this.resourceAccess = resourceAccess;
  }

  public InlineResponse20015 authorization(AccessTokenAuthorization authorization) {
    this.authorization = authorization;
    return this;
  }

   /**
   * Get authorization
   * @return authorization
  **/
  public AccessTokenAuthorization getAuthorization() {
    return authorization;
  }

  public void setAuthorization(AccessTokenAuthorization authorization) {
    this.authorization = authorization;
  }

  public InlineResponse20015 cnf(AccessTokenCnf cnf) {
    this.cnf = cnf;
    return this;
  }

   /**
   * Get cnf
   * @return cnf
  **/
  public AccessTokenCnf getCnf() {
    return cnf;
  }

  public void setCnf(AccessTokenCnf cnf) {
    this.cnf = cnf;
  }

  public InlineResponse20015 scope(String scope) {
    this.scope = scope;
    return this;
  }

   /**
   * Get scope
   * @return scope
  **/
  public String getScope() {
    return scope;
  }

  public void setScope(String scope) {
    this.scope = scope;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse20015 inlineResponse20015 = (InlineResponse20015) o;
    return Objects.equals(this.jti, inlineResponse20015.jti) &&
        Objects.equals(this.exp, inlineResponse20015.exp) &&
        Objects.equals(this.nbf, inlineResponse20015.nbf) &&
        Objects.equals(this.iat, inlineResponse20015.iat) &&
        Objects.equals(this.iss, inlineResponse20015.iss) &&
        Objects.equals(this.sub, inlineResponse20015.sub) &&
        Objects.equals(this.typ, inlineResponse20015.typ) &&
        Objects.equals(this.azp, inlineResponse20015.azp) &&
        Objects.equals(this.otherClaims, inlineResponse20015.otherClaims) &&
        Objects.equals(this.nonce, inlineResponse20015.nonce) &&
        Objects.equals(this.authTime, inlineResponse20015.authTime) &&
        Objects.equals(this.sid, inlineResponse20015.sid) &&
        Objects.equals(this.atHash, inlineResponse20015.atHash) &&
        Objects.equals(this.cHash, inlineResponse20015.cHash) &&
        Objects.equals(this.name, inlineResponse20015.name) &&
        Objects.equals(this.givenName, inlineResponse20015.givenName) &&
        Objects.equals(this.familyName, inlineResponse20015.familyName) &&
        Objects.equals(this.middleName, inlineResponse20015.middleName) &&
        Objects.equals(this.nickname, inlineResponse20015.nickname) &&
        Objects.equals(this.preferredUsername, inlineResponse20015.preferredUsername) &&
        Objects.equals(this.profile, inlineResponse20015.profile) &&
        Objects.equals(this.picture, inlineResponse20015.picture) &&
        Objects.equals(this.website, inlineResponse20015.website) &&
        Objects.equals(this.email, inlineResponse20015.email) &&
        Objects.equals(this.emailVerified, inlineResponse20015.emailVerified) &&
        Objects.equals(this.gender, inlineResponse20015.gender) &&
        Objects.equals(this.birthdate, inlineResponse20015.birthdate) &&
        Objects.equals(this.zoneinfo, inlineResponse20015.zoneinfo) &&
        Objects.equals(this.locale, inlineResponse20015.locale) &&
        Objects.equals(this.phoneNumber, inlineResponse20015.phoneNumber) &&
        Objects.equals(this.phoneNumberVerified, inlineResponse20015.phoneNumberVerified) &&
        Objects.equals(this.address, inlineResponse20015.address) &&
        Objects.equals(this.updatedAt, inlineResponse20015.updatedAt) &&
        Objects.equals(this.claimsLocales, inlineResponse20015.claimsLocales) &&
        Objects.equals(this.acr, inlineResponse20015.acr) &&
        Objects.equals(this.sHash, inlineResponse20015.sHash) &&
        Objects.equals(this.trustedCerts, inlineResponse20015.trustedCerts) &&
        Objects.equals(this.allowedOrigins, inlineResponse20015.allowedOrigins) &&
        Objects.equals(this.realmAccess, inlineResponse20015.realmAccess) &&
        Objects.equals(this.resourceAccess, inlineResponse20015.resourceAccess) &&
        Objects.equals(this.authorization, inlineResponse20015.authorization) &&
        Objects.equals(this.cnf, inlineResponse20015.cnf) &&
        Objects.equals(this.scope, inlineResponse20015.scope);
  }

  @Override
  public int hashCode() {
    return Objects.hash(jti, exp, nbf, iat, iss, sub, typ, azp, otherClaims, nonce, authTime, sid, atHash, cHash, name, givenName, familyName, middleName, nickname, preferredUsername, profile, picture, website, email, emailVerified, gender, birthdate, zoneinfo, locale, phoneNumber, phoneNumberVerified, address, updatedAt, claimsLocales, acr, sHash, trustedCerts, allowedOrigins, realmAccess, resourceAccess, authorization, cnf, scope);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse20015 {\n");
    
    sb.append("    jti: ").append(toIndentedString(jti)).append("\n");
    sb.append("    exp: ").append(toIndentedString(exp)).append("\n");
    sb.append("    nbf: ").append(toIndentedString(nbf)).append("\n");
    sb.append("    iat: ").append(toIndentedString(iat)).append("\n");
    sb.append("    iss: ").append(toIndentedString(iss)).append("\n");
    sb.append("    sub: ").append(toIndentedString(sub)).append("\n");
    sb.append("    typ: ").append(toIndentedString(typ)).append("\n");
    sb.append("    azp: ").append(toIndentedString(azp)).append("\n");
    sb.append("    otherClaims: ").append(toIndentedString(otherClaims)).append("\n");
    sb.append("    nonce: ").append(toIndentedString(nonce)).append("\n");
    sb.append("    authTime: ").append(toIndentedString(authTime)).append("\n");
    sb.append("    sid: ").append(toIndentedString(sid)).append("\n");
    sb.append("    atHash: ").append(toIndentedString(atHash)).append("\n");
    sb.append("    cHash: ").append(toIndentedString(cHash)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    givenName: ").append(toIndentedString(givenName)).append("\n");
    sb.append("    familyName: ").append(toIndentedString(familyName)).append("\n");
    sb.append("    middleName: ").append(toIndentedString(middleName)).append("\n");
    sb.append("    nickname: ").append(toIndentedString(nickname)).append("\n");
    sb.append("    preferredUsername: ").append(toIndentedString(preferredUsername)).append("\n");
    sb.append("    profile: ").append(toIndentedString(profile)).append("\n");
    sb.append("    picture: ").append(toIndentedString(picture)).append("\n");
    sb.append("    website: ").append(toIndentedString(website)).append("\n");
    sb.append("    email: ").append(toIndentedString(email)).append("\n");
    sb.append("    emailVerified: ").append(toIndentedString(emailVerified)).append("\n");
    sb.append("    gender: ").append(toIndentedString(gender)).append("\n");
    sb.append("    birthdate: ").append(toIndentedString(birthdate)).append("\n");
    sb.append("    zoneinfo: ").append(toIndentedString(zoneinfo)).append("\n");
    sb.append("    locale: ").append(toIndentedString(locale)).append("\n");
    sb.append("    phoneNumber: ").append(toIndentedString(phoneNumber)).append("\n");
    sb.append("    phoneNumberVerified: ").append(toIndentedString(phoneNumberVerified)).append("\n");
    sb.append("    address: ").append(toIndentedString(address)).append("\n");
    sb.append("    updatedAt: ").append(toIndentedString(updatedAt)).append("\n");
    sb.append("    claimsLocales: ").append(toIndentedString(claimsLocales)).append("\n");
    sb.append("    acr: ").append(toIndentedString(acr)).append("\n");
    sb.append("    sHash: ").append(toIndentedString(sHash)).append("\n");
    sb.append("    trustedCerts: ").append(toIndentedString(trustedCerts)).append("\n");
    sb.append("    allowedOrigins: ").append(toIndentedString(allowedOrigins)).append("\n");
    sb.append("    realmAccess: ").append(toIndentedString(realmAccess)).append("\n");
    sb.append("    resourceAccess: ").append(toIndentedString(resourceAccess)).append("\n");
    sb.append("    authorization: ").append(toIndentedString(authorization)).append("\n");
    sb.append("    cnf: ").append(toIndentedString(cnf)).append("\n");
    sb.append("    scope: ").append(toIndentedString(scope)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
