/*
 * Keycloak Admin REST API
 * This is a REST API reference for the Keycloak Admin REST API.
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.keycloak.www.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * KeyMetadataRepresentation
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-03-11T12:00:50.005853600+07:00[Asia/Bangkok]")

public class KeyMetadataRepresentation {
  @JsonProperty("providerId")
  private String providerId = null;

  @JsonProperty("providerPriority")
  private Long providerPriority = null;

  @JsonProperty("kid")
  private String kid = null;

  @JsonProperty("status")
  private String status = null;

  @JsonProperty("type")
  private String type = null;

  @JsonProperty("algorithm")
  private String algorithm = null;

  @JsonProperty("publicKey")
  private String publicKey = null;

  @JsonProperty("certificate")
  private String certificate = null;

  /**
   * Gets or Sets use
   */
  public enum UseEnum {
    SIG("SIG"),
    ENC("ENC");

    private String value;

    UseEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static UseEnum fromValue(String input) {
      for (UseEnum b : UseEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("use")
  private UseEnum use = null;

  @JsonProperty("validTo")
  private Long validTo = null;

  public KeyMetadataRepresentation providerId(String providerId) {
    this.providerId = providerId;
    return this;
  }

   /**
   * Get providerId
   * @return providerId
  **/
  public String getProviderId() {
    return providerId;
  }

  public void setProviderId(String providerId) {
    this.providerId = providerId;
  }

  public KeyMetadataRepresentation providerPriority(Long providerPriority) {
    this.providerPriority = providerPriority;
    return this;
  }

   /**
   * Get providerPriority
   * @return providerPriority
  **/
  public Long getProviderPriority() {
    return providerPriority;
  }

  public void setProviderPriority(Long providerPriority) {
    this.providerPriority = providerPriority;
  }

  public KeyMetadataRepresentation kid(String kid) {
    this.kid = kid;
    return this;
  }

   /**
   * Get kid
   * @return kid
  **/
  public String getKid() {
    return kid;
  }

  public void setKid(String kid) {
    this.kid = kid;
  }

  public KeyMetadataRepresentation status(String status) {
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  public String getStatus() {
    return status;
  }

  public void setStatus(String status) {
    this.status = status;
  }

  public KeyMetadataRepresentation type(String type) {
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  public String getType() {
    return type;
  }

  public void setType(String type) {
    this.type = type;
  }

  public KeyMetadataRepresentation algorithm(String algorithm) {
    this.algorithm = algorithm;
    return this;
  }

   /**
   * Get algorithm
   * @return algorithm
  **/
  public String getAlgorithm() {
    return algorithm;
  }

  public void setAlgorithm(String algorithm) {
    this.algorithm = algorithm;
  }

  public KeyMetadataRepresentation publicKey(String publicKey) {
    this.publicKey = publicKey;
    return this;
  }

   /**
   * Get publicKey
   * @return publicKey
  **/
  public String getPublicKey() {
    return publicKey;
  }

  public void setPublicKey(String publicKey) {
    this.publicKey = publicKey;
  }

  public KeyMetadataRepresentation certificate(String certificate) {
    this.certificate = certificate;
    return this;
  }

   /**
   * Get certificate
   * @return certificate
  **/
  public String getCertificate() {
    return certificate;
  }

  public void setCertificate(String certificate) {
    this.certificate = certificate;
  }

  public KeyMetadataRepresentation use(UseEnum use) {
    this.use = use;
    return this;
  }

   /**
   * Get use
   * @return use
  **/
  public UseEnum getUse() {
    return use;
  }

  public void setUse(UseEnum use) {
    this.use = use;
  }

  public KeyMetadataRepresentation validTo(Long validTo) {
    this.validTo = validTo;
    return this;
  }

   /**
   * Get validTo
   * @return validTo
  **/
  public Long getValidTo() {
    return validTo;
  }

  public void setValidTo(Long validTo) {
    this.validTo = validTo;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    KeyMetadataRepresentation keyMetadataRepresentation = (KeyMetadataRepresentation) o;
    return Objects.equals(this.providerId, keyMetadataRepresentation.providerId) &&
        Objects.equals(this.providerPriority, keyMetadataRepresentation.providerPriority) &&
        Objects.equals(this.kid, keyMetadataRepresentation.kid) &&
        Objects.equals(this.status, keyMetadataRepresentation.status) &&
        Objects.equals(this.type, keyMetadataRepresentation.type) &&
        Objects.equals(this.algorithm, keyMetadataRepresentation.algorithm) &&
        Objects.equals(this.publicKey, keyMetadataRepresentation.publicKey) &&
        Objects.equals(this.certificate, keyMetadataRepresentation.certificate) &&
        Objects.equals(this.use, keyMetadataRepresentation.use) &&
        Objects.equals(this.validTo, keyMetadataRepresentation.validTo);
  }

  @Override
  public int hashCode() {
    return Objects.hash(providerId, providerPriority, kid, status, type, algorithm, publicKey, certificate, use, validTo);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class KeyMetadataRepresentation {\n");
    
    sb.append("    providerId: ").append(toIndentedString(providerId)).append("\n");
    sb.append("    providerPriority: ").append(toIndentedString(providerPriority)).append("\n");
    sb.append("    kid: ").append(toIndentedString(kid)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    algorithm: ").append(toIndentedString(algorithm)).append("\n");
    sb.append("    publicKey: ").append(toIndentedString(publicKey)).append("\n");
    sb.append("    certificate: ").append(toIndentedString(certificate)).append("\n");
    sb.append("    use: ").append(toIndentedString(use)).append("\n");
    sb.append("    validTo: ").append(toIndentedString(validTo)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
