/*
 * Keycloak Admin REST API
 * This is a REST API reference for the Keycloak Admin REST API.
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.keycloak.www.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

import java.util.HashMap;
import java.util.List;
import java.util.Map;
/**
 * ManagementPermissionsBody1
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-03-11T12:00:50.005853600+07:00[Asia/Bangkok]")

public class ManagementPermissionsBody1 {
  @JsonProperty("enabled")
  private Boolean enabled = null;

  @JsonProperty("resource")
  private String resource = null;

  @JsonProperty("scopePermissions")
  private Map<String, String> scopePermissions = null;

  public ManagementPermissionsBody1 enabled(Boolean enabled) {
    this.enabled = enabled;
    return this;
  }

   /**
   * Get enabled
   * @return enabled
  **/
  public Boolean isEnabled() {
    return enabled;
  }

  public void setEnabled(Boolean enabled) {
    this.enabled = enabled;
  }

  public ManagementPermissionsBody1 resource(String resource) {
    this.resource = resource;
    return this;
  }

   /**
   * Get resource
   * @return resource
  **/
  public String getResource() {
    return resource;
  }

  public void setResource(String resource) {
    this.resource = resource;
  }

  public ManagementPermissionsBody1 scopePermissions(Map<String, String> scopePermissions) {
    this.scopePermissions = scopePermissions;
    return this;
  }

  public ManagementPermissionsBody1 putScopePermissionsItem(String key, String scopePermissionsItem) {
    if (this.scopePermissions == null) {
      this.scopePermissions = new HashMap<>();
    }
    this.scopePermissions.put(key, scopePermissionsItem);
    return this;
  }

   /**
   * Get scopePermissions
   * @return scopePermissions
  **/
  public Map<String, String> getScopePermissions() {
    return scopePermissions;
  }

  public void setScopePermissions(Map<String, String> scopePermissions) {
    this.scopePermissions = scopePermissions;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ManagementPermissionsBody1 managementPermissionsBody1 = (ManagementPermissionsBody1) o;
    return Objects.equals(this.enabled, managementPermissionsBody1.enabled) &&
        Objects.equals(this.resource, managementPermissionsBody1.resource) &&
        Objects.equals(this.scopePermissions, managementPermissionsBody1.scopePermissions);
  }

  @Override
  public int hashCode() {
    return Objects.hash(enabled, resource, scopePermissions);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ManagementPermissionsBody1 {\n");
    
    sb.append("    enabled: ").append(toIndentedString(enabled)).append("\n");
    sb.append("    resource: ").append(toIndentedString(resource)).append("\n");
    sb.append("    scopePermissions: ").append(toIndentedString(scopePermissions)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
