/*
 * Keycloak Admin REST API
 * This is a REST API reference for the Keycloak Admin REST API.
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.keycloak.www.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

import java.util.HashMap;
import java.util.List;
import java.util.Map;
/**
 * MappersIdBody
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-03-11T12:00:50.005853600+07:00[Asia/Bangkok]")

public class MappersIdBody {
  @JsonProperty("id")
  private String id = null;

  @JsonProperty("name")
  private String name = null;

  @JsonProperty("identityProviderAlias")
  private String identityProviderAlias = null;

  @JsonProperty("identityProviderMapper")
  private String identityProviderMapper = null;

  @JsonProperty("config")
  private Map<String, String> config = null;

  public MappersIdBody id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public MappersIdBody name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public MappersIdBody identityProviderAlias(String identityProviderAlias) {
    this.identityProviderAlias = identityProviderAlias;
    return this;
  }

   /**
   * Get identityProviderAlias
   * @return identityProviderAlias
  **/
  public String getIdentityProviderAlias() {
    return identityProviderAlias;
  }

  public void setIdentityProviderAlias(String identityProviderAlias) {
    this.identityProviderAlias = identityProviderAlias;
  }

  public MappersIdBody identityProviderMapper(String identityProviderMapper) {
    this.identityProviderMapper = identityProviderMapper;
    return this;
  }

   /**
   * Get identityProviderMapper
   * @return identityProviderMapper
  **/
  public String getIdentityProviderMapper() {
    return identityProviderMapper;
  }

  public void setIdentityProviderMapper(String identityProviderMapper) {
    this.identityProviderMapper = identityProviderMapper;
  }

  public MappersIdBody config(Map<String, String> config) {
    this.config = config;
    return this;
  }

  public MappersIdBody putConfigItem(String key, String configItem) {
    if (this.config == null) {
      this.config = new HashMap<>();
    }
    this.config.put(key, configItem);
    return this;
  }

   /**
   * Get config
   * @return config
  **/
  public Map<String, String> getConfig() {
    return config;
  }

  public void setConfig(Map<String, String> config) {
    this.config = config;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MappersIdBody mappersIdBody = (MappersIdBody) o;
    return Objects.equals(this.id, mappersIdBody.id) &&
        Objects.equals(this.name, mappersIdBody.name) &&
        Objects.equals(this.identityProviderAlias, mappersIdBody.identityProviderAlias) &&
        Objects.equals(this.identityProviderMapper, mappersIdBody.identityProviderMapper) &&
        Objects.equals(this.config, mappersIdBody.config);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, identityProviderAlias, identityProviderMapper, config);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MappersIdBody {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    identityProviderAlias: ").append(toIndentedString(identityProviderAlias)).append("\n");
    sb.append("    identityProviderMapper: ").append(toIndentedString(identityProviderMapper)).append("\n");
    sb.append("    config: ").append(toIndentedString(config)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
