/*
 * Keycloak Admin REST API
 * This is a REST API reference for the Keycloak Admin REST API.
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.keycloak.www.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

import java.util.ArrayList;
import java.util.List;
import org.keycloak.www.client.RolesRolenameBody1;
/**
 * MappingsRepresentationClientMappings
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-03-11T12:00:50.005853600+07:00[Asia/Bangkok]")

public class MappingsRepresentationClientMappings {
  @JsonProperty("id")
  private String id = null;

  @JsonProperty("client")
  private String client = null;

  @JsonProperty("mappings")
  private List<RolesRolenameBody1> mappings = null;

  public MappingsRepresentationClientMappings id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public MappingsRepresentationClientMappings client(String client) {
    this.client = client;
    return this;
  }

   /**
   * Get client
   * @return client
  **/
  public String getClient() {
    return client;
  }

  public void setClient(String client) {
    this.client = client;
  }

  public MappingsRepresentationClientMappings mappings(List<RolesRolenameBody1> mappings) {
    this.mappings = mappings;
    return this;
  }

  public MappingsRepresentationClientMappings addMappingsItem(RolesRolenameBody1 mappingsItem) {
    if (this.mappings == null) {
      this.mappings = new ArrayList<>();
    }
    this.mappings.add(mappingsItem);
    return this;
  }

   /**
   * Get mappings
   * @return mappings
  **/
  public List<RolesRolenameBody1> getMappings() {
    return mappings;
  }

  public void setMappings(List<RolesRolenameBody1> mappings) {
    this.mappings = mappings;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MappingsRepresentationClientMappings mappingsRepresentationClientMappings = (MappingsRepresentationClientMappings) o;
    return Objects.equals(this.id, mappingsRepresentationClientMappings.id) &&
        Objects.equals(this.client, mappingsRepresentationClientMappings.client) &&
        Objects.equals(this.mappings, mappingsRepresentationClientMappings.mappings);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, client, mappings);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MappingsRepresentationClientMappings {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    client: ").append(toIndentedString(client)).append("\n");
    sb.append("    mappings: ").append(toIndentedString(mappings)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
