/*
 * Keycloak Admin REST API
 * This is a REST API reference for the Keycloak Admin REST API.
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.keycloak.www.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.keycloak.www.client.AdminrealmsDomains;
import org.keycloak.www.client.AdminrealmsIdentityProviders;
import org.keycloak.www.client.AdminrealmsMembers;
/**
 * OrganizationsOrgidBody
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-03-11T12:00:50.005853600+07:00[Asia/Bangkok]")

public class OrganizationsOrgidBody {
  @JsonProperty("id")
  private String id = null;

  @JsonProperty("name")
  private String name = null;

  @JsonProperty("alias")
  private String alias = null;

  @JsonProperty("enabled")
  private Boolean enabled = null;

  @JsonProperty("description")
  private String description = null;

  @JsonProperty("redirectUrl")
  private String redirectUrl = null;

  @JsonProperty("attributes")
  private Map<String, List<String>> attributes = null;

  @JsonProperty("domains")
  private List<AdminrealmsDomains> domains = null;

  @JsonProperty("members")
  private List<AdminrealmsMembers> members = null;

  @JsonProperty("identityProviders")
  private List<AdminrealmsIdentityProviders> identityProviders = null;

  public OrganizationsOrgidBody id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public OrganizationsOrgidBody name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public OrganizationsOrgidBody alias(String alias) {
    this.alias = alias;
    return this;
  }

   /**
   * Get alias
   * @return alias
  **/
  public String getAlias() {
    return alias;
  }

  public void setAlias(String alias) {
    this.alias = alias;
  }

  public OrganizationsOrgidBody enabled(Boolean enabled) {
    this.enabled = enabled;
    return this;
  }

   /**
   * Get enabled
   * @return enabled
  **/
  public Boolean isEnabled() {
    return enabled;
  }

  public void setEnabled(Boolean enabled) {
    this.enabled = enabled;
  }

  public OrganizationsOrgidBody description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public OrganizationsOrgidBody redirectUrl(String redirectUrl) {
    this.redirectUrl = redirectUrl;
    return this;
  }

   /**
   * Get redirectUrl
   * @return redirectUrl
  **/
  public String getRedirectUrl() {
    return redirectUrl;
  }

  public void setRedirectUrl(String redirectUrl) {
    this.redirectUrl = redirectUrl;
  }

  public OrganizationsOrgidBody attributes(Map<String, List<String>> attributes) {
    this.attributes = attributes;
    return this;
  }

  public OrganizationsOrgidBody putAttributesItem(String key, List<String> attributesItem) {
    if (this.attributes == null) {
      this.attributes = new HashMap<>();
    }
    this.attributes.put(key, attributesItem);
    return this;
  }

   /**
   * Get attributes
   * @return attributes
  **/
  public Map<String, List<String>> getAttributes() {
    return attributes;
  }

  public void setAttributes(Map<String, List<String>> attributes) {
    this.attributes = attributes;
  }

  public OrganizationsOrgidBody domains(List<AdminrealmsDomains> domains) {
    this.domains = domains;
    return this;
  }

  public OrganizationsOrgidBody addDomainsItem(AdminrealmsDomains domainsItem) {
    if (this.domains == null) {
      this.domains = new ArrayList<>();
    }
    this.domains.add(domainsItem);
    return this;
  }

   /**
   * Get domains
   * @return domains
  **/
  public List<AdminrealmsDomains> getDomains() {
    return domains;
  }

  public void setDomains(List<AdminrealmsDomains> domains) {
    this.domains = domains;
  }

  public OrganizationsOrgidBody members(List<AdminrealmsMembers> members) {
    this.members = members;
    return this;
  }

  public OrganizationsOrgidBody addMembersItem(AdminrealmsMembers membersItem) {
    if (this.members == null) {
      this.members = new ArrayList<>();
    }
    this.members.add(membersItem);
    return this;
  }

   /**
   * Get members
   * @return members
  **/
  public List<AdminrealmsMembers> getMembers() {
    return members;
  }

  public void setMembers(List<AdminrealmsMembers> members) {
    this.members = members;
  }

  public OrganizationsOrgidBody identityProviders(List<AdminrealmsIdentityProviders> identityProviders) {
    this.identityProviders = identityProviders;
    return this;
  }

  public OrganizationsOrgidBody addIdentityProvidersItem(AdminrealmsIdentityProviders identityProvidersItem) {
    if (this.identityProviders == null) {
      this.identityProviders = new ArrayList<>();
    }
    this.identityProviders.add(identityProvidersItem);
    return this;
  }

   /**
   * Get identityProviders
   * @return identityProviders
  **/
  public List<AdminrealmsIdentityProviders> getIdentityProviders() {
    return identityProviders;
  }

  public void setIdentityProviders(List<AdminrealmsIdentityProviders> identityProviders) {
    this.identityProviders = identityProviders;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OrganizationsOrgidBody organizationsOrgidBody = (OrganizationsOrgidBody) o;
    return Objects.equals(this.id, organizationsOrgidBody.id) &&
        Objects.equals(this.name, organizationsOrgidBody.name) &&
        Objects.equals(this.alias, organizationsOrgidBody.alias) &&
        Objects.equals(this.enabled, organizationsOrgidBody.enabled) &&
        Objects.equals(this.description, organizationsOrgidBody.description) &&
        Objects.equals(this.redirectUrl, organizationsOrgidBody.redirectUrl) &&
        Objects.equals(this.attributes, organizationsOrgidBody.attributes) &&
        Objects.equals(this.domains, organizationsOrgidBody.domains) &&
        Objects.equals(this.members, organizationsOrgidBody.members) &&
        Objects.equals(this.identityProviders, organizationsOrgidBody.identityProviders);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, alias, enabled, description, redirectUrl, attributes, domains, members, identityProviders);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OrganizationsOrgidBody {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    alias: ").append(toIndentedString(alias)).append("\n");
    sb.append("    enabled: ").append(toIndentedString(enabled)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    redirectUrl: ").append(toIndentedString(redirectUrl)).append("\n");
    sb.append("    attributes: ").append(toIndentedString(attributes)).append("\n");
    sb.append("    domains: ").append(toIndentedString(domains)).append("\n");
    sb.append("    members: ").append(toIndentedString(members)).append("\n");
    sb.append("    identityProviders: ").append(toIndentedString(identityProviders)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
