/*
 * Keycloak Admin REST API
 * This is a REST API reference for the Keycloak Admin REST API.
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.keycloak.www.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * PathCacheConfig
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-03-11T12:00:50.005853600+07:00[Asia/Bangkok]")

public class PathCacheConfig {
  @JsonProperty("max-entries")
  private Integer maxEntries = null;

  @JsonProperty("lifespan")
  private Long lifespan = null;

  public PathCacheConfig maxEntries(Integer maxEntries) {
    this.maxEntries = maxEntries;
    return this;
  }

   /**
   * Get maxEntries
   * @return maxEntries
  **/
  public Integer getMaxEntries() {
    return maxEntries;
  }

  public void setMaxEntries(Integer maxEntries) {
    this.maxEntries = maxEntries;
  }

  public PathCacheConfig lifespan(Long lifespan) {
    this.lifespan = lifespan;
    return this;
  }

   /**
   * Get lifespan
   * @return lifespan
  **/
  public Long getLifespan() {
    return lifespan;
  }

  public void setLifespan(Long lifespan) {
    this.lifespan = lifespan;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PathCacheConfig pathCacheConfig = (PathCacheConfig) o;
    return Objects.equals(this.maxEntries, pathCacheConfig.maxEntries) &&
        Objects.equals(this.lifespan, pathCacheConfig.lifespan);
  }

  @Override
  public int hashCode() {
    return Objects.hash(maxEntries, lifespan);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PathCacheConfig {\n");
    
    sb.append("    maxEntries: ").append(toIndentedString(maxEntries)).append("\n");
    sb.append("    lifespan: ").append(toIndentedString(lifespan)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
