/*
 * Keycloak Admin REST API
 * This is a REST API reference for the Keycloak Admin REST API.
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.keycloak.www.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

import java.util.ArrayList;
import java.util.List;
import org.keycloak.www.client.EnforcementMode;
import org.keycloak.www.client.MethodConfig;
/**
 * PathConfig
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-03-11T12:00:50.005853600+07:00[Asia/Bangkok]")

public class PathConfig {
  @JsonProperty("name")
  private String name = null;

  @JsonProperty("type")
  private String type = null;

  @JsonProperty("path")
  private String path = null;

  @JsonProperty("methods")
  private List<MethodConfig> methods = null;

  @JsonProperty("scopes")
  private List<String> scopes = null;

  @JsonProperty("id")
  private String id = null;

  @JsonProperty("enforcement-mode")
  private EnforcementMode enforcementMode = null;

  @JsonProperty("claim-information-point")
  private Object claimInformationPoint = null;

  @JsonProperty("invalidated")
  private Boolean invalidated = null;

  @JsonProperty("staticPath")
  private Boolean staticPath = null;

  @JsonProperty("static")
  private Boolean _static = null;

  public PathConfig name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public PathConfig type(String type) {
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  public String getType() {
    return type;
  }

  public void setType(String type) {
    this.type = type;
  }

  public PathConfig path(String path) {
    this.path = path;
    return this;
  }

   /**
   * Get path
   * @return path
  **/
  public String getPath() {
    return path;
  }

  public void setPath(String path) {
    this.path = path;
  }

  public PathConfig methods(List<MethodConfig> methods) {
    this.methods = methods;
    return this;
  }

  public PathConfig addMethodsItem(MethodConfig methodsItem) {
    if (this.methods == null) {
      this.methods = new ArrayList<>();
    }
    this.methods.add(methodsItem);
    return this;
  }

   /**
   * Get methods
   * @return methods
  **/
  public List<MethodConfig> getMethods() {
    return methods;
  }

  public void setMethods(List<MethodConfig> methods) {
    this.methods = methods;
  }

  public PathConfig scopes(List<String> scopes) {
    this.scopes = scopes;
    return this;
  }

  public PathConfig addScopesItem(String scopesItem) {
    if (this.scopes == null) {
      this.scopes = new ArrayList<>();
    }
    this.scopes.add(scopesItem);
    return this;
  }

   /**
   * Get scopes
   * @return scopes
  **/
  public List<String> getScopes() {
    return scopes;
  }

  public void setScopes(List<String> scopes) {
    this.scopes = scopes;
  }

  public PathConfig id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public PathConfig enforcementMode(EnforcementMode enforcementMode) {
    this.enforcementMode = enforcementMode;
    return this;
  }

   /**
   * Get enforcementMode
   * @return enforcementMode
  **/
  public EnforcementMode getEnforcementMode() {
    return enforcementMode;
  }

  public void setEnforcementMode(EnforcementMode enforcementMode) {
    this.enforcementMode = enforcementMode;
  }

  public PathConfig claimInformationPoint(Object claimInformationPoint) {
    this.claimInformationPoint = claimInformationPoint;
    return this;
  }

   /**
   * Get claimInformationPoint
   * @return claimInformationPoint
  **/
  public Object getClaimInformationPoint() {
    return claimInformationPoint;
  }

  public void setClaimInformationPoint(Object claimInformationPoint) {
    this.claimInformationPoint = claimInformationPoint;
  }

  public PathConfig invalidated(Boolean invalidated) {
    this.invalidated = invalidated;
    return this;
  }

   /**
   * Get invalidated
   * @return invalidated
  **/
  public Boolean isInvalidated() {
    return invalidated;
  }

  public void setInvalidated(Boolean invalidated) {
    this.invalidated = invalidated;
  }

  public PathConfig staticPath(Boolean staticPath) {
    this.staticPath = staticPath;
    return this;
  }

   /**
   * Get staticPath
   * @return staticPath
  **/
  public Boolean isStaticPath() {
    return staticPath;
  }

  public void setStaticPath(Boolean staticPath) {
    this.staticPath = staticPath;
  }

  public PathConfig _static(Boolean _static) {
    this._static = _static;
    return this;
  }

   /**
   * Get _static
   * @return _static
  **/
  public Boolean isStatic() {
    return _static;
  }

  public void setStatic(Boolean _static) {
    this._static = _static;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PathConfig pathConfig = (PathConfig) o;
    return Objects.equals(this.name, pathConfig.name) &&
        Objects.equals(this.type, pathConfig.type) &&
        Objects.equals(this.path, pathConfig.path) &&
        Objects.equals(this.methods, pathConfig.methods) &&
        Objects.equals(this.scopes, pathConfig.scopes) &&
        Objects.equals(this.id, pathConfig.id) &&
        Objects.equals(this.enforcementMode, pathConfig.enforcementMode) &&
        Objects.equals(this.claimInformationPoint, pathConfig.claimInformationPoint) &&
        Objects.equals(this.invalidated, pathConfig.invalidated) &&
        Objects.equals(this.staticPath, pathConfig.staticPath) &&
        Objects.equals(this._static, pathConfig._static);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, type, path, methods, scopes, id, enforcementMode, claimInformationPoint, invalidated, staticPath, _static);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PathConfig {\n");
    
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    path: ").append(toIndentedString(path)).append("\n");
    sb.append("    methods: ").append(toIndentedString(methods)).append("\n");
    sb.append("    scopes: ").append(toIndentedString(scopes)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    enforcementMode: ").append(toIndentedString(enforcementMode)).append("\n");
    sb.append("    claimInformationPoint: ").append(toIndentedString(claimInformationPoint)).append("\n");
    sb.append("    invalidated: ").append(toIndentedString(invalidated)).append("\n");
    sb.append("    staticPath: ").append(toIndentedString(staticPath)).append("\n");
    sb.append("    _static: ").append(toIndentedString(_static)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
