/*
 * Keycloak Admin REST API
 * This is a REST API reference for the Keycloak Admin REST API.
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.keycloak.www.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.keycloak.www.client.EnforcementMode;
import org.keycloak.www.client.PathCacheConfig;
import org.keycloak.www.client.PathConfig;
import org.keycloak.www.client.UserManagedAccessConfig;
/**
 * PolicyEnforcerConfig
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-03-11T12:00:50.005853600+07:00[Asia/Bangkok]")

public class PolicyEnforcerConfig {
  @JsonProperty("enforcement-mode")
  private EnforcementMode enforcementMode = null;

  @JsonProperty("paths")
  private List<PathConfig> paths = null;

  @JsonProperty("path-cache")
  private PathCacheConfig pathCache = null;

  @JsonProperty("lazy-load-paths")
  private Boolean lazyLoadPaths = null;

  @JsonProperty("on-deny-redirect-to")
  private String onDenyRedirectTo = null;

  @JsonProperty("user-managed-access")
  private UserManagedAccessConfig userManagedAccess = null;

  @JsonProperty("claim-information-point")
  private Object claimInformationPoint = null;

  @JsonProperty("http-method-as-scope")
  private Boolean httpMethodAsScope = null;

  @JsonProperty("realm")
  private String realm = null;

  @JsonProperty("auth-server-url")
  private String authServerUrl = null;

  @JsonProperty("credentials")
  private Map<String, Object> credentials = null;

  @JsonProperty("resource")
  private String resource = null;

  public PolicyEnforcerConfig enforcementMode(EnforcementMode enforcementMode) {
    this.enforcementMode = enforcementMode;
    return this;
  }

   /**
   * Get enforcementMode
   * @return enforcementMode
  **/
  public EnforcementMode getEnforcementMode() {
    return enforcementMode;
  }

  public void setEnforcementMode(EnforcementMode enforcementMode) {
    this.enforcementMode = enforcementMode;
  }

  public PolicyEnforcerConfig paths(List<PathConfig> paths) {
    this.paths = paths;
    return this;
  }

  public PolicyEnforcerConfig addPathsItem(PathConfig pathsItem) {
    if (this.paths == null) {
      this.paths = new ArrayList<>();
    }
    this.paths.add(pathsItem);
    return this;
  }

   /**
   * Get paths
   * @return paths
  **/
  public List<PathConfig> getPaths() {
    return paths;
  }

  public void setPaths(List<PathConfig> paths) {
    this.paths = paths;
  }

  public PolicyEnforcerConfig pathCache(PathCacheConfig pathCache) {
    this.pathCache = pathCache;
    return this;
  }

   /**
   * Get pathCache
   * @return pathCache
  **/
  public PathCacheConfig getPathCache() {
    return pathCache;
  }

  public void setPathCache(PathCacheConfig pathCache) {
    this.pathCache = pathCache;
  }

  public PolicyEnforcerConfig lazyLoadPaths(Boolean lazyLoadPaths) {
    this.lazyLoadPaths = lazyLoadPaths;
    return this;
  }

   /**
   * Get lazyLoadPaths
   * @return lazyLoadPaths
  **/
  public Boolean isLazyLoadPaths() {
    return lazyLoadPaths;
  }

  public void setLazyLoadPaths(Boolean lazyLoadPaths) {
    this.lazyLoadPaths = lazyLoadPaths;
  }

  public PolicyEnforcerConfig onDenyRedirectTo(String onDenyRedirectTo) {
    this.onDenyRedirectTo = onDenyRedirectTo;
    return this;
  }

   /**
   * Get onDenyRedirectTo
   * @return onDenyRedirectTo
  **/
  public String getOnDenyRedirectTo() {
    return onDenyRedirectTo;
  }

  public void setOnDenyRedirectTo(String onDenyRedirectTo) {
    this.onDenyRedirectTo = onDenyRedirectTo;
  }

  public PolicyEnforcerConfig userManagedAccess(UserManagedAccessConfig userManagedAccess) {
    this.userManagedAccess = userManagedAccess;
    return this;
  }

   /**
   * Get userManagedAccess
   * @return userManagedAccess
  **/
  public UserManagedAccessConfig getUserManagedAccess() {
    return userManagedAccess;
  }

  public void setUserManagedAccess(UserManagedAccessConfig userManagedAccess) {
    this.userManagedAccess = userManagedAccess;
  }

  public PolicyEnforcerConfig claimInformationPoint(Object claimInformationPoint) {
    this.claimInformationPoint = claimInformationPoint;
    return this;
  }

   /**
   * Get claimInformationPoint
   * @return claimInformationPoint
  **/
  public Object getClaimInformationPoint() {
    return claimInformationPoint;
  }

  public void setClaimInformationPoint(Object claimInformationPoint) {
    this.claimInformationPoint = claimInformationPoint;
  }

  public PolicyEnforcerConfig httpMethodAsScope(Boolean httpMethodAsScope) {
    this.httpMethodAsScope = httpMethodAsScope;
    return this;
  }

   /**
   * Get httpMethodAsScope
   * @return httpMethodAsScope
  **/
  public Boolean isHttpMethodAsScope() {
    return httpMethodAsScope;
  }

  public void setHttpMethodAsScope(Boolean httpMethodAsScope) {
    this.httpMethodAsScope = httpMethodAsScope;
  }

  public PolicyEnforcerConfig realm(String realm) {
    this.realm = realm;
    return this;
  }

   /**
   * Get realm
   * @return realm
  **/
  public String getRealm() {
    return realm;
  }

  public void setRealm(String realm) {
    this.realm = realm;
  }

  public PolicyEnforcerConfig authServerUrl(String authServerUrl) {
    this.authServerUrl = authServerUrl;
    return this;
  }

   /**
   * Get authServerUrl
   * @return authServerUrl
  **/
  public String getAuthServerUrl() {
    return authServerUrl;
  }

  public void setAuthServerUrl(String authServerUrl) {
    this.authServerUrl = authServerUrl;
  }

  public PolicyEnforcerConfig credentials(Map<String, Object> credentials) {
    this.credentials = credentials;
    return this;
  }

  public PolicyEnforcerConfig putCredentialsItem(String key, Object credentialsItem) {
    if (this.credentials == null) {
      this.credentials = new HashMap<>();
    }
    this.credentials.put(key, credentialsItem);
    return this;
  }

   /**
   * Get credentials
   * @return credentials
  **/
  public Map<String, Object> getCredentials() {
    return credentials;
  }

  public void setCredentials(Map<String, Object> credentials) {
    this.credentials = credentials;
  }

  public PolicyEnforcerConfig resource(String resource) {
    this.resource = resource;
    return this;
  }

   /**
   * Get resource
   * @return resource
  **/
  public String getResource() {
    return resource;
  }

  public void setResource(String resource) {
    this.resource = resource;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PolicyEnforcerConfig policyEnforcerConfig = (PolicyEnforcerConfig) o;
    return Objects.equals(this.enforcementMode, policyEnforcerConfig.enforcementMode) &&
        Objects.equals(this.paths, policyEnforcerConfig.paths) &&
        Objects.equals(this.pathCache, policyEnforcerConfig.pathCache) &&
        Objects.equals(this.lazyLoadPaths, policyEnforcerConfig.lazyLoadPaths) &&
        Objects.equals(this.onDenyRedirectTo, policyEnforcerConfig.onDenyRedirectTo) &&
        Objects.equals(this.userManagedAccess, policyEnforcerConfig.userManagedAccess) &&
        Objects.equals(this.claimInformationPoint, policyEnforcerConfig.claimInformationPoint) &&
        Objects.equals(this.httpMethodAsScope, policyEnforcerConfig.httpMethodAsScope) &&
        Objects.equals(this.realm, policyEnforcerConfig.realm) &&
        Objects.equals(this.authServerUrl, policyEnforcerConfig.authServerUrl) &&
        Objects.equals(this.credentials, policyEnforcerConfig.credentials) &&
        Objects.equals(this.resource, policyEnforcerConfig.resource);
  }

  @Override
  public int hashCode() {
    return Objects.hash(enforcementMode, paths, pathCache, lazyLoadPaths, onDenyRedirectTo, userManagedAccess, claimInformationPoint, httpMethodAsScope, realm, authServerUrl, credentials, resource);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PolicyEnforcerConfig {\n");
    
    sb.append("    enforcementMode: ").append(toIndentedString(enforcementMode)).append("\n");
    sb.append("    paths: ").append(toIndentedString(paths)).append("\n");
    sb.append("    pathCache: ").append(toIndentedString(pathCache)).append("\n");
    sb.append("    lazyLoadPaths: ").append(toIndentedString(lazyLoadPaths)).append("\n");
    sb.append("    onDenyRedirectTo: ").append(toIndentedString(onDenyRedirectTo)).append("\n");
    sb.append("    userManagedAccess: ").append(toIndentedString(userManagedAccess)).append("\n");
    sb.append("    claimInformationPoint: ").append(toIndentedString(claimInformationPoint)).append("\n");
    sb.append("    httpMethodAsScope: ").append(toIndentedString(httpMethodAsScope)).append("\n");
    sb.append("    realm: ").append(toIndentedString(realm)).append("\n");
    sb.append("    authServerUrl: ").append(toIndentedString(authServerUrl)).append("\n");
    sb.append("    credentials: ").append(toIndentedString(credentials)).append("\n");
    sb.append("    resource: ").append(toIndentedString(resource)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
