/*
 * Keycloak Admin REST API
 * This is a REST API reference for the Keycloak Admin REST API.
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.keycloak.www.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.keycloak.www.client.AccessTokenAddress;
import org.keycloak.www.client.AccessTokenAuthorization;
import org.keycloak.www.client.AccessTokenCnf;
import org.keycloak.www.client.AccessTokenRealmAccess;
/**
 * PolicyEvaluationResponseRpt
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-03-11T12:00:50.005853600+07:00[Asia/Bangkok]")

public class PolicyEvaluationResponseRpt {
  @JsonProperty("jti")
  private String jti = null;

  @JsonProperty("exp")
  private Long exp = null;

  @JsonProperty("nbf")
  private Long nbf = null;

  @JsonProperty("iat")
  private Long iat = null;

  @JsonProperty("iss")
  private String iss = null;

  @JsonProperty("sub")
  private String sub = null;

  @JsonProperty("typ")
  private String typ = null;

  @JsonProperty("azp")
  private String azp = null;

  @JsonProperty("otherClaims")
  private Map<String, Object> otherClaims = null;

  @JsonProperty("nonce")
  private String nonce = null;

  @JsonProperty("auth_time")
  private Long authTime = null;

  @JsonProperty("sid")
  private String sid = null;

  @JsonProperty("at_hash")
  private String atHash = null;

  @JsonProperty("c_hash")
  private String cHash = null;

  @JsonProperty("name")
  private String name = null;

  @JsonProperty("given_name")
  private String givenName = null;

  @JsonProperty("family_name")
  private String familyName = null;

  @JsonProperty("middle_name")
  private String middleName = null;

  @JsonProperty("nickname")
  private String nickname = null;

  @JsonProperty("preferred_username")
  private String preferredUsername = null;

  @JsonProperty("profile")
  private String profile = null;

  @JsonProperty("picture")
  private String picture = null;

  @JsonProperty("website")
  private String website = null;

  @JsonProperty("email")
  private String email = null;

  @JsonProperty("email_verified")
  private Boolean emailVerified = null;

  @JsonProperty("gender")
  private String gender = null;

  @JsonProperty("birthdate")
  private String birthdate = null;

  @JsonProperty("zoneinfo")
  private String zoneinfo = null;

  @JsonProperty("locale")
  private String locale = null;

  @JsonProperty("phone_number")
  private String phoneNumber = null;

  @JsonProperty("phone_number_verified")
  private Boolean phoneNumberVerified = null;

  @JsonProperty("address")
  private AccessTokenAddress address = null;

  @JsonProperty("updated_at")
  private Long updatedAt = null;

  @JsonProperty("claims_locales")
  private String claimsLocales = null;

  @JsonProperty("acr")
  private String acr = null;

  @JsonProperty("s_hash")
  private String sHash = null;

  @JsonProperty("trusted-certs")
  private List<String> trustedCerts = null;

  @JsonProperty("allowed-origins")
  private List<String> allowedOrigins = null;

  @JsonProperty("realm_access")
  private AccessTokenRealmAccess realmAccess = null;

  @JsonProperty("resource_access")
  private Map<String, AccessTokenRealmAccess> resourceAccess = null;

  @JsonProperty("authorization")
  private AccessTokenAuthorization authorization = null;

  @JsonProperty("cnf")
  private AccessTokenCnf cnf = null;

  @JsonProperty("scope")
  private String scope = null;

  public PolicyEvaluationResponseRpt jti(String jti) {
    this.jti = jti;
    return this;
  }

   /**
   * Get jti
   * @return jti
  **/
  public String getJti() {
    return jti;
  }

  public void setJti(String jti) {
    this.jti = jti;
  }

  public PolicyEvaluationResponseRpt exp(Long exp) {
    this.exp = exp;
    return this;
  }

   /**
   * Get exp
   * @return exp
  **/
  public Long getExp() {
    return exp;
  }

  public void setExp(Long exp) {
    this.exp = exp;
  }

  public PolicyEvaluationResponseRpt nbf(Long nbf) {
    this.nbf = nbf;
    return this;
  }

   /**
   * Get nbf
   * @return nbf
  **/
  public Long getNbf() {
    return nbf;
  }

  public void setNbf(Long nbf) {
    this.nbf = nbf;
  }

  public PolicyEvaluationResponseRpt iat(Long iat) {
    this.iat = iat;
    return this;
  }

   /**
   * Get iat
   * @return iat
  **/
  public Long getIat() {
    return iat;
  }

  public void setIat(Long iat) {
    this.iat = iat;
  }

  public PolicyEvaluationResponseRpt iss(String iss) {
    this.iss = iss;
    return this;
  }

   /**
   * Get iss
   * @return iss
  **/
  public String getIss() {
    return iss;
  }

  public void setIss(String iss) {
    this.iss = iss;
  }

  public PolicyEvaluationResponseRpt sub(String sub) {
    this.sub = sub;
    return this;
  }

   /**
   * Get sub
   * @return sub
  **/
  public String getSub() {
    return sub;
  }

  public void setSub(String sub) {
    this.sub = sub;
  }

  public PolicyEvaluationResponseRpt typ(String typ) {
    this.typ = typ;
    return this;
  }

   /**
   * Get typ
   * @return typ
  **/
  public String getTyp() {
    return typ;
  }

  public void setTyp(String typ) {
    this.typ = typ;
  }

  public PolicyEvaluationResponseRpt azp(String azp) {
    this.azp = azp;
    return this;
  }

   /**
   * Get azp
   * @return azp
  **/
  public String getAzp() {
    return azp;
  }

  public void setAzp(String azp) {
    this.azp = azp;
  }

  public PolicyEvaluationResponseRpt otherClaims(Map<String, Object> otherClaims) {
    this.otherClaims = otherClaims;
    return this;
  }

  public PolicyEvaluationResponseRpt putOtherClaimsItem(String key, Object otherClaimsItem) {
    if (this.otherClaims == null) {
      this.otherClaims = new HashMap<>();
    }
    this.otherClaims.put(key, otherClaimsItem);
    return this;
  }

   /**
   * Get otherClaims
   * @return otherClaims
  **/
  public Map<String, Object> getOtherClaims() {
    return otherClaims;
  }

  public void setOtherClaims(Map<String, Object> otherClaims) {
    this.otherClaims = otherClaims;
  }

  public PolicyEvaluationResponseRpt nonce(String nonce) {
    this.nonce = nonce;
    return this;
  }

   /**
   * Get nonce
   * @return nonce
  **/
  public String getNonce() {
    return nonce;
  }

  public void setNonce(String nonce) {
    this.nonce = nonce;
  }

  public PolicyEvaluationResponseRpt authTime(Long authTime) {
    this.authTime = authTime;
    return this;
  }

   /**
   * Get authTime
   * @return authTime
  **/
  public Long getAuthTime() {
    return authTime;
  }

  public void setAuthTime(Long authTime) {
    this.authTime = authTime;
  }

  public PolicyEvaluationResponseRpt sid(String sid) {
    this.sid = sid;
    return this;
  }

   /**
   * Get sid
   * @return sid
  **/
  public String getSid() {
    return sid;
  }

  public void setSid(String sid) {
    this.sid = sid;
  }

  public PolicyEvaluationResponseRpt atHash(String atHash) {
    this.atHash = atHash;
    return this;
  }

   /**
   * Get atHash
   * @return atHash
  **/
  public String getAtHash() {
    return atHash;
  }

  public void setAtHash(String atHash) {
    this.atHash = atHash;
  }

  public PolicyEvaluationResponseRpt cHash(String cHash) {
    this.cHash = cHash;
    return this;
  }

   /**
   * Get cHash
   * @return cHash
  **/
  public String getCHash() {
    return cHash;
  }

  public void setCHash(String cHash) {
    this.cHash = cHash;
  }

  public PolicyEvaluationResponseRpt name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public PolicyEvaluationResponseRpt givenName(String givenName) {
    this.givenName = givenName;
    return this;
  }

   /**
   * Get givenName
   * @return givenName
  **/
  public String getGivenName() {
    return givenName;
  }

  public void setGivenName(String givenName) {
    this.givenName = givenName;
  }

  public PolicyEvaluationResponseRpt familyName(String familyName) {
    this.familyName = familyName;
    return this;
  }

   /**
   * Get familyName
   * @return familyName
  **/
  public String getFamilyName() {
    return familyName;
  }

  public void setFamilyName(String familyName) {
    this.familyName = familyName;
  }

  public PolicyEvaluationResponseRpt middleName(String middleName) {
    this.middleName = middleName;
    return this;
  }

   /**
   * Get middleName
   * @return middleName
  **/
  public String getMiddleName() {
    return middleName;
  }

  public void setMiddleName(String middleName) {
    this.middleName = middleName;
  }

  public PolicyEvaluationResponseRpt nickname(String nickname) {
    this.nickname = nickname;
    return this;
  }

   /**
   * Get nickname
   * @return nickname
  **/
  public String getNickname() {
    return nickname;
  }

  public void setNickname(String nickname) {
    this.nickname = nickname;
  }

  public PolicyEvaluationResponseRpt preferredUsername(String preferredUsername) {
    this.preferredUsername = preferredUsername;
    return this;
  }

   /**
   * Get preferredUsername
   * @return preferredUsername
  **/
  public String getPreferredUsername() {
    return preferredUsername;
  }

  public void setPreferredUsername(String preferredUsername) {
    this.preferredUsername = preferredUsername;
  }

  public PolicyEvaluationResponseRpt profile(String profile) {
    this.profile = profile;
    return this;
  }

   /**
   * Get profile
   * @return profile
  **/
  public String getProfile() {
    return profile;
  }

  public void setProfile(String profile) {
    this.profile = profile;
  }

  public PolicyEvaluationResponseRpt picture(String picture) {
    this.picture = picture;
    return this;
  }

   /**
   * Get picture
   * @return picture
  **/
  public String getPicture() {
    return picture;
  }

  public void setPicture(String picture) {
    this.picture = picture;
  }

  public PolicyEvaluationResponseRpt website(String website) {
    this.website = website;
    return this;
  }

   /**
   * Get website
   * @return website
  **/
  public String getWebsite() {
    return website;
  }

  public void setWebsite(String website) {
    this.website = website;
  }

  public PolicyEvaluationResponseRpt email(String email) {
    this.email = email;
    return this;
  }

   /**
   * Get email
   * @return email
  **/
  public String getEmail() {
    return email;
  }

  public void setEmail(String email) {
    this.email = email;
  }

  public PolicyEvaluationResponseRpt emailVerified(Boolean emailVerified) {
    this.emailVerified = emailVerified;
    return this;
  }

   /**
   * Get emailVerified
   * @return emailVerified
  **/
  public Boolean isEmailVerified() {
    return emailVerified;
  }

  public void setEmailVerified(Boolean emailVerified) {
    this.emailVerified = emailVerified;
  }

  public PolicyEvaluationResponseRpt gender(String gender) {
    this.gender = gender;
    return this;
  }

   /**
   * Get gender
   * @return gender
  **/
  public String getGender() {
    return gender;
  }

  public void setGender(String gender) {
    this.gender = gender;
  }

  public PolicyEvaluationResponseRpt birthdate(String birthdate) {
    this.birthdate = birthdate;
    return this;
  }

   /**
   * Get birthdate
   * @return birthdate
  **/
  public String getBirthdate() {
    return birthdate;
  }

  public void setBirthdate(String birthdate) {
    this.birthdate = birthdate;
  }

  public PolicyEvaluationResponseRpt zoneinfo(String zoneinfo) {
    this.zoneinfo = zoneinfo;
    return this;
  }

   /**
   * Get zoneinfo
   * @return zoneinfo
  **/
  public String getZoneinfo() {
    return zoneinfo;
  }

  public void setZoneinfo(String zoneinfo) {
    this.zoneinfo = zoneinfo;
  }

  public PolicyEvaluationResponseRpt locale(String locale) {
    this.locale = locale;
    return this;
  }

   /**
   * Get locale
   * @return locale
  **/
  public String getLocale() {
    return locale;
  }

  public void setLocale(String locale) {
    this.locale = locale;
  }

  public PolicyEvaluationResponseRpt phoneNumber(String phoneNumber) {
    this.phoneNumber = phoneNumber;
    return this;
  }

   /**
   * Get phoneNumber
   * @return phoneNumber
  **/
  public String getPhoneNumber() {
    return phoneNumber;
  }

  public void setPhoneNumber(String phoneNumber) {
    this.phoneNumber = phoneNumber;
  }

  public PolicyEvaluationResponseRpt phoneNumberVerified(Boolean phoneNumberVerified) {
    this.phoneNumberVerified = phoneNumberVerified;
    return this;
  }

   /**
   * Get phoneNumberVerified
   * @return phoneNumberVerified
  **/
  public Boolean isPhoneNumberVerified() {
    return phoneNumberVerified;
  }

  public void setPhoneNumberVerified(Boolean phoneNumberVerified) {
    this.phoneNumberVerified = phoneNumberVerified;
  }

  public PolicyEvaluationResponseRpt address(AccessTokenAddress address) {
    this.address = address;
    return this;
  }

   /**
   * Get address
   * @return address
  **/
  public AccessTokenAddress getAddress() {
    return address;
  }

  public void setAddress(AccessTokenAddress address) {
    this.address = address;
  }

  public PolicyEvaluationResponseRpt updatedAt(Long updatedAt) {
    this.updatedAt = updatedAt;
    return this;
  }

   /**
   * Get updatedAt
   * @return updatedAt
  **/
  public Long getUpdatedAt() {
    return updatedAt;
  }

  public void setUpdatedAt(Long updatedAt) {
    this.updatedAt = updatedAt;
  }

  public PolicyEvaluationResponseRpt claimsLocales(String claimsLocales) {
    this.claimsLocales = claimsLocales;
    return this;
  }

   /**
   * Get claimsLocales
   * @return claimsLocales
  **/
  public String getClaimsLocales() {
    return claimsLocales;
  }

  public void setClaimsLocales(String claimsLocales) {
    this.claimsLocales = claimsLocales;
  }

  public PolicyEvaluationResponseRpt acr(String acr) {
    this.acr = acr;
    return this;
  }

   /**
   * Get acr
   * @return acr
  **/
  public String getAcr() {
    return acr;
  }

  public void setAcr(String acr) {
    this.acr = acr;
  }

  public PolicyEvaluationResponseRpt sHash(String sHash) {
    this.sHash = sHash;
    return this;
  }

   /**
   * Get sHash
   * @return sHash
  **/
  public String getSHash() {
    return sHash;
  }

  public void setSHash(String sHash) {
    this.sHash = sHash;
  }

  public PolicyEvaluationResponseRpt trustedCerts(List<String> trustedCerts) {
    this.trustedCerts = trustedCerts;
    return this;
  }

  public PolicyEvaluationResponseRpt addTrustedCertsItem(String trustedCertsItem) {
    if (this.trustedCerts == null) {
      this.trustedCerts = new ArrayList<>();
    }
    this.trustedCerts.add(trustedCertsItem);
    return this;
  }

   /**
   * Get trustedCerts
   * @return trustedCerts
  **/
  public List<String> getTrustedCerts() {
    return trustedCerts;
  }

  public void setTrustedCerts(List<String> trustedCerts) {
    this.trustedCerts = trustedCerts;
  }

  public PolicyEvaluationResponseRpt allowedOrigins(List<String> allowedOrigins) {
    this.allowedOrigins = allowedOrigins;
    return this;
  }

  public PolicyEvaluationResponseRpt addAllowedOriginsItem(String allowedOriginsItem) {
    if (this.allowedOrigins == null) {
      this.allowedOrigins = new ArrayList<>();
    }
    this.allowedOrigins.add(allowedOriginsItem);
    return this;
  }

   /**
   * Get allowedOrigins
   * @return allowedOrigins
  **/
  public List<String> getAllowedOrigins() {
    return allowedOrigins;
  }

  public void setAllowedOrigins(List<String> allowedOrigins) {
    this.allowedOrigins = allowedOrigins;
  }

  public PolicyEvaluationResponseRpt realmAccess(AccessTokenRealmAccess realmAccess) {
    this.realmAccess = realmAccess;
    return this;
  }

   /**
   * Get realmAccess
   * @return realmAccess
  **/
  public AccessTokenRealmAccess getRealmAccess() {
    return realmAccess;
  }

  public void setRealmAccess(AccessTokenRealmAccess realmAccess) {
    this.realmAccess = realmAccess;
  }

  public PolicyEvaluationResponseRpt resourceAccess(Map<String, AccessTokenRealmAccess> resourceAccess) {
    this.resourceAccess = resourceAccess;
    return this;
  }

  public PolicyEvaluationResponseRpt putResourceAccessItem(String key, AccessTokenRealmAccess resourceAccessItem) {
    if (this.resourceAccess == null) {
      this.resourceAccess = new HashMap<>();
    }
    this.resourceAccess.put(key, resourceAccessItem);
    return this;
  }

   /**
   * Get resourceAccess
   * @return resourceAccess
  **/
  public Map<String, AccessTokenRealmAccess> getResourceAccess() {
    return resourceAccess;
  }

  public void setResourceAccess(Map<String, AccessTokenRealmAccess> resourceAccess) {
    this.resourceAccess = resourceAccess;
  }

  public PolicyEvaluationResponseRpt authorization(AccessTokenAuthorization authorization) {
    this.authorization = authorization;
    return this;
  }

   /**
   * Get authorization
   * @return authorization
  **/
  public AccessTokenAuthorization getAuthorization() {
    return authorization;
  }

  public void setAuthorization(AccessTokenAuthorization authorization) {
    this.authorization = authorization;
  }

  public PolicyEvaluationResponseRpt cnf(AccessTokenCnf cnf) {
    this.cnf = cnf;
    return this;
  }

   /**
   * Get cnf
   * @return cnf
  **/
  public AccessTokenCnf getCnf() {
    return cnf;
  }

  public void setCnf(AccessTokenCnf cnf) {
    this.cnf = cnf;
  }

  public PolicyEvaluationResponseRpt scope(String scope) {
    this.scope = scope;
    return this;
  }

   /**
   * Get scope
   * @return scope
  **/
  public String getScope() {
    return scope;
  }

  public void setScope(String scope) {
    this.scope = scope;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PolicyEvaluationResponseRpt policyEvaluationResponseRpt = (PolicyEvaluationResponseRpt) o;
    return Objects.equals(this.jti, policyEvaluationResponseRpt.jti) &&
        Objects.equals(this.exp, policyEvaluationResponseRpt.exp) &&
        Objects.equals(this.nbf, policyEvaluationResponseRpt.nbf) &&
        Objects.equals(this.iat, policyEvaluationResponseRpt.iat) &&
        Objects.equals(this.iss, policyEvaluationResponseRpt.iss) &&
        Objects.equals(this.sub, policyEvaluationResponseRpt.sub) &&
        Objects.equals(this.typ, policyEvaluationResponseRpt.typ) &&
        Objects.equals(this.azp, policyEvaluationResponseRpt.azp) &&
        Objects.equals(this.otherClaims, policyEvaluationResponseRpt.otherClaims) &&
        Objects.equals(this.nonce, policyEvaluationResponseRpt.nonce) &&
        Objects.equals(this.authTime, policyEvaluationResponseRpt.authTime) &&
        Objects.equals(this.sid, policyEvaluationResponseRpt.sid) &&
        Objects.equals(this.atHash, policyEvaluationResponseRpt.atHash) &&
        Objects.equals(this.cHash, policyEvaluationResponseRpt.cHash) &&
        Objects.equals(this.name, policyEvaluationResponseRpt.name) &&
        Objects.equals(this.givenName, policyEvaluationResponseRpt.givenName) &&
        Objects.equals(this.familyName, policyEvaluationResponseRpt.familyName) &&
        Objects.equals(this.middleName, policyEvaluationResponseRpt.middleName) &&
        Objects.equals(this.nickname, policyEvaluationResponseRpt.nickname) &&
        Objects.equals(this.preferredUsername, policyEvaluationResponseRpt.preferredUsername) &&
        Objects.equals(this.profile, policyEvaluationResponseRpt.profile) &&
        Objects.equals(this.picture, policyEvaluationResponseRpt.picture) &&
        Objects.equals(this.website, policyEvaluationResponseRpt.website) &&
        Objects.equals(this.email, policyEvaluationResponseRpt.email) &&
        Objects.equals(this.emailVerified, policyEvaluationResponseRpt.emailVerified) &&
        Objects.equals(this.gender, policyEvaluationResponseRpt.gender) &&
        Objects.equals(this.birthdate, policyEvaluationResponseRpt.birthdate) &&
        Objects.equals(this.zoneinfo, policyEvaluationResponseRpt.zoneinfo) &&
        Objects.equals(this.locale, policyEvaluationResponseRpt.locale) &&
        Objects.equals(this.phoneNumber, policyEvaluationResponseRpt.phoneNumber) &&
        Objects.equals(this.phoneNumberVerified, policyEvaluationResponseRpt.phoneNumberVerified) &&
        Objects.equals(this.address, policyEvaluationResponseRpt.address) &&
        Objects.equals(this.updatedAt, policyEvaluationResponseRpt.updatedAt) &&
        Objects.equals(this.claimsLocales, policyEvaluationResponseRpt.claimsLocales) &&
        Objects.equals(this.acr, policyEvaluationResponseRpt.acr) &&
        Objects.equals(this.sHash, policyEvaluationResponseRpt.sHash) &&
        Objects.equals(this.trustedCerts, policyEvaluationResponseRpt.trustedCerts) &&
        Objects.equals(this.allowedOrigins, policyEvaluationResponseRpt.allowedOrigins) &&
        Objects.equals(this.realmAccess, policyEvaluationResponseRpt.realmAccess) &&
        Objects.equals(this.resourceAccess, policyEvaluationResponseRpt.resourceAccess) &&
        Objects.equals(this.authorization, policyEvaluationResponseRpt.authorization) &&
        Objects.equals(this.cnf, policyEvaluationResponseRpt.cnf) &&
        Objects.equals(this.scope, policyEvaluationResponseRpt.scope);
  }

  @Override
  public int hashCode() {
    return Objects.hash(jti, exp, nbf, iat, iss, sub, typ, azp, otherClaims, nonce, authTime, sid, atHash, cHash, name, givenName, familyName, middleName, nickname, preferredUsername, profile, picture, website, email, emailVerified, gender, birthdate, zoneinfo, locale, phoneNumber, phoneNumberVerified, address, updatedAt, claimsLocales, acr, sHash, trustedCerts, allowedOrigins, realmAccess, resourceAccess, authorization, cnf, scope);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PolicyEvaluationResponseRpt {\n");
    
    sb.append("    jti: ").append(toIndentedString(jti)).append("\n");
    sb.append("    exp: ").append(toIndentedString(exp)).append("\n");
    sb.append("    nbf: ").append(toIndentedString(nbf)).append("\n");
    sb.append("    iat: ").append(toIndentedString(iat)).append("\n");
    sb.append("    iss: ").append(toIndentedString(iss)).append("\n");
    sb.append("    sub: ").append(toIndentedString(sub)).append("\n");
    sb.append("    typ: ").append(toIndentedString(typ)).append("\n");
    sb.append("    azp: ").append(toIndentedString(azp)).append("\n");
    sb.append("    otherClaims: ").append(toIndentedString(otherClaims)).append("\n");
    sb.append("    nonce: ").append(toIndentedString(nonce)).append("\n");
    sb.append("    authTime: ").append(toIndentedString(authTime)).append("\n");
    sb.append("    sid: ").append(toIndentedString(sid)).append("\n");
    sb.append("    atHash: ").append(toIndentedString(atHash)).append("\n");
    sb.append("    cHash: ").append(toIndentedString(cHash)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    givenName: ").append(toIndentedString(givenName)).append("\n");
    sb.append("    familyName: ").append(toIndentedString(familyName)).append("\n");
    sb.append("    middleName: ").append(toIndentedString(middleName)).append("\n");
    sb.append("    nickname: ").append(toIndentedString(nickname)).append("\n");
    sb.append("    preferredUsername: ").append(toIndentedString(preferredUsername)).append("\n");
    sb.append("    profile: ").append(toIndentedString(profile)).append("\n");
    sb.append("    picture: ").append(toIndentedString(picture)).append("\n");
    sb.append("    website: ").append(toIndentedString(website)).append("\n");
    sb.append("    email: ").append(toIndentedString(email)).append("\n");
    sb.append("    emailVerified: ").append(toIndentedString(emailVerified)).append("\n");
    sb.append("    gender: ").append(toIndentedString(gender)).append("\n");
    sb.append("    birthdate: ").append(toIndentedString(birthdate)).append("\n");
    sb.append("    zoneinfo: ").append(toIndentedString(zoneinfo)).append("\n");
    sb.append("    locale: ").append(toIndentedString(locale)).append("\n");
    sb.append("    phoneNumber: ").append(toIndentedString(phoneNumber)).append("\n");
    sb.append("    phoneNumberVerified: ").append(toIndentedString(phoneNumberVerified)).append("\n");
    sb.append("    address: ").append(toIndentedString(address)).append("\n");
    sb.append("    updatedAt: ").append(toIndentedString(updatedAt)).append("\n");
    sb.append("    claimsLocales: ").append(toIndentedString(claimsLocales)).append("\n");
    sb.append("    acr: ").append(toIndentedString(acr)).append("\n");
    sb.append("    sHash: ").append(toIndentedString(sHash)).append("\n");
    sb.append("    trustedCerts: ").append(toIndentedString(trustedCerts)).append("\n");
    sb.append("    allowedOrigins: ").append(toIndentedString(allowedOrigins)).append("\n");
    sb.append("    realmAccess: ").append(toIndentedString(realmAccess)).append("\n");
    sb.append("    resourceAccess: ").append(toIndentedString(resourceAccess)).append("\n");
    sb.append("    authorization: ").append(toIndentedString(authorization)).append("\n");
    sb.append("    cnf: ").append(toIndentedString(cnf)).append("\n");
    sb.append("    scope: ").append(toIndentedString(scope)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
