/*
 * Keycloak Admin REST API
 * This is a REST API reference for the Keycloak Admin REST API.
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.keycloak.www.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * ProtocolMapperEvaluationRepresentation
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-03-11T12:00:50.005853600+07:00[Asia/Bangkok]")

public class ProtocolMapperEvaluationRepresentation {
  @JsonProperty("mapperId")
  private String mapperId = null;

  @JsonProperty("mapperName")
  private String mapperName = null;

  @JsonProperty("containerId")
  private String containerId = null;

  @JsonProperty("containerName")
  private String containerName = null;

  @JsonProperty("containerType")
  private String containerType = null;

  @JsonProperty("protocolMapper")
  private String protocolMapper = null;

  public ProtocolMapperEvaluationRepresentation mapperId(String mapperId) {
    this.mapperId = mapperId;
    return this;
  }

   /**
   * Get mapperId
   * @return mapperId
  **/
  public String getMapperId() {
    return mapperId;
  }

  public void setMapperId(String mapperId) {
    this.mapperId = mapperId;
  }

  public ProtocolMapperEvaluationRepresentation mapperName(String mapperName) {
    this.mapperName = mapperName;
    return this;
  }

   /**
   * Get mapperName
   * @return mapperName
  **/
  public String getMapperName() {
    return mapperName;
  }

  public void setMapperName(String mapperName) {
    this.mapperName = mapperName;
  }

  public ProtocolMapperEvaluationRepresentation containerId(String containerId) {
    this.containerId = containerId;
    return this;
  }

   /**
   * Get containerId
   * @return containerId
  **/
  public String getContainerId() {
    return containerId;
  }

  public void setContainerId(String containerId) {
    this.containerId = containerId;
  }

  public ProtocolMapperEvaluationRepresentation containerName(String containerName) {
    this.containerName = containerName;
    return this;
  }

   /**
   * Get containerName
   * @return containerName
  **/
  public String getContainerName() {
    return containerName;
  }

  public void setContainerName(String containerName) {
    this.containerName = containerName;
  }

  public ProtocolMapperEvaluationRepresentation containerType(String containerType) {
    this.containerType = containerType;
    return this;
  }

   /**
   * Get containerType
   * @return containerType
  **/
  public String getContainerType() {
    return containerType;
  }

  public void setContainerType(String containerType) {
    this.containerType = containerType;
  }

  public ProtocolMapperEvaluationRepresentation protocolMapper(String protocolMapper) {
    this.protocolMapper = protocolMapper;
    return this;
  }

   /**
   * Get protocolMapper
   * @return protocolMapper
  **/
  public String getProtocolMapper() {
    return protocolMapper;
  }

  public void setProtocolMapper(String protocolMapper) {
    this.protocolMapper = protocolMapper;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ProtocolMapperEvaluationRepresentation protocolMapperEvaluationRepresentation = (ProtocolMapperEvaluationRepresentation) o;
    return Objects.equals(this.mapperId, protocolMapperEvaluationRepresentation.mapperId) &&
        Objects.equals(this.mapperName, protocolMapperEvaluationRepresentation.mapperName) &&
        Objects.equals(this.containerId, protocolMapperEvaluationRepresentation.containerId) &&
        Objects.equals(this.containerName, protocolMapperEvaluationRepresentation.containerName) &&
        Objects.equals(this.containerType, protocolMapperEvaluationRepresentation.containerType) &&
        Objects.equals(this.protocolMapper, protocolMapperEvaluationRepresentation.protocolMapper);
  }

  @Override
  public int hashCode() {
    return Objects.hash(mapperId, mapperName, containerId, containerName, containerType, protocolMapper);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ProtocolMapperEvaluationRepresentation {\n");
    
    sb.append("    mapperId: ").append(toIndentedString(mapperId)).append("\n");
    sb.append("    mapperName: ").append(toIndentedString(mapperName)).append("\n");
    sb.append("    containerId: ").append(toIndentedString(containerId)).append("\n");
    sb.append("    containerName: ").append(toIndentedString(containerName)).append("\n");
    sb.append("    containerType: ").append(toIndentedString(containerType)).append("\n");
    sb.append("    protocolMapper: ").append(toIndentedString(protocolMapper)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
