/*
 * Keycloak Admin REST API
 * This is a REST API reference for the Keycloak Admin REST API.
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.keycloak.www.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.keycloak.www.client.AdminrealmsAdminPermissionsClientAuthorizationSettings;
import org.keycloak.www.client.AdminrealmsAdminPermissionsClientProtocolMappers;
/**
 * RealmClientsBody
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-03-11T12:00:50.005853600+07:00[Asia/Bangkok]")

public class RealmClientsBody {
  @JsonProperty("id")
  private String id = null;

  @JsonProperty("clientId")
  private String clientId = null;

  @JsonProperty("name")
  private String name = null;

  @JsonProperty("description")
  private String description = null;

  @JsonProperty("type")
  private String type = null;

  @JsonProperty("rootUrl")
  private String rootUrl = null;

  @JsonProperty("adminUrl")
  private String adminUrl = null;

  @JsonProperty("baseUrl")
  private String baseUrl = null;

  @JsonProperty("surrogateAuthRequired")
  private Boolean surrogateAuthRequired = null;

  @JsonProperty("enabled")
  private Boolean enabled = null;

  @JsonProperty("alwaysDisplayInConsole")
  private Boolean alwaysDisplayInConsole = null;

  @JsonProperty("clientAuthenticatorType")
  private String clientAuthenticatorType = null;

  @JsonProperty("secret")
  private String secret = null;

  @JsonProperty("registrationAccessToken")
  private String registrationAccessToken = null;

  @JsonProperty("defaultRoles")
  private List<String> defaultRoles = null;

  @JsonProperty("redirectUris")
  private List<String> redirectUris = null;

  @JsonProperty("webOrigins")
  private List<String> webOrigins = null;

  @JsonProperty("notBefore")
  private Integer notBefore = null;

  @JsonProperty("bearerOnly")
  private Boolean bearerOnly = null;

  @JsonProperty("consentRequired")
  private Boolean consentRequired = null;

  @JsonProperty("standardFlowEnabled")
  private Boolean standardFlowEnabled = null;

  @JsonProperty("implicitFlowEnabled")
  private Boolean implicitFlowEnabled = null;

  @JsonProperty("directAccessGrantsEnabled")
  private Boolean directAccessGrantsEnabled = null;

  @JsonProperty("serviceAccountsEnabled")
  private Boolean serviceAccountsEnabled = null;

  @JsonProperty("authorizationServicesEnabled")
  private Boolean authorizationServicesEnabled = null;

  @JsonProperty("directGrantsOnly")
  private Boolean directGrantsOnly = null;

  @JsonProperty("publicClient")
  private Boolean publicClient = null;

  @JsonProperty("frontchannelLogout")
  private Boolean frontchannelLogout = null;

  @JsonProperty("protocol")
  private String protocol = null;

  @JsonProperty("attributes")
  private Map<String, String> attributes = null;

  @JsonProperty("authenticationFlowBindingOverrides")
  private Map<String, String> authenticationFlowBindingOverrides = null;

  @JsonProperty("fullScopeAllowed")
  private Boolean fullScopeAllowed = null;

  @JsonProperty("nodeReRegistrationTimeout")
  private Integer nodeReRegistrationTimeout = null;

  @JsonProperty("registeredNodes")
  private Map<String, Integer> registeredNodes = null;

  @JsonProperty("protocolMappers")
  private List<AdminrealmsAdminPermissionsClientProtocolMappers> protocolMappers = null;

  @JsonProperty("clientTemplate")
  private String clientTemplate = null;

  @JsonProperty("useTemplateConfig")
  private Boolean useTemplateConfig = null;

  @JsonProperty("useTemplateScope")
  private Boolean useTemplateScope = null;

  @JsonProperty("useTemplateMappers")
  private Boolean useTemplateMappers = null;

  @JsonProperty("defaultClientScopes")
  private List<String> defaultClientScopes = null;

  @JsonProperty("optionalClientScopes")
  private List<String> optionalClientScopes = null;

  @JsonProperty("authorizationSettings")
  private AdminrealmsAdminPermissionsClientAuthorizationSettings authorizationSettings = null;

  @JsonProperty("access")
  private Map<String, Boolean> access = null;

  @JsonProperty("origin")
  private String origin = null;

  public RealmClientsBody id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public RealmClientsBody clientId(String clientId) {
    this.clientId = clientId;
    return this;
  }

   /**
   * Get clientId
   * @return clientId
  **/
  public String getClientId() {
    return clientId;
  }

  public void setClientId(String clientId) {
    this.clientId = clientId;
  }

  public RealmClientsBody name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public RealmClientsBody description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public RealmClientsBody type(String type) {
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  public String getType() {
    return type;
  }

  public void setType(String type) {
    this.type = type;
  }

  public RealmClientsBody rootUrl(String rootUrl) {
    this.rootUrl = rootUrl;
    return this;
  }

   /**
   * Get rootUrl
   * @return rootUrl
  **/
  public String getRootUrl() {
    return rootUrl;
  }

  public void setRootUrl(String rootUrl) {
    this.rootUrl = rootUrl;
  }

  public RealmClientsBody adminUrl(String adminUrl) {
    this.adminUrl = adminUrl;
    return this;
  }

   /**
   * Get adminUrl
   * @return adminUrl
  **/
  public String getAdminUrl() {
    return adminUrl;
  }

  public void setAdminUrl(String adminUrl) {
    this.adminUrl = adminUrl;
  }

  public RealmClientsBody baseUrl(String baseUrl) {
    this.baseUrl = baseUrl;
    return this;
  }

   /**
   * Get baseUrl
   * @return baseUrl
  **/
  public String getBaseUrl() {
    return baseUrl;
  }

  public void setBaseUrl(String baseUrl) {
    this.baseUrl = baseUrl;
  }

  public RealmClientsBody surrogateAuthRequired(Boolean surrogateAuthRequired) {
    this.surrogateAuthRequired = surrogateAuthRequired;
    return this;
  }

   /**
   * Get surrogateAuthRequired
   * @return surrogateAuthRequired
  **/
  public Boolean isSurrogateAuthRequired() {
    return surrogateAuthRequired;
  }

  public void setSurrogateAuthRequired(Boolean surrogateAuthRequired) {
    this.surrogateAuthRequired = surrogateAuthRequired;
  }

  public RealmClientsBody enabled(Boolean enabled) {
    this.enabled = enabled;
    return this;
  }

   /**
   * Get enabled
   * @return enabled
  **/
  public Boolean isEnabled() {
    return enabled;
  }

  public void setEnabled(Boolean enabled) {
    this.enabled = enabled;
  }

  public RealmClientsBody alwaysDisplayInConsole(Boolean alwaysDisplayInConsole) {
    this.alwaysDisplayInConsole = alwaysDisplayInConsole;
    return this;
  }

   /**
   * Get alwaysDisplayInConsole
   * @return alwaysDisplayInConsole
  **/
  public Boolean isAlwaysDisplayInConsole() {
    return alwaysDisplayInConsole;
  }

  public void setAlwaysDisplayInConsole(Boolean alwaysDisplayInConsole) {
    this.alwaysDisplayInConsole = alwaysDisplayInConsole;
  }

  public RealmClientsBody clientAuthenticatorType(String clientAuthenticatorType) {
    this.clientAuthenticatorType = clientAuthenticatorType;
    return this;
  }

   /**
   * Get clientAuthenticatorType
   * @return clientAuthenticatorType
  **/
  public String getClientAuthenticatorType() {
    return clientAuthenticatorType;
  }

  public void setClientAuthenticatorType(String clientAuthenticatorType) {
    this.clientAuthenticatorType = clientAuthenticatorType;
  }

  public RealmClientsBody secret(String secret) {
    this.secret = secret;
    return this;
  }

   /**
   * Get secret
   * @return secret
  **/
  public String getSecret() {
    return secret;
  }

  public void setSecret(String secret) {
    this.secret = secret;
  }

  public RealmClientsBody registrationAccessToken(String registrationAccessToken) {
    this.registrationAccessToken = registrationAccessToken;
    return this;
  }

   /**
   * Get registrationAccessToken
   * @return registrationAccessToken
  **/
  public String getRegistrationAccessToken() {
    return registrationAccessToken;
  }

  public void setRegistrationAccessToken(String registrationAccessToken) {
    this.registrationAccessToken = registrationAccessToken;
  }

  public RealmClientsBody defaultRoles(List<String> defaultRoles) {
    this.defaultRoles = defaultRoles;
    return this;
  }

  public RealmClientsBody addDefaultRolesItem(String defaultRolesItem) {
    if (this.defaultRoles == null) {
      this.defaultRoles = new ArrayList<>();
    }
    this.defaultRoles.add(defaultRolesItem);
    return this;
  }

   /**
   * Get defaultRoles
   * @return defaultRoles
  **/
  public List<String> getDefaultRoles() {
    return defaultRoles;
  }

  public void setDefaultRoles(List<String> defaultRoles) {
    this.defaultRoles = defaultRoles;
  }

  public RealmClientsBody redirectUris(List<String> redirectUris) {
    this.redirectUris = redirectUris;
    return this;
  }

  public RealmClientsBody addRedirectUrisItem(String redirectUrisItem) {
    if (this.redirectUris == null) {
      this.redirectUris = new ArrayList<>();
    }
    this.redirectUris.add(redirectUrisItem);
    return this;
  }

   /**
   * Get redirectUris
   * @return redirectUris
  **/
  public List<String> getRedirectUris() {
    return redirectUris;
  }

  public void setRedirectUris(List<String> redirectUris) {
    this.redirectUris = redirectUris;
  }

  public RealmClientsBody webOrigins(List<String> webOrigins) {
    this.webOrigins = webOrigins;
    return this;
  }

  public RealmClientsBody addWebOriginsItem(String webOriginsItem) {
    if (this.webOrigins == null) {
      this.webOrigins = new ArrayList<>();
    }
    this.webOrigins.add(webOriginsItem);
    return this;
  }

   /**
   * Get webOrigins
   * @return webOrigins
  **/
  public List<String> getWebOrigins() {
    return webOrigins;
  }

  public void setWebOrigins(List<String> webOrigins) {
    this.webOrigins = webOrigins;
  }

  public RealmClientsBody notBefore(Integer notBefore) {
    this.notBefore = notBefore;
    return this;
  }

   /**
   * Get notBefore
   * @return notBefore
  **/
  public Integer getNotBefore() {
    return notBefore;
  }

  public void setNotBefore(Integer notBefore) {
    this.notBefore = notBefore;
  }

  public RealmClientsBody bearerOnly(Boolean bearerOnly) {
    this.bearerOnly = bearerOnly;
    return this;
  }

   /**
   * Get bearerOnly
   * @return bearerOnly
  **/
  public Boolean isBearerOnly() {
    return bearerOnly;
  }

  public void setBearerOnly(Boolean bearerOnly) {
    this.bearerOnly = bearerOnly;
  }

  public RealmClientsBody consentRequired(Boolean consentRequired) {
    this.consentRequired = consentRequired;
    return this;
  }

   /**
   * Get consentRequired
   * @return consentRequired
  **/
  public Boolean isConsentRequired() {
    return consentRequired;
  }

  public void setConsentRequired(Boolean consentRequired) {
    this.consentRequired = consentRequired;
  }

  public RealmClientsBody standardFlowEnabled(Boolean standardFlowEnabled) {
    this.standardFlowEnabled = standardFlowEnabled;
    return this;
  }

   /**
   * Get standardFlowEnabled
   * @return standardFlowEnabled
  **/
  public Boolean isStandardFlowEnabled() {
    return standardFlowEnabled;
  }

  public void setStandardFlowEnabled(Boolean standardFlowEnabled) {
    this.standardFlowEnabled = standardFlowEnabled;
  }

  public RealmClientsBody implicitFlowEnabled(Boolean implicitFlowEnabled) {
    this.implicitFlowEnabled = implicitFlowEnabled;
    return this;
  }

   /**
   * Get implicitFlowEnabled
   * @return implicitFlowEnabled
  **/
  public Boolean isImplicitFlowEnabled() {
    return implicitFlowEnabled;
  }

  public void setImplicitFlowEnabled(Boolean implicitFlowEnabled) {
    this.implicitFlowEnabled = implicitFlowEnabled;
  }

  public RealmClientsBody directAccessGrantsEnabled(Boolean directAccessGrantsEnabled) {
    this.directAccessGrantsEnabled = directAccessGrantsEnabled;
    return this;
  }

   /**
   * Get directAccessGrantsEnabled
   * @return directAccessGrantsEnabled
  **/
  public Boolean isDirectAccessGrantsEnabled() {
    return directAccessGrantsEnabled;
  }

  public void setDirectAccessGrantsEnabled(Boolean directAccessGrantsEnabled) {
    this.directAccessGrantsEnabled = directAccessGrantsEnabled;
  }

  public RealmClientsBody serviceAccountsEnabled(Boolean serviceAccountsEnabled) {
    this.serviceAccountsEnabled = serviceAccountsEnabled;
    return this;
  }

   /**
   * Get serviceAccountsEnabled
   * @return serviceAccountsEnabled
  **/
  public Boolean isServiceAccountsEnabled() {
    return serviceAccountsEnabled;
  }

  public void setServiceAccountsEnabled(Boolean serviceAccountsEnabled) {
    this.serviceAccountsEnabled = serviceAccountsEnabled;
  }

  public RealmClientsBody authorizationServicesEnabled(Boolean authorizationServicesEnabled) {
    this.authorizationServicesEnabled = authorizationServicesEnabled;
    return this;
  }

   /**
   * Get authorizationServicesEnabled
   * @return authorizationServicesEnabled
  **/
  public Boolean isAuthorizationServicesEnabled() {
    return authorizationServicesEnabled;
  }

  public void setAuthorizationServicesEnabled(Boolean authorizationServicesEnabled) {
    this.authorizationServicesEnabled = authorizationServicesEnabled;
  }

  public RealmClientsBody directGrantsOnly(Boolean directGrantsOnly) {
    this.directGrantsOnly = directGrantsOnly;
    return this;
  }

   /**
   * Get directGrantsOnly
   * @return directGrantsOnly
  **/
  public Boolean isDirectGrantsOnly() {
    return directGrantsOnly;
  }

  public void setDirectGrantsOnly(Boolean directGrantsOnly) {
    this.directGrantsOnly = directGrantsOnly;
  }

  public RealmClientsBody publicClient(Boolean publicClient) {
    this.publicClient = publicClient;
    return this;
  }

   /**
   * Get publicClient
   * @return publicClient
  **/
  public Boolean isPublicClient() {
    return publicClient;
  }

  public void setPublicClient(Boolean publicClient) {
    this.publicClient = publicClient;
  }

  public RealmClientsBody frontchannelLogout(Boolean frontchannelLogout) {
    this.frontchannelLogout = frontchannelLogout;
    return this;
  }

   /**
   * Get frontchannelLogout
   * @return frontchannelLogout
  **/
  public Boolean isFrontchannelLogout() {
    return frontchannelLogout;
  }

  public void setFrontchannelLogout(Boolean frontchannelLogout) {
    this.frontchannelLogout = frontchannelLogout;
  }

  public RealmClientsBody protocol(String protocol) {
    this.protocol = protocol;
    return this;
  }

   /**
   * Get protocol
   * @return protocol
  **/
  public String getProtocol() {
    return protocol;
  }

  public void setProtocol(String protocol) {
    this.protocol = protocol;
  }

  public RealmClientsBody attributes(Map<String, String> attributes) {
    this.attributes = attributes;
    return this;
  }

  public RealmClientsBody putAttributesItem(String key, String attributesItem) {
    if (this.attributes == null) {
      this.attributes = new HashMap<>();
    }
    this.attributes.put(key, attributesItem);
    return this;
  }

   /**
   * Get attributes
   * @return attributes
  **/
  public Map<String, String> getAttributes() {
    return attributes;
  }

  public void setAttributes(Map<String, String> attributes) {
    this.attributes = attributes;
  }

  public RealmClientsBody authenticationFlowBindingOverrides(Map<String, String> authenticationFlowBindingOverrides) {
    this.authenticationFlowBindingOverrides = authenticationFlowBindingOverrides;
    return this;
  }

  public RealmClientsBody putAuthenticationFlowBindingOverridesItem(String key, String authenticationFlowBindingOverridesItem) {
    if (this.authenticationFlowBindingOverrides == null) {
      this.authenticationFlowBindingOverrides = new HashMap<>();
    }
    this.authenticationFlowBindingOverrides.put(key, authenticationFlowBindingOverridesItem);
    return this;
  }

   /**
   * Get authenticationFlowBindingOverrides
   * @return authenticationFlowBindingOverrides
  **/
  public Map<String, String> getAuthenticationFlowBindingOverrides() {
    return authenticationFlowBindingOverrides;
  }

  public void setAuthenticationFlowBindingOverrides(Map<String, String> authenticationFlowBindingOverrides) {
    this.authenticationFlowBindingOverrides = authenticationFlowBindingOverrides;
  }

  public RealmClientsBody fullScopeAllowed(Boolean fullScopeAllowed) {
    this.fullScopeAllowed = fullScopeAllowed;
    return this;
  }

   /**
   * Get fullScopeAllowed
   * @return fullScopeAllowed
  **/
  public Boolean isFullScopeAllowed() {
    return fullScopeAllowed;
  }

  public void setFullScopeAllowed(Boolean fullScopeAllowed) {
    this.fullScopeAllowed = fullScopeAllowed;
  }

  public RealmClientsBody nodeReRegistrationTimeout(Integer nodeReRegistrationTimeout) {
    this.nodeReRegistrationTimeout = nodeReRegistrationTimeout;
    return this;
  }

   /**
   * Get nodeReRegistrationTimeout
   * @return nodeReRegistrationTimeout
  **/
  public Integer getNodeReRegistrationTimeout() {
    return nodeReRegistrationTimeout;
  }

  public void setNodeReRegistrationTimeout(Integer nodeReRegistrationTimeout) {
    this.nodeReRegistrationTimeout = nodeReRegistrationTimeout;
  }

  public RealmClientsBody registeredNodes(Map<String, Integer> registeredNodes) {
    this.registeredNodes = registeredNodes;
    return this;
  }

  public RealmClientsBody putRegisteredNodesItem(String key, Integer registeredNodesItem) {
    if (this.registeredNodes == null) {
      this.registeredNodes = new HashMap<>();
    }
    this.registeredNodes.put(key, registeredNodesItem);
    return this;
  }

   /**
   * Get registeredNodes
   * @return registeredNodes
  **/
  public Map<String, Integer> getRegisteredNodes() {
    return registeredNodes;
  }

  public void setRegisteredNodes(Map<String, Integer> registeredNodes) {
    this.registeredNodes = registeredNodes;
  }

  public RealmClientsBody protocolMappers(List<AdminrealmsAdminPermissionsClientProtocolMappers> protocolMappers) {
    this.protocolMappers = protocolMappers;
    return this;
  }

  public RealmClientsBody addProtocolMappersItem(AdminrealmsAdminPermissionsClientProtocolMappers protocolMappersItem) {
    if (this.protocolMappers == null) {
      this.protocolMappers = new ArrayList<>();
    }
    this.protocolMappers.add(protocolMappersItem);
    return this;
  }

   /**
   * Get protocolMappers
   * @return protocolMappers
  **/
  public List<AdminrealmsAdminPermissionsClientProtocolMappers> getProtocolMappers() {
    return protocolMappers;
  }

  public void setProtocolMappers(List<AdminrealmsAdminPermissionsClientProtocolMappers> protocolMappers) {
    this.protocolMappers = protocolMappers;
  }

  public RealmClientsBody clientTemplate(String clientTemplate) {
    this.clientTemplate = clientTemplate;
    return this;
  }

   /**
   * Get clientTemplate
   * @return clientTemplate
  **/
  public String getClientTemplate() {
    return clientTemplate;
  }

  public void setClientTemplate(String clientTemplate) {
    this.clientTemplate = clientTemplate;
  }

  public RealmClientsBody useTemplateConfig(Boolean useTemplateConfig) {
    this.useTemplateConfig = useTemplateConfig;
    return this;
  }

   /**
   * Get useTemplateConfig
   * @return useTemplateConfig
  **/
  public Boolean isUseTemplateConfig() {
    return useTemplateConfig;
  }

  public void setUseTemplateConfig(Boolean useTemplateConfig) {
    this.useTemplateConfig = useTemplateConfig;
  }

  public RealmClientsBody useTemplateScope(Boolean useTemplateScope) {
    this.useTemplateScope = useTemplateScope;
    return this;
  }

   /**
   * Get useTemplateScope
   * @return useTemplateScope
  **/
  public Boolean isUseTemplateScope() {
    return useTemplateScope;
  }

  public void setUseTemplateScope(Boolean useTemplateScope) {
    this.useTemplateScope = useTemplateScope;
  }

  public RealmClientsBody useTemplateMappers(Boolean useTemplateMappers) {
    this.useTemplateMappers = useTemplateMappers;
    return this;
  }

   /**
   * Get useTemplateMappers
   * @return useTemplateMappers
  **/
  public Boolean isUseTemplateMappers() {
    return useTemplateMappers;
  }

  public void setUseTemplateMappers(Boolean useTemplateMappers) {
    this.useTemplateMappers = useTemplateMappers;
  }

  public RealmClientsBody defaultClientScopes(List<String> defaultClientScopes) {
    this.defaultClientScopes = defaultClientScopes;
    return this;
  }

  public RealmClientsBody addDefaultClientScopesItem(String defaultClientScopesItem) {
    if (this.defaultClientScopes == null) {
      this.defaultClientScopes = new ArrayList<>();
    }
    this.defaultClientScopes.add(defaultClientScopesItem);
    return this;
  }

   /**
   * Get defaultClientScopes
   * @return defaultClientScopes
  **/
  public List<String> getDefaultClientScopes() {
    return defaultClientScopes;
  }

  public void setDefaultClientScopes(List<String> defaultClientScopes) {
    this.defaultClientScopes = defaultClientScopes;
  }

  public RealmClientsBody optionalClientScopes(List<String> optionalClientScopes) {
    this.optionalClientScopes = optionalClientScopes;
    return this;
  }

  public RealmClientsBody addOptionalClientScopesItem(String optionalClientScopesItem) {
    if (this.optionalClientScopes == null) {
      this.optionalClientScopes = new ArrayList<>();
    }
    this.optionalClientScopes.add(optionalClientScopesItem);
    return this;
  }

   /**
   * Get optionalClientScopes
   * @return optionalClientScopes
  **/
  public List<String> getOptionalClientScopes() {
    return optionalClientScopes;
  }

  public void setOptionalClientScopes(List<String> optionalClientScopes) {
    this.optionalClientScopes = optionalClientScopes;
  }

  public RealmClientsBody authorizationSettings(AdminrealmsAdminPermissionsClientAuthorizationSettings authorizationSettings) {
    this.authorizationSettings = authorizationSettings;
    return this;
  }

   /**
   * Get authorizationSettings
   * @return authorizationSettings
  **/
  public AdminrealmsAdminPermissionsClientAuthorizationSettings getAuthorizationSettings() {
    return authorizationSettings;
  }

  public void setAuthorizationSettings(AdminrealmsAdminPermissionsClientAuthorizationSettings authorizationSettings) {
    this.authorizationSettings = authorizationSettings;
  }

  public RealmClientsBody access(Map<String, Boolean> access) {
    this.access = access;
    return this;
  }

  public RealmClientsBody putAccessItem(String key, Boolean accessItem) {
    if (this.access == null) {
      this.access = new HashMap<>();
    }
    this.access.put(key, accessItem);
    return this;
  }

   /**
   * Get access
   * @return access
  **/
  public Map<String, Boolean> getAccess() {
    return access;
  }

  public void setAccess(Map<String, Boolean> access) {
    this.access = access;
  }

  public RealmClientsBody origin(String origin) {
    this.origin = origin;
    return this;
  }

   /**
   * Get origin
   * @return origin
  **/
  public String getOrigin() {
    return origin;
  }

  public void setOrigin(String origin) {
    this.origin = origin;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RealmClientsBody realmClientsBody = (RealmClientsBody) o;
    return Objects.equals(this.id, realmClientsBody.id) &&
        Objects.equals(this.clientId, realmClientsBody.clientId) &&
        Objects.equals(this.name, realmClientsBody.name) &&
        Objects.equals(this.description, realmClientsBody.description) &&
        Objects.equals(this.type, realmClientsBody.type) &&
        Objects.equals(this.rootUrl, realmClientsBody.rootUrl) &&
        Objects.equals(this.adminUrl, realmClientsBody.adminUrl) &&
        Objects.equals(this.baseUrl, realmClientsBody.baseUrl) &&
        Objects.equals(this.surrogateAuthRequired, realmClientsBody.surrogateAuthRequired) &&
        Objects.equals(this.enabled, realmClientsBody.enabled) &&
        Objects.equals(this.alwaysDisplayInConsole, realmClientsBody.alwaysDisplayInConsole) &&
        Objects.equals(this.clientAuthenticatorType, realmClientsBody.clientAuthenticatorType) &&
        Objects.equals(this.secret, realmClientsBody.secret) &&
        Objects.equals(this.registrationAccessToken, realmClientsBody.registrationAccessToken) &&
        Objects.equals(this.defaultRoles, realmClientsBody.defaultRoles) &&
        Objects.equals(this.redirectUris, realmClientsBody.redirectUris) &&
        Objects.equals(this.webOrigins, realmClientsBody.webOrigins) &&
        Objects.equals(this.notBefore, realmClientsBody.notBefore) &&
        Objects.equals(this.bearerOnly, realmClientsBody.bearerOnly) &&
        Objects.equals(this.consentRequired, realmClientsBody.consentRequired) &&
        Objects.equals(this.standardFlowEnabled, realmClientsBody.standardFlowEnabled) &&
        Objects.equals(this.implicitFlowEnabled, realmClientsBody.implicitFlowEnabled) &&
        Objects.equals(this.directAccessGrantsEnabled, realmClientsBody.directAccessGrantsEnabled) &&
        Objects.equals(this.serviceAccountsEnabled, realmClientsBody.serviceAccountsEnabled) &&
        Objects.equals(this.authorizationServicesEnabled, realmClientsBody.authorizationServicesEnabled) &&
        Objects.equals(this.directGrantsOnly, realmClientsBody.directGrantsOnly) &&
        Objects.equals(this.publicClient, realmClientsBody.publicClient) &&
        Objects.equals(this.frontchannelLogout, realmClientsBody.frontchannelLogout) &&
        Objects.equals(this.protocol, realmClientsBody.protocol) &&
        Objects.equals(this.attributes, realmClientsBody.attributes) &&
        Objects.equals(this.authenticationFlowBindingOverrides, realmClientsBody.authenticationFlowBindingOverrides) &&
        Objects.equals(this.fullScopeAllowed, realmClientsBody.fullScopeAllowed) &&
        Objects.equals(this.nodeReRegistrationTimeout, realmClientsBody.nodeReRegistrationTimeout) &&
        Objects.equals(this.registeredNodes, realmClientsBody.registeredNodes) &&
        Objects.equals(this.protocolMappers, realmClientsBody.protocolMappers) &&
        Objects.equals(this.clientTemplate, realmClientsBody.clientTemplate) &&
        Objects.equals(this.useTemplateConfig, realmClientsBody.useTemplateConfig) &&
        Objects.equals(this.useTemplateScope, realmClientsBody.useTemplateScope) &&
        Objects.equals(this.useTemplateMappers, realmClientsBody.useTemplateMappers) &&
        Objects.equals(this.defaultClientScopes, realmClientsBody.defaultClientScopes) &&
        Objects.equals(this.optionalClientScopes, realmClientsBody.optionalClientScopes) &&
        Objects.equals(this.authorizationSettings, realmClientsBody.authorizationSettings) &&
        Objects.equals(this.access, realmClientsBody.access) &&
        Objects.equals(this.origin, realmClientsBody.origin);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, clientId, name, description, type, rootUrl, adminUrl, baseUrl, surrogateAuthRequired, enabled, alwaysDisplayInConsole, clientAuthenticatorType, secret, registrationAccessToken, defaultRoles, redirectUris, webOrigins, notBefore, bearerOnly, consentRequired, standardFlowEnabled, implicitFlowEnabled, directAccessGrantsEnabled, serviceAccountsEnabled, authorizationServicesEnabled, directGrantsOnly, publicClient, frontchannelLogout, protocol, attributes, authenticationFlowBindingOverrides, fullScopeAllowed, nodeReRegistrationTimeout, registeredNodes, protocolMappers, clientTemplate, useTemplateConfig, useTemplateScope, useTemplateMappers, defaultClientScopes, optionalClientScopes, authorizationSettings, access, origin);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RealmClientsBody {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    clientId: ").append(toIndentedString(clientId)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    rootUrl: ").append(toIndentedString(rootUrl)).append("\n");
    sb.append("    adminUrl: ").append(toIndentedString(adminUrl)).append("\n");
    sb.append("    baseUrl: ").append(toIndentedString(baseUrl)).append("\n");
    sb.append("    surrogateAuthRequired: ").append(toIndentedString(surrogateAuthRequired)).append("\n");
    sb.append("    enabled: ").append(toIndentedString(enabled)).append("\n");
    sb.append("    alwaysDisplayInConsole: ").append(toIndentedString(alwaysDisplayInConsole)).append("\n");
    sb.append("    clientAuthenticatorType: ").append(toIndentedString(clientAuthenticatorType)).append("\n");
    sb.append("    secret: ").append(toIndentedString(secret)).append("\n");
    sb.append("    registrationAccessToken: ").append(toIndentedString(registrationAccessToken)).append("\n");
    sb.append("    defaultRoles: ").append(toIndentedString(defaultRoles)).append("\n");
    sb.append("    redirectUris: ").append(toIndentedString(redirectUris)).append("\n");
    sb.append("    webOrigins: ").append(toIndentedString(webOrigins)).append("\n");
    sb.append("    notBefore: ").append(toIndentedString(notBefore)).append("\n");
    sb.append("    bearerOnly: ").append(toIndentedString(bearerOnly)).append("\n");
    sb.append("    consentRequired: ").append(toIndentedString(consentRequired)).append("\n");
    sb.append("    standardFlowEnabled: ").append(toIndentedString(standardFlowEnabled)).append("\n");
    sb.append("    implicitFlowEnabled: ").append(toIndentedString(implicitFlowEnabled)).append("\n");
    sb.append("    directAccessGrantsEnabled: ").append(toIndentedString(directAccessGrantsEnabled)).append("\n");
    sb.append("    serviceAccountsEnabled: ").append(toIndentedString(serviceAccountsEnabled)).append("\n");
    sb.append("    authorizationServicesEnabled: ").append(toIndentedString(authorizationServicesEnabled)).append("\n");
    sb.append("    directGrantsOnly: ").append(toIndentedString(directGrantsOnly)).append("\n");
    sb.append("    publicClient: ").append(toIndentedString(publicClient)).append("\n");
    sb.append("    frontchannelLogout: ").append(toIndentedString(frontchannelLogout)).append("\n");
    sb.append("    protocol: ").append(toIndentedString(protocol)).append("\n");
    sb.append("    attributes: ").append(toIndentedString(attributes)).append("\n");
    sb.append("    authenticationFlowBindingOverrides: ").append(toIndentedString(authenticationFlowBindingOverrides)).append("\n");
    sb.append("    fullScopeAllowed: ").append(toIndentedString(fullScopeAllowed)).append("\n");
    sb.append("    nodeReRegistrationTimeout: ").append(toIndentedString(nodeReRegistrationTimeout)).append("\n");
    sb.append("    registeredNodes: ").append(toIndentedString(registeredNodes)).append("\n");
    sb.append("    protocolMappers: ").append(toIndentedString(protocolMappers)).append("\n");
    sb.append("    clientTemplate: ").append(toIndentedString(clientTemplate)).append("\n");
    sb.append("    useTemplateConfig: ").append(toIndentedString(useTemplateConfig)).append("\n");
    sb.append("    useTemplateScope: ").append(toIndentedString(useTemplateScope)).append("\n");
    sb.append("    useTemplateMappers: ").append(toIndentedString(useTemplateMappers)).append("\n");
    sb.append("    defaultClientScopes: ").append(toIndentedString(defaultClientScopes)).append("\n");
    sb.append("    optionalClientScopes: ").append(toIndentedString(optionalClientScopes)).append("\n");
    sb.append("    authorizationSettings: ").append(toIndentedString(authorizationSettings)).append("\n");
    sb.append("    access: ").append(toIndentedString(access)).append("\n");
    sb.append("    origin: ").append(toIndentedString(origin)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
