/*
 * Keycloak Admin REST API
 * This is a REST API reference for the Keycloak Admin REST API.
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.keycloak.www.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

import java.util.ArrayList;
import java.util.List;
import org.keycloak.www.client.InlineResponseMapItems200;
/**
 * RequiredActionConfigInfoRepresentation
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-03-11T12:00:50.005853600+07:00[Asia/Bangkok]")

public class RequiredActionConfigInfoRepresentation {
  @JsonProperty("properties")
  private List<InlineResponseMapItems200> properties = null;

  public RequiredActionConfigInfoRepresentation properties(List<InlineResponseMapItems200> properties) {
    this.properties = properties;
    return this;
  }

  public RequiredActionConfigInfoRepresentation addPropertiesItem(InlineResponseMapItems200 propertiesItem) {
    if (this.properties == null) {
      this.properties = new ArrayList<>();
    }
    this.properties.add(propertiesItem);
    return this;
  }

   /**
   * Get properties
   * @return properties
  **/
  public List<InlineResponseMapItems200> getProperties() {
    return properties;
  }

  public void setProperties(List<InlineResponseMapItems200> properties) {
    this.properties = properties;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RequiredActionConfigInfoRepresentation requiredActionConfigInfoRepresentation = (RequiredActionConfigInfoRepresentation) o;
    return Objects.equals(this.properties, requiredActionConfigInfoRepresentation.properties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(properties);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RequiredActionConfigInfoRepresentation {\n");
    
    sb.append("    properties: ").append(toIndentedString(properties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
