/*
 * Keycloak Admin REST API
 * This is a REST API reference for the Keycloak Admin REST API.
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.keycloak.www.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

import java.util.ArrayList;
import java.util.List;
import org.keycloak.www.client.AdminrealmsAdminPermissionsClientAuthorizationSettingsAuthorizationSchema;
import org.keycloak.www.client.AdminrealmsAdminPermissionsClientAuthorizationSettingsPolicies;
import org.keycloak.www.client.AdminrealmsAdminPermissionsClientAuthorizationSettingsResources;
import org.keycloak.www.client.AdminrealmsAdminPermissionsClientAuthorizationSettingsScopes;
/**
 * ResourceServerRepresentation
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-03-11T12:00:50.005853600+07:00[Asia/Bangkok]")

public class ResourceServerRepresentation {
  @JsonProperty("id")
  private String id = null;

  @JsonProperty("clientId")
  private String clientId = null;

  @JsonProperty("name")
  private String name = null;

  @JsonProperty("allowRemoteResourceManagement")
  private Boolean allowRemoteResourceManagement = null;

  /**
   * Gets or Sets policyEnforcementMode
   */
  public enum PolicyEnforcementModeEnum {
    ENFORCING("ENFORCING"),
    PERMISSIVE("PERMISSIVE"),
    DISABLED("DISABLED");

    private String value;

    PolicyEnforcementModeEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static PolicyEnforcementModeEnum fromValue(String input) {
      for (PolicyEnforcementModeEnum b : PolicyEnforcementModeEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("policyEnforcementMode")
  private PolicyEnforcementModeEnum policyEnforcementMode = null;

  @JsonProperty("resources")
  private List<AdminrealmsAdminPermissionsClientAuthorizationSettingsResources> resources = null;

  @JsonProperty("policies")
  private List<AdminrealmsAdminPermissionsClientAuthorizationSettingsPolicies> policies = null;

  @JsonProperty("scopes")
  private List<AdminrealmsAdminPermissionsClientAuthorizationSettingsScopes> scopes = null;

  /**
   * Gets or Sets decisionStrategy
   */
  public enum DecisionStrategyEnum {
    AFFIRMATIVE("AFFIRMATIVE"),
    UNANIMOUS("UNANIMOUS"),
    CONSENSUS("CONSENSUS");

    private String value;

    DecisionStrategyEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static DecisionStrategyEnum fromValue(String input) {
      for (DecisionStrategyEnum b : DecisionStrategyEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("decisionStrategy")
  private DecisionStrategyEnum decisionStrategy = null;

  @JsonProperty("authorizationSchema")
  private AdminrealmsAdminPermissionsClientAuthorizationSettingsAuthorizationSchema authorizationSchema = null;

  public ResourceServerRepresentation id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public ResourceServerRepresentation clientId(String clientId) {
    this.clientId = clientId;
    return this;
  }

   /**
   * Get clientId
   * @return clientId
  **/
  public String getClientId() {
    return clientId;
  }

  public void setClientId(String clientId) {
    this.clientId = clientId;
  }

  public ResourceServerRepresentation name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public ResourceServerRepresentation allowRemoteResourceManagement(Boolean allowRemoteResourceManagement) {
    this.allowRemoteResourceManagement = allowRemoteResourceManagement;
    return this;
  }

   /**
   * Get allowRemoteResourceManagement
   * @return allowRemoteResourceManagement
  **/
  public Boolean isAllowRemoteResourceManagement() {
    return allowRemoteResourceManagement;
  }

  public void setAllowRemoteResourceManagement(Boolean allowRemoteResourceManagement) {
    this.allowRemoteResourceManagement = allowRemoteResourceManagement;
  }

  public ResourceServerRepresentation policyEnforcementMode(PolicyEnforcementModeEnum policyEnforcementMode) {
    this.policyEnforcementMode = policyEnforcementMode;
    return this;
  }

   /**
   * Get policyEnforcementMode
   * @return policyEnforcementMode
  **/
  public PolicyEnforcementModeEnum getPolicyEnforcementMode() {
    return policyEnforcementMode;
  }

  public void setPolicyEnforcementMode(PolicyEnforcementModeEnum policyEnforcementMode) {
    this.policyEnforcementMode = policyEnforcementMode;
  }

  public ResourceServerRepresentation resources(List<AdminrealmsAdminPermissionsClientAuthorizationSettingsResources> resources) {
    this.resources = resources;
    return this;
  }

  public ResourceServerRepresentation addResourcesItem(AdminrealmsAdminPermissionsClientAuthorizationSettingsResources resourcesItem) {
    if (this.resources == null) {
      this.resources = new ArrayList<>();
    }
    this.resources.add(resourcesItem);
    return this;
  }

   /**
   * Get resources
   * @return resources
  **/
  public List<AdminrealmsAdminPermissionsClientAuthorizationSettingsResources> getResources() {
    return resources;
  }

  public void setResources(List<AdminrealmsAdminPermissionsClientAuthorizationSettingsResources> resources) {
    this.resources = resources;
  }

  public ResourceServerRepresentation policies(List<AdminrealmsAdminPermissionsClientAuthorizationSettingsPolicies> policies) {
    this.policies = policies;
    return this;
  }

  public ResourceServerRepresentation addPoliciesItem(AdminrealmsAdminPermissionsClientAuthorizationSettingsPolicies policiesItem) {
    if (this.policies == null) {
      this.policies = new ArrayList<>();
    }
    this.policies.add(policiesItem);
    return this;
  }

   /**
   * Get policies
   * @return policies
  **/
  public List<AdminrealmsAdminPermissionsClientAuthorizationSettingsPolicies> getPolicies() {
    return policies;
  }

  public void setPolicies(List<AdminrealmsAdminPermissionsClientAuthorizationSettingsPolicies> policies) {
    this.policies = policies;
  }

  public ResourceServerRepresentation scopes(List<AdminrealmsAdminPermissionsClientAuthorizationSettingsScopes> scopes) {
    this.scopes = scopes;
    return this;
  }

  public ResourceServerRepresentation addScopesItem(AdminrealmsAdminPermissionsClientAuthorizationSettingsScopes scopesItem) {
    if (this.scopes == null) {
      this.scopes = new ArrayList<>();
    }
    this.scopes.add(scopesItem);
    return this;
  }

   /**
   * Get scopes
   * @return scopes
  **/
  public List<AdminrealmsAdminPermissionsClientAuthorizationSettingsScopes> getScopes() {
    return scopes;
  }

  public void setScopes(List<AdminrealmsAdminPermissionsClientAuthorizationSettingsScopes> scopes) {
    this.scopes = scopes;
  }

  public ResourceServerRepresentation decisionStrategy(DecisionStrategyEnum decisionStrategy) {
    this.decisionStrategy = decisionStrategy;
    return this;
  }

   /**
   * Get decisionStrategy
   * @return decisionStrategy
  **/
  public DecisionStrategyEnum getDecisionStrategy() {
    return decisionStrategy;
  }

  public void setDecisionStrategy(DecisionStrategyEnum decisionStrategy) {
    this.decisionStrategy = decisionStrategy;
  }

  public ResourceServerRepresentation authorizationSchema(AdminrealmsAdminPermissionsClientAuthorizationSettingsAuthorizationSchema authorizationSchema) {
    this.authorizationSchema = authorizationSchema;
    return this;
  }

   /**
   * Get authorizationSchema
   * @return authorizationSchema
  **/
  public AdminrealmsAdminPermissionsClientAuthorizationSettingsAuthorizationSchema getAuthorizationSchema() {
    return authorizationSchema;
  }

  public void setAuthorizationSchema(AdminrealmsAdminPermissionsClientAuthorizationSettingsAuthorizationSchema authorizationSchema) {
    this.authorizationSchema = authorizationSchema;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ResourceServerRepresentation resourceServerRepresentation = (ResourceServerRepresentation) o;
    return Objects.equals(this.id, resourceServerRepresentation.id) &&
        Objects.equals(this.clientId, resourceServerRepresentation.clientId) &&
        Objects.equals(this.name, resourceServerRepresentation.name) &&
        Objects.equals(this.allowRemoteResourceManagement, resourceServerRepresentation.allowRemoteResourceManagement) &&
        Objects.equals(this.policyEnforcementMode, resourceServerRepresentation.policyEnforcementMode) &&
        Objects.equals(this.resources, resourceServerRepresentation.resources) &&
        Objects.equals(this.policies, resourceServerRepresentation.policies) &&
        Objects.equals(this.scopes, resourceServerRepresentation.scopes) &&
        Objects.equals(this.decisionStrategy, resourceServerRepresentation.decisionStrategy) &&
        Objects.equals(this.authorizationSchema, resourceServerRepresentation.authorizationSchema);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, clientId, name, allowRemoteResourceManagement, policyEnforcementMode, resources, policies, scopes, decisionStrategy, authorizationSchema);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ResourceServerRepresentation {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    clientId: ").append(toIndentedString(clientId)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    allowRemoteResourceManagement: ").append(toIndentedString(allowRemoteResourceManagement)).append("\n");
    sb.append("    policyEnforcementMode: ").append(toIndentedString(policyEnforcementMode)).append("\n");
    sb.append("    resources: ").append(toIndentedString(resources)).append("\n");
    sb.append("    policies: ").append(toIndentedString(policies)).append("\n");
    sb.append("    scopes: ").append(toIndentedString(scopes)).append("\n");
    sb.append("    decisionStrategy: ").append(toIndentedString(decisionStrategy)).append("\n");
    sb.append("    authorizationSchema: ").append(toIndentedString(authorizationSchema)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
