/*
 * Keycloak Admin REST API
 * This is a REST API reference for the Keycloak Admin REST API.
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.keycloak.www.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.keycloak.www.client.AdminrealmsAdminPermissionsClientAuthorizationSettingsOwner;
import org.keycloak.www.client.AdminrealmsAdminPermissionsClientAuthorizationSettingsScopes;
/**
 * ResourceRepresentation
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-03-11T12:00:50.005853600+07:00[Asia/Bangkok]")

public class ResourceRepresentation {
  @JsonProperty("_id")
  private String _id = null;

  @JsonProperty("name")
  private String name = null;

  @JsonProperty("uris")
  private List<String> uris = null;

  @JsonProperty("type")
  private String type = null;

  @JsonProperty("scopes")
  private List<AdminrealmsAdminPermissionsClientAuthorizationSettingsScopes> scopes = null;

  @JsonProperty("icon_uri")
  private String iconUri = null;

  @JsonProperty("owner")
  private AdminrealmsAdminPermissionsClientAuthorizationSettingsOwner owner = null;

  @JsonProperty("ownerManagedAccess")
  private Boolean ownerManagedAccess = null;

  @JsonProperty("displayName")
  private String displayName = null;

  @JsonProperty("attributes")
  private Map<String, List<String>> attributes = null;

  @JsonProperty("uri")
  private String uri = null;

  @JsonProperty("scopesUma")
  private List<AdminrealmsAdminPermissionsClientAuthorizationSettingsScopes> scopesUma = null;

  public ResourceRepresentation _id(String _id) {
    this._id = _id;
    return this;
  }

   /**
   * Get _id
   * @return _id
  **/
  public String getId() {
    return _id;
  }

  public void setId(String _id) {
    this._id = _id;
  }

  public ResourceRepresentation name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public ResourceRepresentation uris(List<String> uris) {
    this.uris = uris;
    return this;
  }

  public ResourceRepresentation addUrisItem(String urisItem) {
    if (this.uris == null) {
      this.uris = new ArrayList<>();
    }
    this.uris.add(urisItem);
    return this;
  }

   /**
   * Get uris
   * @return uris
  **/
  public List<String> getUris() {
    return uris;
  }

  public void setUris(List<String> uris) {
    this.uris = uris;
  }

  public ResourceRepresentation type(String type) {
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  public String getType() {
    return type;
  }

  public void setType(String type) {
    this.type = type;
  }

  public ResourceRepresentation scopes(List<AdminrealmsAdminPermissionsClientAuthorizationSettingsScopes> scopes) {
    this.scopes = scopes;
    return this;
  }

  public ResourceRepresentation addScopesItem(AdminrealmsAdminPermissionsClientAuthorizationSettingsScopes scopesItem) {
    if (this.scopes == null) {
      this.scopes = new ArrayList<>();
    }
    this.scopes.add(scopesItem);
    return this;
  }

   /**
   * Get scopes
   * @return scopes
  **/
  public List<AdminrealmsAdminPermissionsClientAuthorizationSettingsScopes> getScopes() {
    return scopes;
  }

  public void setScopes(List<AdminrealmsAdminPermissionsClientAuthorizationSettingsScopes> scopes) {
    this.scopes = scopes;
  }

  public ResourceRepresentation iconUri(String iconUri) {
    this.iconUri = iconUri;
    return this;
  }

   /**
   * Get iconUri
   * @return iconUri
  **/
  public String getIconUri() {
    return iconUri;
  }

  public void setIconUri(String iconUri) {
    this.iconUri = iconUri;
  }

  public ResourceRepresentation owner(AdminrealmsAdminPermissionsClientAuthorizationSettingsOwner owner) {
    this.owner = owner;
    return this;
  }

   /**
   * Get owner
   * @return owner
  **/
  public AdminrealmsAdminPermissionsClientAuthorizationSettingsOwner getOwner() {
    return owner;
  }

  public void setOwner(AdminrealmsAdminPermissionsClientAuthorizationSettingsOwner owner) {
    this.owner = owner;
  }

  public ResourceRepresentation ownerManagedAccess(Boolean ownerManagedAccess) {
    this.ownerManagedAccess = ownerManagedAccess;
    return this;
  }

   /**
   * Get ownerManagedAccess
   * @return ownerManagedAccess
  **/
  public Boolean isOwnerManagedAccess() {
    return ownerManagedAccess;
  }

  public void setOwnerManagedAccess(Boolean ownerManagedAccess) {
    this.ownerManagedAccess = ownerManagedAccess;
  }

  public ResourceRepresentation displayName(String displayName) {
    this.displayName = displayName;
    return this;
  }

   /**
   * Get displayName
   * @return displayName
  **/
  public String getDisplayName() {
    return displayName;
  }

  public void setDisplayName(String displayName) {
    this.displayName = displayName;
  }

  public ResourceRepresentation attributes(Map<String, List<String>> attributes) {
    this.attributes = attributes;
    return this;
  }

  public ResourceRepresentation putAttributesItem(String key, List<String> attributesItem) {
    if (this.attributes == null) {
      this.attributes = new HashMap<>();
    }
    this.attributes.put(key, attributesItem);
    return this;
  }

   /**
   * Get attributes
   * @return attributes
  **/
  public Map<String, List<String>> getAttributes() {
    return attributes;
  }

  public void setAttributes(Map<String, List<String>> attributes) {
    this.attributes = attributes;
  }

  public ResourceRepresentation uri(String uri) {
    this.uri = uri;
    return this;
  }

   /**
   * Get uri
   * @return uri
  **/
  public String getUri() {
    return uri;
  }

  public void setUri(String uri) {
    this.uri = uri;
  }

  public ResourceRepresentation scopesUma(List<AdminrealmsAdminPermissionsClientAuthorizationSettingsScopes> scopesUma) {
    this.scopesUma = scopesUma;
    return this;
  }

  public ResourceRepresentation addScopesUmaItem(AdminrealmsAdminPermissionsClientAuthorizationSettingsScopes scopesUmaItem) {
    if (this.scopesUma == null) {
      this.scopesUma = new ArrayList<>();
    }
    this.scopesUma.add(scopesUmaItem);
    return this;
  }

   /**
   * Get scopesUma
   * @return scopesUma
  **/
  public List<AdminrealmsAdminPermissionsClientAuthorizationSettingsScopes> getScopesUma() {
    return scopesUma;
  }

  public void setScopesUma(List<AdminrealmsAdminPermissionsClientAuthorizationSettingsScopes> scopesUma) {
    this.scopesUma = scopesUma;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ResourceRepresentation resourceRepresentation = (ResourceRepresentation) o;
    return Objects.equals(this._id, resourceRepresentation._id) &&
        Objects.equals(this.name, resourceRepresentation.name) &&
        Objects.equals(this.uris, resourceRepresentation.uris) &&
        Objects.equals(this.type, resourceRepresentation.type) &&
        Objects.equals(this.scopes, resourceRepresentation.scopes) &&
        Objects.equals(this.iconUri, resourceRepresentation.iconUri) &&
        Objects.equals(this.owner, resourceRepresentation.owner) &&
        Objects.equals(this.ownerManagedAccess, resourceRepresentation.ownerManagedAccess) &&
        Objects.equals(this.displayName, resourceRepresentation.displayName) &&
        Objects.equals(this.attributes, resourceRepresentation.attributes) &&
        Objects.equals(this.uri, resourceRepresentation.uri) &&
        Objects.equals(this.scopesUma, resourceRepresentation.scopesUma);
  }

  @Override
  public int hashCode() {
    return Objects.hash(_id, name, uris, type, scopes, iconUri, owner, ownerManagedAccess, displayName, attributes, uri, scopesUma);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ResourceRepresentation {\n");
    
    sb.append("    _id: ").append(toIndentedString(_id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    uris: ").append(toIndentedString(uris)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    scopes: ").append(toIndentedString(scopes)).append("\n");
    sb.append("    iconUri: ").append(toIndentedString(iconUri)).append("\n");
    sb.append("    owner: ").append(toIndentedString(owner)).append("\n");
    sb.append("    ownerManagedAccess: ").append(toIndentedString(ownerManagedAccess)).append("\n");
    sb.append("    displayName: ").append(toIndentedString(displayName)).append("\n");
    sb.append("    attributes: ").append(toIndentedString(attributes)).append("\n");
    sb.append("    uri: ").append(toIndentedString(uri)).append("\n");
    sb.append("    scopesUma: ").append(toIndentedString(scopesUma)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
