/*
 * Keycloak Admin REST API
 * This is a REST API reference for the Keycloak Admin REST API.
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.keycloak.www.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

import java.util.ArrayList;
import java.util.List;
import org.keycloak.www.client.AdminrealmsAdminPermissionsClientAuthorizationSettingsPolicies;
import org.keycloak.www.client.ResourceRepresentation;
/**
 * ScopeRepresentation
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-03-11T12:00:50.005853600+07:00[Asia/Bangkok]")

public class ScopeRepresentation {
  @JsonProperty("id")
  private String id = null;

  @JsonProperty("name")
  private String name = null;

  @JsonProperty("iconUri")
  private String iconUri = null;

  @JsonProperty("policies")
  private List<AdminrealmsAdminPermissionsClientAuthorizationSettingsPolicies> policies = null;

  @JsonProperty("resources")
  private List<ResourceRepresentation> resources = null;

  @JsonProperty("displayName")
  private String displayName = null;

  public ScopeRepresentation id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public ScopeRepresentation name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public ScopeRepresentation iconUri(String iconUri) {
    this.iconUri = iconUri;
    return this;
  }

   /**
   * Get iconUri
   * @return iconUri
  **/
  public String getIconUri() {
    return iconUri;
  }

  public void setIconUri(String iconUri) {
    this.iconUri = iconUri;
  }

  public ScopeRepresentation policies(List<AdminrealmsAdminPermissionsClientAuthorizationSettingsPolicies> policies) {
    this.policies = policies;
    return this;
  }

  public ScopeRepresentation addPoliciesItem(AdminrealmsAdminPermissionsClientAuthorizationSettingsPolicies policiesItem) {
    if (this.policies == null) {
      this.policies = new ArrayList<>();
    }
    this.policies.add(policiesItem);
    return this;
  }

   /**
   * Get policies
   * @return policies
  **/
  public List<AdminrealmsAdminPermissionsClientAuthorizationSettingsPolicies> getPolicies() {
    return policies;
  }

  public void setPolicies(List<AdminrealmsAdminPermissionsClientAuthorizationSettingsPolicies> policies) {
    this.policies = policies;
  }

  public ScopeRepresentation resources(List<ResourceRepresentation> resources) {
    this.resources = resources;
    return this;
  }

  public ScopeRepresentation addResourcesItem(ResourceRepresentation resourcesItem) {
    if (this.resources == null) {
      this.resources = new ArrayList<>();
    }
    this.resources.add(resourcesItem);
    return this;
  }

   /**
   * Get resources
   * @return resources
  **/
  public List<ResourceRepresentation> getResources() {
    return resources;
  }

  public void setResources(List<ResourceRepresentation> resources) {
    this.resources = resources;
  }

  public ScopeRepresentation displayName(String displayName) {
    this.displayName = displayName;
    return this;
  }

   /**
   * Get displayName
   * @return displayName
  **/
  public String getDisplayName() {
    return displayName;
  }

  public void setDisplayName(String displayName) {
    this.displayName = displayName;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ScopeRepresentation scopeRepresentation = (ScopeRepresentation) o;
    return Objects.equals(this.id, scopeRepresentation.id) &&
        Objects.equals(this.name, scopeRepresentation.name) &&
        Objects.equals(this.iconUri, scopeRepresentation.iconUri) &&
        Objects.equals(this.policies, scopeRepresentation.policies) &&
        Objects.equals(this.resources, scopeRepresentation.resources) &&
        Objects.equals(this.displayName, scopeRepresentation.displayName);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, iconUri, policies, resources, displayName);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ScopeRepresentation {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    iconUri: ").append(toIndentedString(iconUri)).append("\n");
    sb.append("    policies: ").append(toIndentedString(policies)).append("\n");
    sb.append("    resources: ").append(toIndentedString(resources)).append("\n");
    sb.append("    displayName: ").append(toIndentedString(displayName)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
