/*
 * Keycloak Admin REST API
 * This is a REST API reference for the Keycloak Admin REST API.
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.keycloak.www.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * SocialLinkRepresentation
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-03-11T12:00:50.005853600+07:00[Asia/Bangkok]")

public class SocialLinkRepresentation {
  @JsonProperty("socialProvider")
  private String socialProvider = null;

  @JsonProperty("socialUserId")
  private String socialUserId = null;

  @JsonProperty("socialUsername")
  private String socialUsername = null;

  public SocialLinkRepresentation socialProvider(String socialProvider) {
    this.socialProvider = socialProvider;
    return this;
  }

   /**
   * Get socialProvider
   * @return socialProvider
  **/
  public String getSocialProvider() {
    return socialProvider;
  }

  public void setSocialProvider(String socialProvider) {
    this.socialProvider = socialProvider;
  }

  public SocialLinkRepresentation socialUserId(String socialUserId) {
    this.socialUserId = socialUserId;
    return this;
  }

   /**
   * Get socialUserId
   * @return socialUserId
  **/
  public String getSocialUserId() {
    return socialUserId;
  }

  public void setSocialUserId(String socialUserId) {
    this.socialUserId = socialUserId;
  }

  public SocialLinkRepresentation socialUsername(String socialUsername) {
    this.socialUsername = socialUsername;
    return this;
  }

   /**
   * Get socialUsername
   * @return socialUsername
  **/
  public String getSocialUsername() {
    return socialUsername;
  }

  public void setSocialUsername(String socialUsername) {
    this.socialUsername = socialUsername;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SocialLinkRepresentation socialLinkRepresentation = (SocialLinkRepresentation) o;
    return Objects.equals(this.socialProvider, socialLinkRepresentation.socialProvider) &&
        Objects.equals(this.socialUserId, socialLinkRepresentation.socialUserId) &&
        Objects.equals(this.socialUsername, socialLinkRepresentation.socialUsername);
  }

  @Override
  public int hashCode() {
    return Objects.hash(socialProvider, socialUserId, socialUsername);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SocialLinkRepresentation {\n");
    
    sb.append("    socialProvider: ").append(toIndentedString(socialProvider)).append("\n");
    sb.append("    socialUserId: ").append(toIndentedString(socialUserId)).append("\n");
    sb.append("    socialUsername: ").append(toIndentedString(socialUsername)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
