/*
 * Keycloak Admin REST API
 * This is a REST API reference for the Keycloak Admin REST API.
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.keycloak.www.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

import java.util.ArrayList;
import java.util.List;
/**
 * UPAttributePermissions
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-03-11T12:00:50.005853600+07:00[Asia/Bangkok]")

public class UPAttributePermissions {
  @JsonProperty("view")
  private List<String> view = null;

  @JsonProperty("edit")
  private List<String> edit = null;

  public UPAttributePermissions view(List<String> view) {
    this.view = view;
    return this;
  }

  public UPAttributePermissions addViewItem(String viewItem) {
    if (this.view == null) {
      this.view = new ArrayList<>();
    }
    this.view.add(viewItem);
    return this;
  }

   /**
   * Get view
   * @return view
  **/
  public List<String> getView() {
    return view;
  }

  public void setView(List<String> view) {
    this.view = view;
  }

  public UPAttributePermissions edit(List<String> edit) {
    this.edit = edit;
    return this;
  }

  public UPAttributePermissions addEditItem(String editItem) {
    if (this.edit == null) {
      this.edit = new ArrayList<>();
    }
    this.edit.add(editItem);
    return this;
  }

   /**
   * Get edit
   * @return edit
  **/
  public List<String> getEdit() {
    return edit;
  }

  public void setEdit(List<String> edit) {
    this.edit = edit;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UPAttributePermissions upAttributePermissions = (UPAttributePermissions) o;
    return Objects.equals(this.view, upAttributePermissions.view) &&
        Objects.equals(this.edit, upAttributePermissions.edit);
  }

  @Override
  public int hashCode() {
    return Objects.hash(view, edit);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UPAttributePermissions {\n");
    
    sb.append("    view: ").append(toIndentedString(view)).append("\n");
    sb.append("    edit: ").append(toIndentedString(edit)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
