/*
 * Keycloak Admin REST API
 * This is a REST API reference for the Keycloak Admin REST API.
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.keycloak.www.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

import java.util.ArrayList;
import java.util.List;
import org.keycloak.www.client.AdminrealmsUserProfileMetadataGroups;
import org.keycloak.www.client.AdminrealmsrealmusersprofileAttributes;
/**
 * UPConfig
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-03-11T12:00:50.005853600+07:00[Asia/Bangkok]")

public class UPConfig {
  @JsonProperty("attributes")
  private List<AdminrealmsrealmusersprofileAttributes> attributes = null;

  @JsonProperty("groups")
  private List<AdminrealmsUserProfileMetadataGroups> groups = null;

  /**
   * Gets or Sets unmanagedAttributePolicy
   */
  public enum UnmanagedAttributePolicyEnum {
    ENABLED("ENABLED"),
    ADMIN_VIEW("ADMIN_VIEW"),
    ADMIN_EDIT("ADMIN_EDIT");

    private String value;

    UnmanagedAttributePolicyEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static UnmanagedAttributePolicyEnum fromValue(String input) {
      for (UnmanagedAttributePolicyEnum b : UnmanagedAttributePolicyEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("unmanagedAttributePolicy")
  private UnmanagedAttributePolicyEnum unmanagedAttributePolicy = null;

  public UPConfig attributes(List<AdminrealmsrealmusersprofileAttributes> attributes) {
    this.attributes = attributes;
    return this;
  }

  public UPConfig addAttributesItem(AdminrealmsrealmusersprofileAttributes attributesItem) {
    if (this.attributes == null) {
      this.attributes = new ArrayList<>();
    }
    this.attributes.add(attributesItem);
    return this;
  }

   /**
   * Get attributes
   * @return attributes
  **/
  public List<AdminrealmsrealmusersprofileAttributes> getAttributes() {
    return attributes;
  }

  public void setAttributes(List<AdminrealmsrealmusersprofileAttributes> attributes) {
    this.attributes = attributes;
  }

  public UPConfig groups(List<AdminrealmsUserProfileMetadataGroups> groups) {
    this.groups = groups;
    return this;
  }

  public UPConfig addGroupsItem(AdminrealmsUserProfileMetadataGroups groupsItem) {
    if (this.groups == null) {
      this.groups = new ArrayList<>();
    }
    this.groups.add(groupsItem);
    return this;
  }

   /**
   * Get groups
   * @return groups
  **/
  public List<AdminrealmsUserProfileMetadataGroups> getGroups() {
    return groups;
  }

  public void setGroups(List<AdminrealmsUserProfileMetadataGroups> groups) {
    this.groups = groups;
  }

  public UPConfig unmanagedAttributePolicy(UnmanagedAttributePolicyEnum unmanagedAttributePolicy) {
    this.unmanagedAttributePolicy = unmanagedAttributePolicy;
    return this;
  }

   /**
   * Get unmanagedAttributePolicy
   * @return unmanagedAttributePolicy
  **/
  public UnmanagedAttributePolicyEnum getUnmanagedAttributePolicy() {
    return unmanagedAttributePolicy;
  }

  public void setUnmanagedAttributePolicy(UnmanagedAttributePolicyEnum unmanagedAttributePolicy) {
    this.unmanagedAttributePolicy = unmanagedAttributePolicy;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UPConfig upConfig = (UPConfig) o;
    return Objects.equals(this.attributes, upConfig.attributes) &&
        Objects.equals(this.groups, upConfig.groups) &&
        Objects.equals(this.unmanagedAttributePolicy, upConfig.unmanagedAttributePolicy);
  }

  @Override
  public int hashCode() {
    return Objects.hash(attributes, groups, unmanagedAttributePolicy);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UPConfig {\n");
    
    sb.append("    attributes: ").append(toIndentedString(attributes)).append("\n");
    sb.append("    groups: ").append(toIndentedString(groups)).append("\n");
    sb.append("    unmanagedAttributePolicy: ").append(toIndentedString(unmanagedAttributePolicy)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
