/*
 * Keycloak Admin REST API
 * This is a REST API reference for the Keycloak Admin REST API.
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.keycloak.www.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

import java.util.HashMap;
import java.util.List;
import java.util.Map;
/**
 * UserProfileAttributeGroupMetadata
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-03-11T12:00:50.005853600+07:00[Asia/Bangkok]")

public class UserProfileAttributeGroupMetadata {
  @JsonProperty("name")
  private String name = null;

  @JsonProperty("displayHeader")
  private String displayHeader = null;

  @JsonProperty("displayDescription")
  private String displayDescription = null;

  @JsonProperty("annotations")
  private Map<String, Object> annotations = null;

  public UserProfileAttributeGroupMetadata name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public UserProfileAttributeGroupMetadata displayHeader(String displayHeader) {
    this.displayHeader = displayHeader;
    return this;
  }

   /**
   * Get displayHeader
   * @return displayHeader
  **/
  public String getDisplayHeader() {
    return displayHeader;
  }

  public void setDisplayHeader(String displayHeader) {
    this.displayHeader = displayHeader;
  }

  public UserProfileAttributeGroupMetadata displayDescription(String displayDescription) {
    this.displayDescription = displayDescription;
    return this;
  }

   /**
   * Get displayDescription
   * @return displayDescription
  **/
  public String getDisplayDescription() {
    return displayDescription;
  }

  public void setDisplayDescription(String displayDescription) {
    this.displayDescription = displayDescription;
  }

  public UserProfileAttributeGroupMetadata annotations(Map<String, Object> annotations) {
    this.annotations = annotations;
    return this;
  }

  public UserProfileAttributeGroupMetadata putAnnotationsItem(String key, Object annotationsItem) {
    if (this.annotations == null) {
      this.annotations = new HashMap<>();
    }
    this.annotations.put(key, annotationsItem);
    return this;
  }

   /**
   * Get annotations
   * @return annotations
  **/
  public Map<String, Object> getAnnotations() {
    return annotations;
  }

  public void setAnnotations(Map<String, Object> annotations) {
    this.annotations = annotations;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UserProfileAttributeGroupMetadata userProfileAttributeGroupMetadata = (UserProfileAttributeGroupMetadata) o;
    return Objects.equals(this.name, userProfileAttributeGroupMetadata.name) &&
        Objects.equals(this.displayHeader, userProfileAttributeGroupMetadata.displayHeader) &&
        Objects.equals(this.displayDescription, userProfileAttributeGroupMetadata.displayDescription) &&
        Objects.equals(this.annotations, userProfileAttributeGroupMetadata.annotations);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, displayHeader, displayDescription, annotations);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UserProfileAttributeGroupMetadata {\n");
    
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    displayHeader: ").append(toIndentedString(displayHeader)).append("\n");
    sb.append("    displayDescription: ").append(toIndentedString(displayDescription)).append("\n");
    sb.append("    annotations: ").append(toIndentedString(annotations)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
