/*
 * Keycloak Admin REST API
 * This is a REST API reference for the Keycloak Admin REST API.
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.keycloak.www.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

import java.util.ArrayList;
import java.util.List;
/**
 * UserConsentRepresentation
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-03-11T12:00:50.005853600+07:00[Asia/Bangkok]")

public class UserConsentRepresentation {
  @JsonProperty("clientId")
  private String clientId = null;

  @JsonProperty("grantedClientScopes")
  private List<String> grantedClientScopes = null;

  @JsonProperty("createdDate")
  private Long createdDate = null;

  @JsonProperty("lastUpdatedDate")
  private Long lastUpdatedDate = null;

  @JsonProperty("grantedRealmRoles")
  private List<String> grantedRealmRoles = null;

  public UserConsentRepresentation clientId(String clientId) {
    this.clientId = clientId;
    return this;
  }

   /**
   * Get clientId
   * @return clientId
  **/
  public String getClientId() {
    return clientId;
  }

  public void setClientId(String clientId) {
    this.clientId = clientId;
  }

  public UserConsentRepresentation grantedClientScopes(List<String> grantedClientScopes) {
    this.grantedClientScopes = grantedClientScopes;
    return this;
  }

  public UserConsentRepresentation addGrantedClientScopesItem(String grantedClientScopesItem) {
    if (this.grantedClientScopes == null) {
      this.grantedClientScopes = new ArrayList<>();
    }
    this.grantedClientScopes.add(grantedClientScopesItem);
    return this;
  }

   /**
   * Get grantedClientScopes
   * @return grantedClientScopes
  **/
  public List<String> getGrantedClientScopes() {
    return grantedClientScopes;
  }

  public void setGrantedClientScopes(List<String> grantedClientScopes) {
    this.grantedClientScopes = grantedClientScopes;
  }

  public UserConsentRepresentation createdDate(Long createdDate) {
    this.createdDate = createdDate;
    return this;
  }

   /**
   * Get createdDate
   * @return createdDate
  **/
  public Long getCreatedDate() {
    return createdDate;
  }

  public void setCreatedDate(Long createdDate) {
    this.createdDate = createdDate;
  }

  public UserConsentRepresentation lastUpdatedDate(Long lastUpdatedDate) {
    this.lastUpdatedDate = lastUpdatedDate;
    return this;
  }

   /**
   * Get lastUpdatedDate
   * @return lastUpdatedDate
  **/
  public Long getLastUpdatedDate() {
    return lastUpdatedDate;
  }

  public void setLastUpdatedDate(Long lastUpdatedDate) {
    this.lastUpdatedDate = lastUpdatedDate;
  }

  public UserConsentRepresentation grantedRealmRoles(List<String> grantedRealmRoles) {
    this.grantedRealmRoles = grantedRealmRoles;
    return this;
  }

  public UserConsentRepresentation addGrantedRealmRolesItem(String grantedRealmRolesItem) {
    if (this.grantedRealmRoles == null) {
      this.grantedRealmRoles = new ArrayList<>();
    }
    this.grantedRealmRoles.add(grantedRealmRolesItem);
    return this;
  }

   /**
   * Get grantedRealmRoles
   * @return grantedRealmRoles
  **/
  public List<String> getGrantedRealmRoles() {
    return grantedRealmRoles;
  }

  public void setGrantedRealmRoles(List<String> grantedRealmRoles) {
    this.grantedRealmRoles = grantedRealmRoles;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UserConsentRepresentation userConsentRepresentation = (UserConsentRepresentation) o;
    return Objects.equals(this.clientId, userConsentRepresentation.clientId) &&
        Objects.equals(this.grantedClientScopes, userConsentRepresentation.grantedClientScopes) &&
        Objects.equals(this.createdDate, userConsentRepresentation.createdDate) &&
        Objects.equals(this.lastUpdatedDate, userConsentRepresentation.lastUpdatedDate) &&
        Objects.equals(this.grantedRealmRoles, userConsentRepresentation.grantedRealmRoles);
  }

  @Override
  public int hashCode() {
    return Objects.hash(clientId, grantedClientScopes, createdDate, lastUpdatedDate, grantedRealmRoles);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UserConsentRepresentation {\n");
    
    sb.append("    clientId: ").append(toIndentedString(clientId)).append("\n");
    sb.append("    grantedClientScopes: ").append(toIndentedString(grantedClientScopes)).append("\n");
    sb.append("    createdDate: ").append(toIndentedString(createdDate)).append("\n");
    sb.append("    lastUpdatedDate: ").append(toIndentedString(lastUpdatedDate)).append("\n");
    sb.append("    grantedRealmRoles: ").append(toIndentedString(grantedRealmRoles)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
