# yaml-language-server: $schema=https://json-schema.axonivy.com/app/12.0.0/databases.json
Databases:
  axonivysystemdatabase:
    Url: jdbc:hsqldb:mem:axonivysystemdatabase
    Driver: org.hsqldb.jdbc.JDBCDriver
    Password: ${decrypt:}
