# yaml-language-server: $schema=https://json-schema.axonivy.com/app/12.0.0/rest-clients.json
RestClients:
  #This is a REST API reference for the Keycloak Admin REST API.
  Keycloak (Keycloak Admin REST API):
    UUID: 72e7f221-b3d8-4d70-9d2c-3d5ef73d7ac5
    Url: ${ivy.var.keycloakConnector.url}
    Icon: res:/webContent/icons/keycloak.png
    Features:
    - ch.ivyteam.ivy.rest.client.mapper.JsonFeature
    - com.axonivy.connector.keycloak.auth.KeycloakAuthFeature
    OpenAPI:
      SpecUrl: https://www.keycloak.org/docs-api/latest/rest-api/openapi.json
      Namespace: org.keycloak.www.client
      ResolveFully: true
