# yaml-language-server: $schema=https://json-schema.axonivy.com/app/12.0.0/rest-clients.json
RestClients:
  #This is a REST API reference for the Keycloak Admin REST API.
  Keycloak (Keycloak Admin REST API):
    UUID: f609430c-21e8-4851-9aac-d7a5ececc750
    Url: ${ivy.var.keycloakConnector.url}
    Icon: res:/webContent/icons/keycloak.png
    Features:
    - ch.ivyteam.ivy.rest.client.mapper.JsonFeature
    OpenAPI:
      SpecUrl: https://www.keycloak.org/docs-api/latest/rest-api/openapi.json
      Namespace: org.keycloak.www.client
      ResolveFully: true
