# yaml-language-server: $schema=https://json-schema.axonivy.com/app/12.0.0/variables.json
Variables:
  keyCloakConnector:
    # url to connect to keycloak instance e.g. "http://localhost:8090"
    url: ""
    # username of keycloak admin user
    username: ""
    # password of keycloak admin user
    password: ""
    realmName: ""
    # email which would send confirmation for applicant
    mailSender: ""
