# yaml-language-server: $schema=https://json-schema.axonivy.com/app/12.0.0/variables.json
Variables:
  keyCloakConnector:
    # Url to connect to the Keycloak instance
    url: ""
    # username of keycloak admin user
    username: ""
    # password of keycloak admin user
    #[password]
    password: ""
    # The realm name on the KeyCloak instance
    realmName: ""
    # Email which would send confirmation for applicant
    mailSender: ""
