# yaml-language-server: $schema=https://json-schema.axonivy.com/app/12.0.0/variables.json
Variables:
  keyCloakConnector:
    url: ""
    username: ""
    #[password]
    password: ${decrypt:}
    realmName: ""
